---
kind: CronJob
schedule: "*/20 * * * *"

service:
  enabled: true

serviceMonitor:
  enabled: true

deschedulerPolicy:
  profiles:
    - name: default
      pluginConfig:
        - name: DefaultEvictor
          args:
            ignorePvcPods: true
            evictLocalStoragePods: false
            evictSystemCriticalPods: false
        - name: RemoveDuplicates
        - name: RemovePodsViolatingTopologySpreadConstraint
        - name: RemovePodsViolatingNodeAffinity
          args:
            nodeAffinityType:
              - requiredDuringSchedulingIgnoredDuringExecution
        - name: RemovePodsViolatingInterPodAntiAffinity
        - name: RemoveFailedPods
        - name: RemovePodsHavingTooManyRestarts
          args:
            podRestartThreshold: 100
            includingInitContainers: true
      plugins:
        balance:
          enabled:
            - RemoveDuplicates
            - RemovePodsViolatingTopologySpreadConstraint
        deschedule:
          enabled:
            - RemovePodsViolatingNodeAffinity
            - RemovePodsViolatingInterPodAntiAffinity
            - RemoveFailedPods
            - RemovePodsHavingTooManyRestarts
        filter:
          enabled:
            - DefaultEvictor
