apiVersion: v1
kind: Secret
metadata:
    name: dragonfly-secret
stringData:
    REDIS_PASSWORD: ENC[AES256_GCM,data:HsZEA9hJG5oSmEP/mOGwwx2roWrZxYmU5M23H6C4exPCz9SFqYnaXpN9t6Z369zwT3AZS4x1POjKtQZ42YR2qQ==,iv:VFu5CE0eSNvGvTfY23XQCJHfDhDN+B8gJAgC0hzrSKU=,tag:qFFerT6rmWKeoNa8ftgU8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPMGxFSGQ5bDd5NHBpYUgw
            UFJCZVAxdVFBWmkraERHdEJzNGZBUEVZY2x3Cmp1QXNyRkRzUEJiVTdoSzU4Y3dp
            eFdFQ3JOL25KbWhHNVhPTDVxOEZrUTgKLS0tIExuUm9kTXBzQU5TbDNSMDIrMnUz
            dHR3VmVrek03UHBwOTFPalR1YlhQWncKSEJ20jgqvwOrnvoGJD0MEyRN8mvFqTSb
            AjHOmrSXtBnaLmzXdaFKVrI0oWcOPfPbKcnZPKz16PuS+DMSbkKwWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-21T13:27:25Z"
    mac: ENC[AES256_GCM,data:9trfgtKD8q72gGe9unXzPiCFityOd7IhDb7N8/0Hu28dquHIGcV3IjULyBw/4T0sBsBh7oRwLIrSBLSNXp92z0gW5l4KxTipygybx8gQ2DeOt/UzPbxkAQfSB/EG28Sm7eB99I6ZYdgEs1eWWpYsujkJSRfBB8prbe8wmV7RQsU=,iv:P/PUm2r9g+LvbJ6t3Ab4Plcs6BnEyzn0t6T6QBFCYyc=,tag:L7UY63MO4k0L41gCGyF1Lg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
