---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./external-secret.yaml
  - ./blueprint-secrets.yaml
  - ./cluster.yaml
  - ./scheduled-backup.yaml
  - ./podmonitor.yaml
  - ./ciliumnetworkpolicy.yaml
configMapGenerator:
  - name: authentik-blueprints
    files:
      - blueprints/00-groups.yaml
      - blueprints/01-access-control.yaml
      - blueprints/bar-assistant.yaml
      - blueprints/forgejo.yaml
      - blueprints/gotosocial.yaml
      - blueprints/grafana.yaml
      - blueprints/harbor.yaml
      - blueprints/miniflux.yaml
      - blueprints/renovate.yaml
      - blueprints/nextcloud.yaml
      - blueprints/jellyfin.yaml
      - blueprints/immich.yaml
      - blueprints/mailcow.yaml
      - blueprints/matrix.yaml
      - blueprints/paperless.yaml
generatorOptions:
  disableNameSuffixHash: true
