---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: authentik-postgres-backup
  namespace: security
spec:
  schedule: "0 0 2 * * *"
  backupOwnerReference: self
  cluster:
    name: authentik-postgres
  method: barmanObjectStore
