apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:X6835XzuX4X5KJxmiCzZHU4nyvRh+0XJpkcyjvOmRLX1yWbkY9fhNWz98rdVXTu7ISxewsRl152s5K00Rxr+ze0KqkcbJCcSoTv3l4KRKt0h8/272uBp3d+a16Bav28Eb1/LSqfwL4WJMHlqzQtEeHyRbf0t0UyGQu5NHDM48wg=,iv:EdMwN43CaCpUWfuEecSb/5QVkuZ1SNxpkHZFFAp9i1s=,tag:2lgqZQ/4F33osbAEk9QgSw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:/yiXEZAnHSi1hJvLvfC2Fc5hzA+MzT6zM3pLFHMCJ85sRxsbjR4uhk6pEJoFyPmydmmt86xs48cGdXpe8DCeOgfekdsJR+DmaPsV/+LUfiTkE6tUfHQMO1bcyfqHMcIsRZ7TC5F+DQ4fvuZsDWcBYFyjd46NYvE1hhU4Y/axQ7+l5DOuRFG1k4V37Y858+ELno3MWOjol+y82SokyxidsILN0AbbkcTmhqYzcCFHFr3AsRKquhF7As70Pz7gnI2BfTat+QIpX7IeTz5/+9qQFOOyO1wU7ioF6EbrXA==,iv:Psb5DkKminv9aBlQSai+Gs/RRXU157NkeBCN8d78+Y8=,tag:KggbpFq3Rz6zmFN9IR7waw==,type:str]
    #ENC[AES256_GCM,data:g2uD8uyrYampRrnzecw=,iv:EoNhwIV04HoNrRF7lQAaExbhHxakME2YULs2WdHnj3Y=,tag:MwrMI83nJXx6g9TPHE4b8A==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:MuTP9OY66TeZBKw=,iv:Ge4aaGmMB+X/korbyCRI/4YZ/1rHvBBaNGpfop2q/4g=,tag:K1iKzalycLByxcTzRnBoGA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:tKRKLnQdhS62Yz+KUu6xuwo1ccEC9wBAliUjzAAO6PzCItE4k3hm5Q==,iv:iK8JbnBFmhLB0KP3PsuQJZ4kNtz0uGVpTMPl+Y/+7lA=,tag:VAhsztkctcoeuz92EUk3aQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:r3pHZ8mq8JJ3lzTGsKO1s1UoqQ==,iv:6fqb5O+TknrMELv/gaUCQqi/s7Dxi5fZCdz3KIwvjuk=,tag:rQJtXlCepN9cwqKJxoQT4A==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:YcDLgwTy4keHBuet2jaNwcANBZ4AALPMeXDiqCFPWbc4w/VmZDcYTgP/8Z/HfuWKhC+FAIgB3PYIPJaPz16l+KbfM6Txs7DZah/UVM8akQUrfQ13sTd+4/jkZ6mGtT4rUvWvqpYrVyEf5eJnREHV4rtgCn4F/3LArzYtnkYhlZA=,iv:+XtFD5EiUu6bDcNUSlfFl+N6sUOcX7rFc+XNsFDMEa4=,tag:Js/TT0I8j/eW60qTOvneNA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:TOP9MsgaG5X3yzoD/u2bSFg1xtTLxHbjWW+5kC21wzdovo7lkH1h2XKABrfMsPfEUzLTlWSVU/beq2J4Q6RrnUZyRkMxOVScq4HNqk0Q7eOBP5iKZlczj+RvpPQAxwVz1J+Acb/1Onwe5DhMNyT/ZaxNHA2btJZWC/+s+xCqKwE=,iv:dWpYPIJVKLlXO373E1D+0hOosNY9y8DEfIUyvRqORDo=,tag:QvlJM3gIoaOA7iM09bt/ww==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNb20wZGxBNVhEOTJ4L0Ja
            N2F4S2U5R2JkRnBEb0VSeEMrQlJEMVlFQVFRCkwwbXlmYS81a3p4blB1MzBNZ28r
            WGlGVVVnRmxuWC81SndLY1JCK0FQSncKLS0tICtXeGVkWTBUTUlMWUxVd0hsczds
            QTlraUZPdVFteXdWNTQ3YklGK2NxTVUKK5C8+Wj2x2nzMfVrPf7DEn4HPcX44N4o
            Missx0cFnMX4U+ALN38FVmjbo4kVVSQo3ZdoCHuJ1cYOiWs9BzYOoQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-11T11:29:41Z"
    mac: ENC[AES256_GCM,data:iIx4NZAeVzTsWjJtwL7srC6goUhLPFB/6xivbFZVDHbFWwuYDzm25QdwvBEEuTGFC6JfCwi01PwnXOzTZE7Z7q95+PDW32Jby6oJodnCbeZ56UC+O7TNQvgLeFyXhnBVmrkZjQ6dC9s2VxFHoqT93SrxoaDoUb4ESm5omEilyPw=,iv:NsSQIv6DnJZQAY50b9ZLrnBl8GtOLwpPw3U9BqtWB9k=,tag:+xEs1eYg85ZWUdXpcTY8Bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
