apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:fkHSAQ9ObayPd3O6U6IdKi/v/IofDBY/RrLQoNpbDnFX86FnvOcICY2myllyRhXfACFJnATOD4uDEaqi95yevg==,iv:tjwRIb+9iwuG347Jn2ejXTrw7TMXAaCwfROTdZE5n6k=,tag:ndv5yDWr54o9tEfunpZJuw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUE1sd3FDc0ttN2h0Y3I5
            U1JxZ29vK0YzS2N3d0dKZHBnQ1dXNHJDaGhZCldoZlYySlQ0bElJQ0ZoVUlVaGJW
            ZklYVHV6cko1WEpxNkR4enY1N0pIMXcKLS0tIGV4RDhhR0lONmVadmdEeXQ1a2xQ
            Z3BRdHJPZ0MvRWtINmFEdWJhOWlxZTgKkEe7LXMZK9fqpTXd6diJZAuUvrw2gO3Y
            u+U9rjgtJtKK53OB8mjX4+k37nZUXgP5q8upbgQLX0t8vCppXFYTPQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-11T02:45:50Z"
    mac: ENC[AES256_GCM,data:T8xeUvCbqDNF1pXdFxGlncQ69HumYuS+Sks6b0hjy1VkI/grZ7yydnEHbZXH+awzeZdHdxMmE2OKhwe1xMZChaa0xi2PjOUBSIctKH8gmORQjWLGd8YYG3KW1jZ73cc0VxmHUfdTkeQcTx5ixxgUvL0VFfDlDp5j9aeUaGEGrZ8=,iv:U9BTE2r6272FyY8GK5gq5/3c1T0m9PcPEC/QRsUxBU4=,tag:bQNXSJANyZSYaFLn/ybb3A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
