apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: matrix-cluster
  namespace: comms
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  primaryUpdateStrategy: unsupervised
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - k8s-2
            - k8s-6
            - k8s-7
            - k8s-9
  storage:
    size: 200Gi
    storageClass: openebs-hostpath
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg/matrix-cluster
      endpointURL: http://10.0.60.15:30188
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-secret
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: matrix-synapse
  namespace: comms
spec:
  name: matrix-synapse
  owner: app
  cluster:
    name: matrix-cluster
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: matrix-auth
  namespace: comms
spec:
  name: matrix-auth
  owner: app
  cluster:
    name: matrix-cluster
