---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: matrix
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: oidc-config
  data:
    - secretKey: oidc.yaml
      remoteRef:
        key: /matrix/oidc
        decodingStrategy: Base64
