apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:mjvY24vkmYP93YI=,iv:CUoI+F1BFKofqc9Zm2OWGgvw1jA+JGlJiJpi8eh6qME=,tag:/yKQp3Cq3h6FI3W/AeZDhw==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:QqIxAeZ+TtYod9V9BNo=,iv:Hx9Aedg6O1u1+rR3IFR8xxUIRmjwpJSjO8lr2cjRsE4=,tag:g3HS0+DJ7wzjSs7HQXjHaQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:ztlAYKDk2jdYAyoK8JpvtdHAGUMZq6L6/i+VrTkIkO7wjWrpLVTMt/WzGiyWB6tZZ52gmOh1j2lD1f8JYUHEDQxlNlInRPtnw+9puGPZL75Rh9IxYd8JGtJrpGfLNgwKvmU+eTz1SYCd63WYeojtkdfXuUIyQDIcKhw8bTlErTnGJIi+p4VIBo2mv5nbgRCdwCtuiq48JdKwb/XmhdnCOknKZ6q3I8vuEqDMtsB2dAkCHpOhpqTLn7MMJMLqbOpsK9DKQWEPXwEBXEAFCxFsNsTrGEgVBg==,iv:J7kGLQ7tZJQnUeAOpzjNZsg3/A+72VPdtMJot4bmEnA=,tag:PtrB3Yi/n9LH7l9MJqAmew==,type:str]
    #ENC[AES256_GCM,data:seiPmWfNd0R9mxXrr+w=,iv:19sPMeU8XOwEPX1xPXSLAglfGMDRMBzgisSVhDsrWrk=,tag:qUUNy/42pnEJBheJfQNdzA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:9vNGgj/FbLM=,iv:RBiwZWP+n7F38IgDscVfRj6m2TO/M8dG8TixsobzmNE=,tag:DccKnyQzyg3mg0omT4cirw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:db39BKgywBVVntQovvoT4bXvFcL6cyQPcQILm5YZmc1d2FLfdqlBFg==,iv:Cyo7VCpIErtwxI3COwX5RwklnwWAYMljiOZT7VNxR2E=,tag:0V0tx7gFzyNMaV9R+nyWqQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:yBFf3Jzt/EHxwbvMoF93Ew==,iv:leS/ppMZI30Brw49zqrHggEkGBJpluLJPadrb9GeqGw=,tag:2MiIBQKU+s+vJjU2Q/sx0g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Frwm/X6DVdQcHFeoSnil4zKLiiGocIDT5XpYZ4wKmygH//bUvnqKp24vBt67XY/kdbT4SuXr3bz6ZX85dPb9hJalkrYC6qtTOD3a2TGQFfx66qvrZzdCmiXONL8gUIjwl+xZUGXGQ3FG5Z+B+wFwbfNDkSXQz+YBbYL6Bk1mFXk=,iv:RMBSZdoSVYojjuGH4uPX2QCWs333sWnrgpMdq/26v4g=,tag:NcrEyVgkTZ7gBAUVubhN3Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:f4WmyUX4mdKBrs4omWqhbd6eKRah6wibfW7Cr9XUbE1cvBJRb+9aL6hOJNUsZhPuInvR79IFrdeUfUt6sCVlmi1sx40IGfZCpgD+LDGe+OP5tp0lZOKNs7KH6lGiH4Jk2ZVt2mT0zYuIcqEpvKXubfmCPCDCFqU3HgpvRVRRR+U=,iv:+zMNQA4qeti7YQ8eih/aOXFsqN9LV+J6gg05x3juB5k=,tag:7lk2Fdb5GeCg5op1fOXJ1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArUXNZZVVoUmhZdW1oZHBT
            MFdSd1Z5dmo4VGZtTVNyNDZoSmNzUHdBZzNvClFEN2hYTUMrNHZzaXJ1UEp3SFky
            elBoUjRVRFByM2wzUFlQelZ1b1kwb00KLS0tIFlzZjJHUXlXNGxrbE9xVWVSZWln
            L3RTOGhILzd6MWY0bzNzcjhwZVpRQ2cKRyqg3Ou0cGbh5AJ+AinvRNGLMGAVk7LG
            N6rA8dC8lv28d+/bcgNBtfBEFeiYfIHRA5xEqjF4D36OAJnEpjGnBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T06:17:47Z"
    mac: ENC[AES256_GCM,data:MJ64umlu6acapgVrYj5V9II86tAF8pyvfnojYeUvZbFAharzfHaeySjn8ucZgZZOcSz94DXrpgHwUv8DcKUkORlXcEKeEjGKvDMMnmDbjJ4E9A4jKJdKJcLxFm0rIJVVLFEd1Sorxihy5nWaqcu9HndUMc/IwlFzpkX7SWoTrkk=,iv:180/5ETD3CQLzKhkOv+Kihid1ev0QWud3UMKMQ9s78A=,tag:eObqy1yj7kS7eZX9atDkLQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
