apiVersion: v1
kind: Secret
metadata:
    name: miniflux-secret
stringData:
    ADMIN_USERNAME: ENC[AES256_GCM,data:deBvGp4MpYxJsN8=,iv:cMGwu6GN6yqfEJ4LCZTw8WcbCQlJDHEwWv6P2behqt0=,tag:vTD6FSrmjvS360mImvmVRA==,type:str]
    ADMIN_PASSWORD: ENC[AES256_GCM,data:ksOxvqH6lYk6vffXBOc=,iv:jsbYiBYU5jhs7EDmlm2WwqPEYb98Z5pU2zvG2zDJgDo=,tag:zPbsICqVL2zB0RgWqNbteQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:+qCz4789WrgpTSqBxkSVtIigVDnl3nGziSmNZUn2WRXFozi4TtiqouZ9YuCj5TZwuDHWtu97eqQpKVG8yhzW7INnMk/yrISfz4XnWo+OWyG7rQjQOhyUuS/QZcO8MpF4NELcikjbO1A8O+84LlkG888rO/i++MCSGPbdiX56NoGX2F/7Yd7BPLmPj9/n+rs2UjKlf/fdO0JtYtrVlltZEaM52VTVCtZbuG6gVx0DmSKhVPr5/SZ0VJ4WY7GApdpL28LgRLY0sKirhumnhnlZHVu2k2uyhw==,iv:QSzRr8NL2dR5+A0BfHgmGQ6iFqfA5+3lptH3uAyLAmQ=,tag:xejPQaghcbZ10FS8aa0NsQ==,type:str]
    #ENC[AES256_GCM,data:BNTP7dZZEEfxepkKB5E=,iv:wn1Q3vnPF8MEQMnLgvIJ2ow+w4bbINVvG94FhpYyqRc=,tag:WzqAsS67KeN8x9qOhW77rA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:2FSI2gaifZo=,iv:0HQ/PYOcHtIFuzt1BItc7HZoaC+lRx4k1qQan5v6YDE=,tag:85HuBz+Y47T6WswVIjX/jA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:4brHnctow0WM5iOacZfDCbJqtDqtLjfwWMtZ7UT6jwxw1klkdW3a9A==,iv:gwM5LT6oVaRT1X0o3wlnM4FSf4+4i8Zr3mcdP9oMwRU=,tag:cw3Zg4MeCGMz6QyCUCUb+w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:AZngDJpfQFJx7J1sJAfbYg==,iv:2igeCJ9cLnQuBcypHRV+blQj9zCCEx3ucWuWAWXBec8=,tag:Juec/k05frQO/p4VJBq34g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:TXrOi1a1IXx/5+SPG6YjZzN/uwGoMcGKgNQe2nAtHpx+qHVNfSD+vq8L1YnTNtwOic+q38Qr9iD152TcE+M+WeZtUCBrlkV47eoSYtTVLDgct4ZFt8Vb0OxlPC9c5Ma8M7VOTdzKL8Ti2bqqJPqDIziLuBj2i/eMEHc/pCWmEkw=,iv:5H3nderhMGTLqNMZT1lGgAw2dycKBg4bZkZ1Suvxbvg=,tag:E6czU9fP7hPBwSdxfct1Fw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:3VpZCZ3AUOUxprzeLX+qEJMI6AB7I7Tok8nHynqQZPYnIrR4ijgB8s6iIbb6k8WatfCH8vHCvvy9mee7v61QASrL5FCuMtmZAvK/zwQzNFobTgmZ3fHB6iq7a2vRJWqFL1hsH+sdsONxIhw+4NqbydQgSPmTlrMZ2O+/GNo/Q48=,iv:V7QzqITyhBj0aWJD1czwDQvf60uEjMd5miCZQyrLeno=,tag:8maz0G1u/8ef27Zu4RhVCg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3ZDBaN3NpTXhGR3Y3R0Rh
            U1A4WEN4WHhrbzVERHNIb1pjeHZvN29MbmpNCm15cFdvVk5ncUN2bjhwVmJMQ1FP
            MXpabEpIT1B2Zys0anAzbnpJM2s4aW8KLS0tICtsdXdEYitpaVFYS1Y4QnppbEhP
            UWhvNE5yY2p1bFJEU3J5V0QrSWJ5RlEKdOzZWRaqubaSjm1zCbsubO4D+dRLo8dg
            vM/PALKW4JgGAjyDY5DC0dQaC0YwsMqVY0hZJVgz2H5JycsEFu1kAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T05:46:10Z"
    mac: ENC[AES256_GCM,data:9HjM93fVPKxRj6WDTvzoe77bFRd77x3m0UdyPT4LeK0MQgrUrbQrq5KZkWrhuluupO66iQYdwlhimNgGnASuaK/JrcgjhGYaEpXfEskZthVZAke5abAWYOg3oBvjOUBWJA0VAC43Hyn/G5zV9ZJkDsUhjKOVe4tbtD86EEEnIlo=,iv:pZtnA2zFjLp8nPdemoFN07tx01A4AmYyi2ZLZ/8Fn3s=,tag:JOsNw6nDm/szoUFRDQBqaQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
