---
# No yaml-language-server schema available: stakater/Reloader (no values.schema.json)
fullnameOverride: reloader
reloader:
  readOnlyRootFileSystem: true
  podMonitor:
    enabled: true
    namespace: "{{ .Release.Namespace }}"
