apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    discord-webhook-url: ENC[AES256_GCM,data:Y636WUJBXKWo1PI2m+tBPn/teINqzMcflXLEpc07/5OZnYtfw8kkr2x5ErJBAbBtI9OV16fablFCkLCu+8YF2U6wOObNMIpPwA6jEaVA/pmuL0fNtCd6x02s7BWxjQNpCcoGfSiEEKqRSwjSrbCulb3KaXpRtX27XQ==,iv:NaCgiY6OMP8qWrkSzDOTn8wViRC3fsmIwL4IGCr9MdM=,tag:scWvseZbjI3zj7VfH2kYpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUNjJOcGwzRG9oY3dPYlAv
            ZTlmSEw0UGVPNjFiMDY1cHU0M2RuWnA0d1RBCkVFNVdQR1NqZWpoSEQ1T3FtR25X
            Z2s0T01BNmZGYjhkM3dEN0I4UnlRZUUKLS0tIHQxdnBvN2VTbW5XZzhheGMyTzUr
            c2JFN0llanZ3ajFZaGNMcjJSMzZxZ1kKA2qAsA7xirddY5h7lNLueH/1gIPUxUvW
            kDW+W53yAjl04FGo7AJG6bxwwe0azzliO9/l0CU7+iS8vjjzwYnjNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T06:45:48Z"
    mac: ENC[AES256_GCM,data:EKNiaZJhF2NkPLQNV2ZsXh9tK3ZXX3E668ww/FQ48AZQOsYXeszfAVDihIBqslJq/4nGZtzYMEzAbnqbQCVEFyWLG83rfompnWkKBYHwjyLj82sYNe+aDzx8iqpBQ1nGOejDywa6ZhgkpSKbTSgwUNVs11GpKlmtFRCxKR1xyh0=,iv:0Ymamu2mKm9i6uOTIwOGf/j3aLjv7hunBq58EQ9kQaY=,tag:clLR4gkKkQ03MtGTW8823w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
