apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
stringData:
    discord-webhook-url: ENC[AES256_GCM,data:NtzUS8TfNHON1IDuvdl6v5o8N1Lf/o2OnH/aPaLIw/80T8gpkPZ/HvVCoEXku7Asap33ohdKUs/IN3QBpXoepTqofHeth2exeqst0Oq7v9kHrGe1TEM5SzfW47tZqpdY1eHyysEZtzYdEKvm5bHPRa0pr/rkFKGiEw==,iv:3Xj0WpEEU5Zg5WbeWIeFZeX3NXGFqhaBQHPwKdjBlr8=,tag:nqrMZdsC+3rafFyxoq9FoQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RnVkbTg4V2ZzM1YrTjU2
            WEcxckFzSTRwMUFWQ1kvY2ViZnVSZGtHc1hRClVjSWVrK1RhM3A1cHIvaEFCSGlL
            K1R3b01JNFVna1QvdVYrbzdPNUNZTmcKLS0tIDRONmhhNlVxNU93aTR6cGlHQkNQ
            R2lvTy92dnFSSWFlVmNMT2tSbXdXMVEKEJXawebj3sszlYbnH9PRi3LzNS93eWE7
            O6GgMw0ZAl0+hEDZt4OX4gxFIf3rfka/3fHST+7w+4hpNTsatutXWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-25T23:00:40Z"
    mac: ENC[AES256_GCM,data:t8AzydgeRUXU9sSXFho4M3qEYaNGawvHWbfjz0o0cw+c1O5JcBuc1XrNTb3QbqywOioylpxgf+EnNIezP3bWNvgRHJrgaqbX9DUk3aQvzOMbS/TAPoxGQWG+Jzbm75UU5TGuEzGSKhzELI5eCZAQPeQ0v5/omQJaDqL60ybsNao=,iv:XehVtOdpxII26WzD14wx3XuYylnnFE2ZV6h2FSBtGO0=,tag:X7mng1y4VfFzzDyifiUZiw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
