apiVersion: v1
kind: Secret
metadata:
  name: redbot-secret
stringData:
  TOKEN: ENC[AES256_GCM,data:UEMiy3C9GTWmx5vD/9rJ7ZChflK4efNvF/18u/soIAwMp/sDIAghyoItH0Ub+H/vABtLD1ZVNgawSFmShCz5pFCQVhSVgA==,iv:sIjMqlxT6VfSM/DT0m4dB3QXv56vjX+3hpkcLrXim6I=,tag:BGarxx5Ir3N6gCYG4SG3JQ==,type:str]
sops:
  age:
    - recipient: age1pk4hw4gdplvq3tz6ma96hx3ja4w303ld5n5x82yqzyhj4g45qadqq9nf4n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2Qk5uSFgzQ3QyMUlXbXpq
        R0pJQ052bHBtWWZLbTFRS0lYZ252RU9yTHl3Ci9SdmE0Ym5PaHNHMjJBUDVSbVVv
        dEZUV2tUT2VqTHB6eGNFZzhsOThXaDAKLS0tIGUyT1VPUWVOYW9BQko3b2pRbWsw
        NjZEdGhwMGo1eWQzNVJqWEFoYmtKT0kKMxToes/YGth3YqMAtBmC/0s5b2MdNsl9
        gfKApnVcJ1NgQyWqIC/1o3gG/m87lsq92lidQKJ48OvM93QCjsNklg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-30T13:33:28Z"
  mac: ENC[AES256_GCM,data:MVBpbsadfArcScbPxErLeDucKkl6ukQssaMR9AgsV8FrU8jtv+eqfZ/H0nHWkYya3i+uokpFRPgbJBlYCB6galOu5zWsLvCxWKRVepFqPNGMvItKCe5lCwsmL549nf3vrtfcxEFVHH9M2eBG0sJQ5pgN03Mcc0286BXkNwUkzLE=,iv:o1890wMG6SUQ3jZ5t+cQYTp+Qv6G238r9i2FfIf+AOo=,tag:wCakYrfC5ZMPkDPjhtH97Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
