apiVersion: v1
kind: Secret
metadata:
    name: redbot-secret
stringData:
    TOKEN: ENC[AES256_GCM,data:o2QU4RbZLvXxDDq+A3KxToJpsBaMeHwEiih8Dwe1Tq6wfTGhlU1ASQM4zU5AkJ8qLvhhQV9gXOvGIkN8jFIwumqZ61uLGg==,iv:097VmWsuctszdSjMG+k44E4fbjcx5x0tlcAhne92N7w=,tag:pyqDggY4XUadZuxu7Kc+3Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNYUlXMkh0RnBTRHZkZTRF
            NDNhcmR1Sk02dk1SVmxycENEN2MyRFZiVmk4CmErTVBqM0hYRkc2eW5Kbk5yVzlE
            UEZZWHZMcGl5eHdiUUNGemxZT0JiRlUKLS0tIHNqMkZXbHB2c1JVY05aQzkzSk16
            ZFhRNGFDbzMvWFVMK1hxZjhyVmxYdFkKGgn5NJpxlpzvms7ipeCEqnVEqSYema5m
            Z8pjV/T49i8N41VeVPzgmN0pYW22K9ZAxC4hd8ePn3UfspWHHGEm5g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:04:59Z"
    mac: ENC[AES256_GCM,data:GMe6K7N41RgWsTUvyChMoW5rvqKO6GWO3XZfcC9amhCVsEnN3yLC1ok7bIiy8ffragVPuXE4L97BYF/kW9WeSk/OPvM9MFHqa3F5GCvDuw9pP0eGj13PCPlaRNkiIV1CAm+BarRL1UXcWTVFeOIMwxN+ki3aN+7bv5bm31NrppA=,iv:yYiwxvTWM9/ceULFsIVs1UWIj7uOBjJOoi2r07p5BtI=,tag:vi3vRPeFW09u0rmjztTllQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
