apiVersion: v1
kind: Secret
metadata:
    name: redbot-secret
stringData:
    TOKEN: ENC[AES256_GCM,data:oR/Lmdbmy9/Y/ex8SzwgYQTJrEWXz+Wvc63UX21mjeAjLJY8mQF8pNGHTmt73VfADqlAyMj0cjvAFlK0ppjfGh0sIpt5sw==,iv:dbKi1S22xLPRW8O+fhrSqYwb4VsdTKmZ8yXa3KD/ENs=,tag:s0Yj54Y7kgTfSqvzVDFMFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQ0hyUU9JVEh4dFByMnZy
            YnZuL0F3RVh0TE9ETldiMkZWQWRRZGhrSEhjCk8rQ1VTRGhnNkcxSC9ZMjR1RGFS
            RkZNVVVwRzc3U3ZKaitYakpsbFNNMGMKLS0tIENQSFllUkNYdFNSanNqemJmQndU
            WUZUdTYxZjNiVHZidUpyNkpXOE80WVkKcRP0EpVW/liXyZFiXfd8t8WTKCQ7uz5j
            DCNbLsqxhOiQN3z5bxiXpVscDZhMdD+TntafP+chHK36orGSCQjFdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T12:33:48Z"
    mac: ENC[AES256_GCM,data:Wx+/8vdYsT1vN/0DS3DxkGvCP2W88ZVoxSySoF7g/lwQ88MgZ/XCGq2SkH5CjU/RpaohLEJ35WWSnEKkrJTPM+hgfTzfZ+nJ3YrY6wxoYMkL07DGCyOVUT2pWoehI0Luv9qjxyB2LUNeHZhV/xZi9a3+iV9l7LJxUhhDDm8bTD8=,iv:UXwmMHK5lQOIs2CYKqTGkUE2Wc4WeyjopbqsE+1CNa0=,tag:buscgwY9y/AGX7Tec3TBSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
