---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ghost
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      ghost:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/library/ghost
              tag: 5.126.1
            env:
              TZ: ${TIMEZONE}
              NODE_ENV: "production"
              url: https://blog.${SECRET_DOMAIN}
              database__client: sqlite3
              database__connection__filename: "/var/lib/ghost/content/data/ghost.db"
              database__useNullAsDefault: true
              database__debug: false
              mail__transport: "SMTP"
              mail__options__host: "smtp-relay.default.svc.cluster.local"
              mail__options__port: "25"
              mail__options__tls__rejectUnauthorized: false
              mail__from: ${NOREPLY_EMAIL}
              privacy__useRpcPing: false
            resources:
              requests:
                memory: 512M
              limits:
                memory: 800M
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      content:
        existingClaim: *app
        globalMounts:
          - path: /var/lib/ghost/content
    service:
      app:
        ports:
          http:
            port: 2368
    route:
      app:
        hostnames: ["blog.${SECRET_DOMAIN}"]
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
