---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dmarc-report-viewer
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: dmarc-report-viewer-secret
  data:
  - secretKey: IMAP_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /dmarc-report-viewer/imap-password
  - secretKey: HTTP_SERVER_USER
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /dmarc-report-viewer/http-user
  - secretKey: HTTP_SERVER_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /dmarc-report-viewer/http-password
