# No yaml-language-server schema available: rook/rook-ceph (no values.schema.json)
csi:
  serviceMonitor:
    enabled: true
image:
  repository: ghcr.io/rook/ceph
monitoring:
  enabled: true
resources:
  requests:
    memory: 128Mi # unchangable
    cpu: 100m # unchangable
  limits: {}
