apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-minio-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:YBu2abDFJ7T+5I02h6gfYgj46KhX9hHivqEN9IFA19Wo85TiavvWvX53MRhxzBBR0LutNHo=,iv:gMOyZ9xO3cz/w73mLKVjNw265adlMdiq0QWULNaTJ88=,tag:P4b8+S6vF+2MG6AK/gQhCw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:BpiO9LKg3JX8Adce5nhvlUP3XIVrqyg5BmEorU5ayVpyw4rhJCeb9eeRj8U30eejWDOk1ia3DCGeYN3A9s7pitv9WDSVgl+fXtBBTyeOBp73YnPyQXziVMUUtOdp3oC6MbLAFxBzuxLmQEvGJEfPe9vg8k3IlvbrroxWCnAkENI=,iv:Er0Yj1yksvzKZCt+OoijEu6mH8h6iDlEQSJyHE1UlkM=,tag:evCBNdFKGD9XewmQAna3Gw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:U3iqtVZILhi/,iv:hDHii30rFvnM6+XNs/qklv9jItQy8HHehhr+l3JVbJY=,tag:R1lJyPKPE0s3tpMhWHQ8UA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:90B/BItv6fzeXxi7oHRq2sZqPqWEhocH2b/b6raZkcQ=,iv:gW7ti98RGRooCegRmD6/xsAhCF9hmdrdvNF4JZuZ8Gg=,tag:6ncgusWi5Vk1kfJ+MWVFGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFenk2LzgyOE0xVjBkMU1H
            a21vbDdFMHM5b3daRVNBam9jQW4zUkh1TVM0CndPV09uUUxOblU2d1lZbExIRWN4
            b3FZREl4TE1WYlhtVFBnMHA3anVOZVEKLS0tIGRKcXRERno3ZjhqS3Yyd0lwdjEv
            MlhySmxPajFFYU93WFArWHFKc1AyQU0K5jELAchl/hyP8yKslErrVfqkgtu+YKWh
            hC/G5yDq2UrXzzl6TZYSjLAX6/HPOZwtGp+fyxormeZjimi+wsi3HA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-10T12:50:20Z"
    mac: ENC[AES256_GCM,data:Op89278IlVdrYcJ2x8K19XdQXcxWuyLy7rrcQOOvcJ3+3UphRV5ToR3kOrczWx0VV9+ul4vC4ntu0NRfqVh1QFR/9pQBMSmoB9UNvTejWEwYAYj8DDg5BOZz28RigIo6URNQg2g/nojv4tM/2Pzvgbfime1V8clVdDYWzmL0+Xo=,iv:pEJ0HJDm1IBi0Hx1syBPQNIa5gx8/0d2VY5Lswqd36w=,tag:IuCyJnLCCvQla2rlvOTHjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
