apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-minio-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:CIkRd/pdoCg4tvYa0nE+ghcN9Nl5koIGQCvMhPVvndkmcyDqQJ9NkM8wOjdmD8bkI+mNncLGpC1YquL3,iv:jYnomdVYpEkBwys17IdCmmEWg/44p4QY0guubystr54=,tag:6hJafrydxS7WA0J6XVO6lw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:seNUdPrCHNP0P/TI2recLv8SQg7eU7rhgKUW2wpqQoD2SFKb68ioXBRReUvw0mB8PC7o1Zhwb/OZcTY//0f3NpJx6Ir7DsC0nXjrNqkKX/SwY++C6nIT5PsT/0u3aPBiLZwOEMWuQwNyswOo50JWNx88NdkH7Sg1RRUbFIURGTE=,iv:GjTExpZmWWGrEPNYT57W4GhYGQtp/xPUQgeTHPGrKeY=,tag:oa+lcTrmm9EKaB+CrDiliw==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:Dxzr1ujt3EIX,iv:+4OaQfdk5BafL4SnLaUtRQmgoDbJvCSgfTW2V/wIcD8=,tag:Gr4iAWv/SMdA1QidetR2pQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:6z5GvtPrcFt85P/cawlQMckIAtxlwRirOKNGXUBVhZQ=,iv:Lac2VpG5pQP+/oEZ2xhfT0XIG41tAbyFmXprj9ceJM4=,tag:z88OjObinFhGeVahA1jxYQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBWTkva1FCYVdhMXp2WmlX
            aENjcGQ2L0NGdTQvVzBwUU5mKzVLanZmYVNzClBURUhzNVFWWnJPcitYWFhCTlFQ
            eW9iS21ydXBialZwbUZocjlGMk5oM0kKLS0tIElPOW9SV2NWS2hHeTREc2V3YlpE
            RFZTUVJpbUVWZld3Z1NOTFRrTjJRdXMKycrhgeX0Rdl4md1tLpOnG1RVednSXBnf
            6SV++kiZE1x9eYiynNN3HuWrrcF+gQd46Kn5+XL8nBrhQWNhLJ94cA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T05:17:50Z"
    mac: ENC[AES256_GCM,data:C2u8SfeKIRdmHWIEuTpA3yVvlv+6x4yd9V5uWDyLtkjYuMNWcb0n3EvoKciN0ugLhNffP6rGPytBbmEfCKolQQraYOt+4tTsTAygo89nNvJ6yBBOCkhTXLa/T0G1Bv40cHmXcJ7hPtolgSIZErBUyW4V02mbq7zwi+uMUeEEppo=,iv:GzgiElRpjL959e9IhHj+C0VhZicbRzdFIzXnAbVj064=,tag:pX5iuR9FG5VD8Qh7yqHhtg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
