apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-minio-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:Upe/mnVlVKWLae+OL9uoPrWzJ+eiZUrzVz1VOwXuDAHq7ZbtxK9C3x5YG+pPnyIqyR7fL8qhVsc1IPxW,iv:oOaTWaIaXES/mssR9UY+Qj0ismpBStv6JTUZ+aymuFc=,tag:e6k+BHsHKHtjXbWYR/wnnw==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:VgvfnJz7a4FbJ0Ke3W6Ggv01GrjTM2XzP0wCluCPRJ+0ePduk+JMLEG3IyV7bjtMgodZHzRavLFaTeBYpkYj2ysO5XAQp/RQz2akuQxdqCrw3e4x0bwloC93HNe7D23Ov/I4lsC6Y86zLbr6fyspDyTfLOg+SxJkWR1hxU34whs=,iv:PXl8iPfQCYEnp83pLoXY/KTtrwcPkCbLWGOSRhcHSdY=,tag:axBTlh5tJIZLgLteQvi3EA==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:LoXp//jFaqOP,iv:WxddtnYPYWn+xdxFPmK1Et1SDY28h+9+q+8XIrSqs/E=,tag:ZqdS43d8NtU6QAq+5ESOyA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:cfZx0VWnPdkFzWAww4C41eIE+FpKWkW9CovFC+ig5WI=,iv:26Rhy16KA67G5YWb2k/eBfNZrkCnuZTgOEY2PbHbNrk=,tag:dWzkKj+L0yr07ChDUsZ0nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SkpkRzZ3Y0dEZmdsYmlB
            RFB2bERjWGdwa2lCVXJRYnFpd3IwUTFsWjFrCnZrUmRvb0dTNkgvMlRLdUI5Wksr
            ZThCS2JwOTAyOU1KWGZ1WC83em1GRmsKLS0tIDZCb0FJcDJIVHhSd3JPY3FpRmRO
            Q1VSUXVxYlZKZStqOE9MNmZDQ3NMdjAKDjntGYxmWedBRVhs6Ogr4+wjABTPQqGL
            8bcewi3G0EY1h0Yfgl1aSEDXdKRjfzelk6G7eHjC27l61/Hs/85QQw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-08T23:07:30Z"
    mac: ENC[AES256_GCM,data:gM1SLvxH/VHl/DPP9nNPmWHDaJGvmmjPkE9ppr17cso/pUPy+hbwvstxI7SCoCHANiGvNRWNfd/ZQd6NAAZZ/GvBR6GUW3rFa3/pOAcsKIqEOC9s7ZpDoRNrD/IbTVQErPGZZzyjna7EF1V8BOcWnaO5vEgIn7PGLgUSKgWyJBg=,iv:mqwRajWAlXOhPMtga9gKmBtFJSmQz0adaLec7ADT9xk=,tag:mxsrH8u/FkkhD75ae2EzVQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
