apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync-r2-secret
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:uhGjLTz5NFts0K/zl6sg++CQSvyW7ounBjCszNJsQGKyatACqJF8ILHGwlLPX4YZsAO3zoA=,iv:DB/a5jitZsm3EtXQRjYcJ6Z+3kCDuOuXvn3nPLNZod0=,tag:D1hJ031NfH/PWkLEjBajSw==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:YjO0YTaWou06aLd7mkJD/38tRRuSLsbrz3whEWrZ2vdj94OoNuMCQGfgMAbf1oZVd70ZvzFsMloFRwSuY4hrLSVHihwMZYJ3zTLUW84fmAwmdKK2IfkxRDfWm4dQ8LpancZYa7jOwcPFQGfg3FdvoIxyTzTZREhYi7hnOB23Leo=,iv:cUpQn1Us18Mp4bEtVzzyC63wouhhsfK3QlfpmDGf4e4=,tag:trKuoWwhmv4nXgo8WZ47pw==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:uhHzNy/OREMP,iv:UPusipwbYSHHnRQCn/HvsmBJNJ3NVNMw9uqjp47PYvs=,tag:U0L2B0I1qMu5nFk5ovcj4A==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:367RWIPBq5f6BtI/LNyAVT/pCLOLfjtFPbEBpObtUb8=,iv:PUV3cEjOWmdQyYE7LpJK1sjzOSip6ilpqAOpti9yLbk=,tag:nY6VyWD4mu46EzVD1mZ5Gw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJeUI2UzVmQy9VVGJBcEFs
        QVBTdHBubEpzeVVLQUJNbTNZL3oyMHdFUEc4CkNRL0VCdlUrUkNwMWlkTk9uODJk
        eU8zM2krRTE5TFJHL3dCSkRUeDdINXMKLS0tIFFXcldhczczclpBOVNGTm9rVXlO
        ZnBsVjhhNmlxdFBqcWh3eGxZN0xYRzgKId+RfCYmEaxUWJjc2TXxg6xm9k7vb1gC
        HdKMO19RDHehP0cGerokVY5Jwq2MXovkctKB/gV6XZ0EsTuxO1fbiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-12-07T10:13:38Z"
  mac: ENC[AES256_GCM,data:HSyQflgKokYJKiWNZ/YWih95lK5/mRijCG0ZSSMrOc5oTX+84uPTV5NnSYiGMZMnnmIvnNahH2bz7Aw/iXxq6H5PUBB1HWyq+lMAeAN3hSGJIwJ08A2v2kksp7msHouXrzTTVm90Djzi4C9g1iYk4JQNVnigmga2s1BsslYkPag=,iv:UAMeiXwcQyi8+zJxNWmnLCy6RbCoRFlpJzDuyO7mIHw=,tag:qpd6c/ve44IwU2R7YcoUdw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.1
