apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-rs2-secret
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:iPeRQb/7Yky6E0TayFuIWeDiIpuzDgtJqHT2cjNol55CM+xgx6lS5XV/BzZZVyIigmQZp7k=,iv:jaBIK+rXwFt77/2EMBnlaFIX0bZ+qCfhIeb/83//zbM=,tag:BnmXaUdijTIzXG4y5yG92A==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:m4Vgh2A5EuGfId02wcFcRsCtmxAuHveH7az12q9/nflWRmxagy0YEZo/zIiTn2e4aH8LJhZp2QIxLGpnVY4uy7ErwDmI8wEVps2iM0VC60Y+Aoj1lhdt1dg9xB0HX7nQO9ThHZSv+6W1/aOtBNf5yFfJTfzs0OVyxt97iqIssFA=,iv:7EqqdkqMB8SizxUJ8+hRy/CySlYBMf0XX78hy6hiiXg=,tag:SseINC6Y8cCc+QPGR/7s1Q==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:SOCvujpFzdl3,iv:G9M2u/4RbRMi4sJSruQv5NHTmhH169/Z6bBtp05+Ftg=,tag:aa+mKE6HaTl4oG2JUYuiiQ==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:gR+mkU4SKuUoid6Jd1TJSqz90JffhDh5wgSvgdykT5k=,iv:2b60vJS/E3FlwUbtQCzVamcbmrn8/I2TaNC2aWGToho=,tag:O6xa6Rk9cFd0CO/lvrgBwQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhL0dOUkVJRlRYRGJFbXl3
            OE9hZFFrNE1ldFpKaUVxWHRocjBzQ1I0UEc4CjFVRW1zanpWWEkzd0x4MUNkOXFZ
            VkdFbm41dFI1S2hSR1p4ZWx2NXRnSzgKLS0tIGRaNUV6ZHN1c0RYRHI0NUdnSk4w
            K0VUTE42L2dmTkhYZk1KUlBXalhBWTAKavvcrhdHFpr9MA6oxpfm9lu+R0zp1n9D
            iBTQbLUgDJ42PO/IPXvXI+YOKvL6YM03deHAqnomjlIiZxwc9PS75g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-10T12:50:20Z"
    mac: ENC[AES256_GCM,data:/TE2AYOExv83yqB6bUF5snaOlizqIYj1BGL4qXk46pz+4wxMr6P5tvGgbA2KRTMJNT6Icm4SFIgyZri2OivQG0wVnf2woSdCXAQ1fn+sjax7lZPhSX0k9lDEAiNOXldsNmxL3bsK1ik0tNTxBA1BrujPJn/W7Y+pY2k7GSdkOyw=,iv:ZTHgdn2Q8Zk5STF6aovVguBhZzhwv6SBZbKvuSbv/Fs=,tag:TrgREfhdL1J3mSx52UZ1pg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
