---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: etcd-backup-s3-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: etcd-backup-s3-secret
    template:
      data:
        AWS_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
        AWS_REGION: "garage"
        CUSTOM_S3_ENDPOINT: "http://10.0.60.15:30188"
        USE_PATH_STYLE: "true"
        BUCKET: "etcd-backup"
        AGE_RECIPIENT_PUBLIC_KEY: "{{ .AGE_PUBLIC_KEY }}"
  data:
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /etcd-backup/s3-access-key-id
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /etcd-backup/s3-secret-access-key
    - secretKey: AGE_PUBLIC_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /etcd-backup/age-public-key
