# No yaml-language-server schema available: envoyproxy/gateway-helm (no values.schema.json)
global:
  imageRegistry: mirror.gcr.io
config:
  envoyGateway:
    extensionApis:
      enableEnvoyPatchPolicy: true
    provider:
      type: Kubernetes
      kubernetes:
        deploy:
          type: GatewayNamespace
