---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: phoenix
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: phoenix-secret
  data:
  - secretKey: PHOENIX_SECRET
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /phoenix/secret
  - secretKey: PHOENIX_ADMIN_SECRET
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /phoenix/admin-secret
  - secretKey: PHOENIX_OAUTH2_AUTHENTIK_CLIENT_SECRET
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /phoenix/oauth2-client-secret
