---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Darkflame72/home-ops.git"
      path: apps/games/minecraft
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/itzg/minecraft-server-charts
      chart: minecraft
      targetRevision: 5.1.1
      helm:
        releaseName: minecraft
        valueFiles:
          - $repo/apps/games/minecraft/values.yaml
  destination:
    name: in-cluster
    namespace: games
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
