---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: minecraft-server
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.26.4
  url: oci://ghcr.io/itzg/minecraft-server-charts/minecraft
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: minecraft-server
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    fullnameOverride: *app
    deploymentAnnotations:
      reloader.stakater.com/auto: "true"
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: 2025.6.2-java21@sha256:262e2309f7cc6b2ff0ac1458ac52c91e9bc778989543feec6588501f6dad31ef
      pullPolicy: IfNotPresent
    livenessProbe:
      initialDelaySeconds: 120
    serviceAnnotations:
      external-dns.alpha.kubernetes.io/hostname: mc.${SECRET_DOMAIN}
      external-dns.alpha.kubernetes.io/target: mc-router.${SECRET_DOMAIN}
      mc-router.itzg.me/externalServerName: mc.${SECRET_DOMAIN}
    minecraftServer:
      difficulty: "normal"
      eula: "true"
      memory: 6G
      motd: "Testing"
      ops: "Darkflame72"
      overrideServerProperties: true
      spawnProtection: 0
      type: "PAPER"
      vanillaTweaksShareCodes:
        - 5hByeu
      version: "1.21.7"
      viewDistance: 7
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    extraEnv:
      ENABLE_ROLLING_LOGS: "true"
      ENFORCE_WHITELIST: "true"
      OVERRIDE_WHITELIST: "true"
      RCON_CMDS_STARTUP: |-
        gamerule doFireTick false
        gamerule playersSleepingPercentage 0
        scoreboard objectives setdisplay list ts_Deaths
      SIMULATION_DISTANCE: "4"
      SNOOPER_ENABLED: "false"
      SYNC_CHUNK_WRITES: "false"
    envFrom:
      - secretRef:
          name: minecraft-secret
    resources:
      requests:
        cpu: 500m
        memory: &mem 8Gi
      limits:
        memory: *mem
