---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/ocirepository-source-v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: minecraft-server
spec:
  interval: 5m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 4.26.3
  url: oci://ghcr.io/itzg/minecraft-server-charts/minecraft
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: minecraft-server
  values:
    image:
      repository: itzg/minecraft-server
      tag: 2025.6.2
    resources:
      limits:
        memory: 8000Mi
      requests:
        cpu: 1000m
        memory: 4000Mi
    securityContext:
      runAsUser: 568
      fsGroup: 568
    livenessProbe:
      initialDelaySeconds: 0
    readinessProbe:
      initialDelaySeconds: 0
    startupProbe:
      enabled: true
    extraEnv:
      TZ: ${TIMEZONE}
      ENABLE_ROLLING_LOGS: true
      MEMORY: ""
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    serviceAnnotations:
      lbipam.cilium.io/ips: "10.0.60.16"
    minecraftServer:
      eula: true
      version: 1.21.7
      type: PURPUR
      difficulty: normal
      whitelist: "Darkflame72"
      ops: "Darkflame72"
      pvp: true
      motd: Testing
      worldSaveName: World
      viewDistance: 12
      forceReDownload: true
      memory: ""
      jvmXXOpts: "-XX:MaxRAMPercentage=70"
