---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: harbor-postgres
  namespace: default
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:18.1
  primaryUpdateStrategy: unsupervised

  affinity:
    podAntiAffinityType: required
    topologyKey: kubernetes.io/hostname
  storage:
    size: 10Gi
    storageClass: openebs-hostpath
  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 256MB
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"

  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg/harbor-postgres
      endpointURL: http://10.0.60.15:30188
      s3Credentials:
        accessKeyId:
          name: cnpg-backup-secret
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-backup-secret
          key: ACCESS_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
