---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: harbor-admin-secret
    template:
      data:
        HARBOR_ADMIN_PASSWORD: "{{ .adminPassword }}"
        OIDC_CLIENT_ID: "{{ .oidcClientId }}"
        OIDC_CLIENT_SECRET: "{{ .oidcClientSecret }}"
  data:
  - secretKey: adminPassword
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /harbor/admin-password
  - secretKey: oidcClientId
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /harbor/oidc-client-id
  - secretKey: oidcClientSecret
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /harbor/oidc-client-secret
