---
# renovate: datasource=github-releases depName=cert-manager/cert-manager
# yaml-language-server: $schema=https://raw.githubusercontent.com/cert-manager/cert-manager/v1.20.2/deploy/charts/cert-manager/values.schema.json
crds:
  enabled: true
replicaCount: 1
dns01RecursiveNameservers: https://1.1.1.1:443/dns-query,https://1.0.0.1:443/dns-query
dns01RecursiveNameserversOnly: true
prometheus:
  enabled: true
  servicemonitor:
    enabled: true
