---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/clusterexternalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: volsync-s3-secret
spec:
  externalSecretName: volsync-s3-secret
  namespaces:
    - comms
    - default
    - games
    - media
    - observability
    - security
    - volsync-system
  refreshTime: 1h
  externalSecretSpec:
    secretStoreRef:
      kind: ClusterSecretStore
      name: infisical
    target:
      name: volsync-s3-secret
      template:
        data:
          KOPIA_REPOSITORY: "s3://kopia"
          KOPIA_PASSWORD: "{{ .KOPIA_PASSWORD }}"
          AWS_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
          AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
          AWS_REGION: "garage"
          AWS_ENDPOINT_URL: "http://10.0.60.15:30188"
    data:
    - secretKey: KOPIA_PASSWORD
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /volsync/kopia-password
    - secretKey: S3_ACCESS_KEY_ID
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /volsync/s3-access-key-id
    - secretKey: S3_SECRET_ACCESS_KEY
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /volsync/s3-secret-access-key
