---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volsync.io/backup: "true"
  annotations:
    volsync.io/cache-capacity: "10Gi"
  name: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: jellyfin-dst
  resources:
    requests:
      storage: 40Gi
  storageClassName: ceph-block
