---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: falco
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: falco-secret
  data:
  - secretKey: discord-webhook
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /falco/discord-webhook
