apiVersion: v1
kind: Secret
metadata:
    name: jellystat-secret
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:UerHUqlE/kbyN7NQmK9eUuU=,iv:gsef01Ir5oXL+X/OBoLLRhaVv7yfVA04xUrPvOppow8=,tag:vL1qEO72XP27D9jiaCezMA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:wg5ssRiIWgbRuT9JWs30CFJAZMXPkHc2cVAiK+SNddHd1foi5u38DoC+9+iaPepeZNCaWygH89re/8i/LMB9p3EB1xEZZGYyH2H6vfoTwNF3K9SJB+Uq3fftutFJEepacgDN8A5jxCSMxSx4xGzQzjk+rBHFsT9AGfJySADO7TA=,iv:LNdkRL1Wy/zEFdmu4eN0Bn481WQNkhQSgGj3HzM9Bbs=,tag:baFy0N8O6KYkwrczNZhuFw==,type:str]
    POSTGRES_IP: ENC[AES256_GCM,data:P2wRmkSaSGgkCs8CWayJvHsEpRP+WbZggLTHGhDp/uOTWkVSxSTnYg==,iv:ksx0TxEBYmfRuOPB0LUOXexowdQMbk5fvzFhUoCGHl8=,tag:SJs+OlVMBhKPgXwmUIQ6zw==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:2YL2uA==,iv:tznZcknKZTPTeql4nkjYhyRM9Ppot+6yFt+R5HmFn/k=,tag:3++0JPZz1p2wpCU8Lq/TCw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:NGlUDXFakDgf,iv:KrVWf0V1zyzk3ejCrVAJiK7USwvg9EwSGz/sEbFrrAU=,tag:r0EG2AKpMN+Vici2zFyJzw==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:9JNp1H9Wiq9v0meOyIFxe8MtAD4jLSVNSezO+4027h62vWyxXzsm74plDRGg/88AfjXaH2ryVfNALf/Nbm0rekGkkkuov9M8VeNv3LC3Sf6YRw3DP8QoFXAxl2RaYIQhzN+LY4MBS/5C2GPN53XaXlf/89THnRqK9jkqcHGNCi0JNwYTCw5Wm8KVMA5YzUdObfpo7uhBIo+gq86gTmmrhC9QFcqQXFMgmbckVQnqCTbVpGufJgKEWHAa/CWJ8tDwYn/Yan2huod2rQ+nCknW16WKh9TPvT3KSN497VYRfVqA2PivevEKgf7XI3i62oOCnw4F1YCije9pI4m+8aQE6KyZy8h+Ct7da21z+GgRXjbPs+uri7TqTUk3tSkkKbrN59sRjT3R1s5e6ZILoFPz1bMtFMO36uqlHUbsOWYLszyFG7p8jLUJwg+zGiibhXn/LP9XDKWj5gSCHq3ZfKdx+JOc2OvN+2Y+u2O0I5JD6+ktp4EW3PJUG/UVTm/2RAzO1e+LNQE4xfSnuwm3kkS/oK3tqHVIwfbmpEZ+BQ3/KrrFhDpfk+tkCa9I/xZvpI/EOgAKjCfmnF/AMXJS2RMSvUjMNosCE55NPU8uB8cSZKB+nQaLupQGHpC/dQKCzv99f7OdM59rL+tohDeqDhQdmzriWt48FfypHdXk0xRw9X4=,iv:SvY/zvFMq2vmhOmZ13YH87hbYilirOvJ0P0RJqqLn9c=,tag:znXh/ltGyznrXVZDevGPbw==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:j27yKWU64vrx,iv:UtLjjXXApdsi7XtUpQ0evl3VIbfbfDUGIpaxrUX9XDI=,tag:XNirq51jWb4aFN9QDj3SQw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:14KGZunM4dY5AGdHdbWR1DFibgzH6GyIfw5sccWh8SmX1ZgNtlKVjg==,iv:s8icsiH5U3A1hPhMjD4TBYV7Pm644WIiORo4AVbhk88=,tag:BdhQMNy6Z2YObJ2BQObzmA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:v5oPLz8h7JI4I1Qg+bonS8k=,iv:eOvd/RfSUtkLo6CiNRuk0rbQln8Nt1WMW5bVkORVZD0=,tag:9Wpkkm6UmWSbR4aMwVg96g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:jMYiY9WCqFIMBH/p6anwhYhlr24kgQFf4xRk/W1Mi1mrlMuFUI1jh8oLS643piC3L/pMhj3YEqKD9syQMYpmZ6eOpGiJkN2xAAv9nJRR0CsZsfduML3g8To/aauoKMFzYKJAZy+tbbI1cJXFi9pE4rdlX+o3BNr9/DgFdSVNojs=,iv:VpFTR2j4aZnu3gLUxER/rGC/mvnCOcQSAgDr7d9Gk7A=,tag:5v3hIsrBbgfKLdYUG8R2Mw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:wxYBiZVRYoneyBf7uOknNXlxSR+rEmr/wjidtqbFs31QWkeFf9bXBNJyoWW4W5HZaFStgK375i7lUYNHheLQYjK84/jdDMPnJ+ojxoSLN3XluXBO/BLglfMp/wlsfvQ2zL3hjGrVIF760gmchUiWKVDkuWOpaWhJW3rk/kDlIXY=,iv:9wRheEZ/QiqjEM6BfIv6arGdAv7Pqgc3EEd2JyyZp3A=,tag:89yQITgwYhGPt2n+THoGQA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBISlFtRnU0eHZ4YmZyTTdX
            bTZaUC91b0dIZmIrRUdtT0Z2cndYdjQrdENRCkx0NENWbEZvZS9sQ2JPWkJycjdw
            VjdNcWhRZjhvQjhyekMyNUxKQWRNeHcKLS0tIDBJbHltSzZ1eWFrbitLYzFmZkxG
            ZGI4VkJUWlRRUkpPYUpSZnU3MWZMa2sKPKYydwDQ2JHp9RoC2q88reSS66VA8OZY
            FD8rcDIYuU+6EjDDytj2xkQ7RwJ1kQSrecV6/Q03GBqcDyq3wibuUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T06:17:38Z"
    mac: ENC[AES256_GCM,data:YFm9NwkSJzylngPSQsuAX6YwwPRndDVnf+RYNJZhLMyYVdf3u4Cuh1NRm69R0d9QUnwU8YFHj2E9iWfytMDGJXtiTYzBQ2U8M/cHw1SkSfypmTQDscsdSpyRyUTJ7Hfiyxk+SfYP16mIjJ7zFtfCm33tB6olgo79zw1Q1hcI7zA=,iv:9dy9TGvGEP8FuC6y0dMgfFxAMEpAMxzB1iI/1rvfOmM=,tag:AyuuGwZ5e4ydABSY8xtaBg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
