apiVersion: v1
kind: Secret
metadata:
    name: jellystat-secret
stringData:
    POSTGRES_USER: ENC[AES256_GCM,data:ihZBbeR4xiTZwYkvZ8gnYH0=,iv:7eudEhkTPINdDn4V10wRhgNaRjRbG8bBgoL7JEJllx8=,tag:lZIuJnRq2h2ZBnm+FvyU6w==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:LZtQtFWCMztD78hVEs7emuanDV+6GOb+XVRMAsvfaFRm7NYGiTRbTj8VcFDK0YusfcnALfTGqpZBhkaMaNjYUV0SiGJAiiguPWUaSc4Bdx91BpaiG7AXIZzFzjpblkxztOUhygLlKoclczFsKeMYxeDLkXVapOKqvFwMgfr6yIs=,iv:yC8M+k1AhJ8MD7lrbs493RMRgUuMR40NrcGHXnNmYtQ=,tag:qG05AuAFI9ctDoAnU+/JdQ==,type:str]
    POSTGRES_IP: ENC[AES256_GCM,data:6I7PUM5jQbU2b8nTWvY+8UZNLb4XZ35lnRfilaFpXs0h00wh55ACGA==,iv:Ic52RLz/0LREDHdliICdWlSYzS1l8FlfYuVpsvGu6Hc=,tag:KNwQRuBWla48ep83drIUdw==,type:str]
    POSTGRES_PORT: ENC[AES256_GCM,data:Ajtrvw==,iv:M1MCQMCYX0ALacwHeUGPGgtN0pvCUnyoumFtNCHd+RE=,tag:fHZskem80HJAnn/PgD1CGA==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:d2ym93e4TlfF,iv:kojPTboYAqyExxO1Q3tCtu7CS+pNTwFPA+lUK+aJXYI=,tag:CKmgrBzdy49vTJZDOfzWrQ==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:hRnRu6vqGaqsm6bPqFA5L8SqLReb6uenIhL13TeFschperoic02Ts7ZyIRjo/lZJ7Ab1dvwL2gfXKg1yv2n17dHAaDHEXZuHnPRiOZZe1iDw20H5KjVg5HIqM8UlyFO8YHpwsYYIMv6i4bDakrqUzigLdWpqVwsggYkOzThSfn+rEkQMXp6At0/r1Y9tuC43gxDlhuwK1Bko+JJpRYHEyKPGpYaBYphybPXjApCTRbxcqbsNEOY2V3Njsfmhf8OaPj+FzvJAvEGUKMyTlkGxZw0FIdCDUV5MDUOcV24wUk6jd17cnHFqK53CkFv2YQbyFesTzQt3QPbRas4SJzfylx1i5Kyx3C5waUBzysByrOJS2M3wNt+IPbFihQ2nAUTTbiGXtQFTer9IzsCeXhYJn08Y+m10mzjjTKZPd4JKHUwgRZZlFuVtUKgLYI1GfbUmsp2KFWWsxLUkInfHdKPTY+LaSGYBjftYENLUYVZ5cwM/9XHSGxtGl8IFTCO6c7VDBgEbt5Wq/Qe+RH1c5mnu+not6nQFUG7fFhD7g46r6ISILr5LaOlm3XUbVoO9URTU9Ykt2z2oV+RNDah/myiTMXZukeA/8c/lQMDbSOA6RMuAMfIdmsGd/WjUukXYV3paklxl1K8HG6swjwTFFpQ7Tk67Z9c8T6VimDMJf9DXARI=,iv:7EwtuCu9vq2QBe1+J7t2pGjnLcj+QL7VeJbhpb7l9j8=,tag:vt7YO0cry1OP7DGkNNiU5A==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:C812mKOeLMMa,iv:M0ivYfl3dtJLSkgiBGXGgwwPZQ6/DkHSQJ77oOOrtZY=,tag:7il+ox/DgWCxB+bwtNSgZQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:ZjTV5Rh/xN2NwwKIm27KVGdoKinHfDEpPT9BljIFqvuEv7zjdF1x4Q==,iv:Pizi4Cn4xPq2h8XL9aOyYlPb2kyqw/02xl4JMfhz6dw=,tag:ummkmDJpG6ZYoBQaM7Z3/g==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:8aSZdB7uSXqSnNcUWq3TdOc=,iv:ud66QY3SMM+smq1/OodN0O2yGTZATzvEndang5YpdWg=,tag:VAepK6Qh9645hLDstJJU7g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:VRkManlsytz3XGZl2DkDfV8uWbbyomIPme3UrZwqJjMAQ8m2Kuq138AhLwWDE2aP9AqXE1Avty/2ifYf9v1NUpboVZ2GaRFA9uNIjctghypPY2ptVP7jl+TLMWMyF8jL0HKJ4GjOiKt+uVJONQXtyJN3fjCy0GJKbSzpRv6shx0=,iv:vCIrfKoi3Jd2G+O8g475UivYthq34BPnnD9wnMF/H9s=,tag:F8PeHmnnCDtDrc21TL1WaA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:TsR7t4MptYAmRQP5j4uuzd9apot0899HfSFe3XrT7AJEg7kuPKTsQoFGiFtNc8etmWewfmIbFZcEemN8kSiY+6UAMySplJWYtHPEQPvtGlC2I8/pmzeUJiiZ4PPm3QqGS5m6Zam+iPUPkLjTquynXJUbR9OfVrp/nCC86+eh34s=,iv:79R9zDiHnJw5+hOe/uMKLKP9GBH1XjcpEx+PtudhDvc=,tag:HpKON2d0m53gxZQmK8rAkw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1WkNpVVdGVWQraW9CU0sy
            MnZma21vb3pWTFNHeTNCVzEwOXkvUlpWakJRCkdHd3g1RHk5ZHk5czhCdmxnSE1o
            U3Nscjd2UlNJSlJpQ2xJRXdiTUZSbEUKLS0tIGphSnA0T0FIUHQxc3ozZlFIYnY4
            YWlPR3lKVnVFRDBtZGVHVFNUb3J0bUUKIUEf3LeRXThkYOqoD0FIhOs6ISwxgjQV
            B4iA+IwVAv07su9LU9Gbeb2+YhbnWYxoapoLwLQOzybB3S1Q7u2vaw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-11T10:25:37Z"
    mac: ENC[AES256_GCM,data:+XMkQjbLK4EMCXdvyrh+nWjirw7s4XgEqGBmcPOz9o0NqbAX5xaq6aGQ1RC4QEwN6Cnvsh2f9wiohPcq8cSvzxAEwzfWf8dzaTV8sFykRuxdl/iNP525q+JX79tl52a4S0NZMDyvOIwMhCA9TAhT0FLJxchhqhEQn26GXVMxCII=,iv:6UK9VNTLJpaMd6FXfg6OSMWrjvO+obMupbJxiEhy4UA=,tag:Rg/1vRfLmDFZPvDbHD1RAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
