---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.6.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
    - name: volsync
      namespace: volsync-system
  values:
    controllers:
      vaultwarden:
        initContainers:
          01-init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16.6@sha256:a37bbb04a0ea3f15b505c6f97637e7ae89bc66541ae23b8d3848024087980e76
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: vaultwarden-secret
        pod:
          securityContext:
            runAsUser: 568
            runAsGroup: 568
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"
        containers:
          app:
            image:
              repository: vaultwarden/server
              tag: 1.32.7@sha256:7a0aa23c0947be3582898deb5170ea4359493ed9a76af2badf60a7eb45ac36af
            env:
              DATA_FOLDER: "data"
              ICON_CACHE_FOLDER: "data/icon_cache"
              ATTACHMENTS_FOLDER: "data/attachments"
              DOMAIN: "https://vault.${SECRET_DOMAIN}"
              TZ: ${TIMEZONE}
              SIGNUPS_ALLOWED: "false"
              INVITATION_ORG_NAME: ${SECRET_DOMAIN}
              TRASH_AUTO_DELETE_DAYS: "30"
              SMTP_HOST: smtp-relay.default.svc.cluster.local
              SMTP_FROM: ${NOREPLY_EMAIL}
              SMTP_FROM_NAME: Vaultwarden
              SMTP_PORT: 25
              SMTP_SECURITY: off
            envFrom:
              - secretRef:
                  name: vaultwarden-secret
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /alive
                    port: &port 80
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 2Gi
    service:
      app:
        controller: vaultwarden
        ports:
          http:
            port: *port
    ingress:
      app:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hosts:
          - host: &host vault.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
        tls:
          - hosts:
              - *host
            secretName: *host
    persistence:
      data:
        existingClaim: vaultwarden
