apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:yAtyTgKIRGzsP+4fxpWvPPqCV52dMaHPL5A5SSn6whgGORzk7davfWvTuN3rgesvaSsEVubfVVz6jP+pPfeFU+TzT8mcQSIHPRTdQ3mrAxx9/g23SMnk4eeP4px1M4nDXps8ycASxv1tVDxono3is1MJPoPO21ypQVVpq2AMHXA=,iv:cbqhkvbEhohTu/ZlSmhNMQUBo9Oh7nrRB0kFuzOvD2E=,tag:97Z1Gtwju3vOHi4ZiNRbFA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:vNfhHR1BYNCmQ1FR24bznF9Isf6FCHXwenchzau0Gkl5vCTiHLYq56XYivTUpfosmpzbGiI8qezky6Cw4i/X2tW0RjA3bhSG7IWNsasWGEb2kdekahReH8bilncsuI50po5jc5iD9XaRa8bfu9NJbIPQP5nR1mVzmpwabtLVMaJIzx6fOk98iUtr/KbY+xuf3v/z3unyLE3NZgpbU3HqJbbpdULHR8UcgjqdkXztBOZVdan6bMt6/sH0vwgqki/G3JqWPyhnL0AZ5tBFCT8gOYjORPmR1MNtnMTXQw==,iv:n7WjjOUCoTaGGLdj0G8Il80QP3twaMdI9/nrBf8FT2s=,tag:2siYsH/mAfgOLz48IqLcmw==,type:str]
    #ENC[AES256_GCM,data:Ml0S5ob8PNKH3pIu2mw=,iv:CeyPCbDrwi3KNlF8TlICI6gnxuJD/ue4zlJnILhzqYo=,tag:JTPmcNZmBZxEiQyCqf+mqw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:PG/JjMODAE47EOM=,iv:L8KENYHrX3hVpYebNTnhTbXunLOq9d7G57bx1Ddu1IQ=,tag:r/eepo+INCPLpMBoT1LtGQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:8TUNsSNWGihAJ5vBRbDzEEcxs4HgQOq/duSnRCpz9taSj84cKvc1FA==,iv:VkI46m5+Nl7KXcfGZ3le2/bGhRrwuLdewAbeivuFwbA=,tag:QBKyYuP/pbZKOeniyVQHBg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:OiZckGbbPSMUveeDFXDP78jkpQ==,iv:/IhDeJIcqhFV3m1cEFA3JL/iIU/V/9e3CgBJZ4BUzqg=,tag:db8w+ZjPB0qQ8feHvfUZzw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qmW03VJu5tgWEZlNQ+JwNqnJAn+PX0GiST7FSK/t6arZJ1oZJdcUyRZ5xxXfZB0ohrQG39ZosCHAHrflLTgDTBnoOUVRLRF2tBrJjmh7yXPmWR9ZdAy75oeWQ6QxmCB7b09fpzr6+BKEhrk5uxr26l3AC+S4A8fnXst1mAN/oyY=,iv:p1xrhFpef8vmi3a159OFfy9aFGvIRikzmqF81uIhZF4=,tag:7dSW7ljwCLApTu5P+SfMcQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pNkEgwpEW8Hf69IZPooyCgibDQkPSrQvUEZGjYkHrdGyF8NNPW1C9Ov7lqTeUL5kaIUcGGAcG7CMfGRjfWjHQh/yzmaH/6p3QdsCMhul2DreSb9YckoX9ifEgDUQUfOgQZMwy1szYeFpD5Xgrq+gn+OrmVOT04c+zI9dQvMNSqw=,iv:1aTHf9NspyqZHCT06UuMHgzYSvhYjU8dOg9u1Od5de8=,tag:WZvprN0KJZwOP2NgArGHpQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoOVMybi8vMlJPUlFSWHk2
            QjVtVUY3TU9FWldqN284dDBQamJiaEJ4dERRCko4QU9xbUlZZkpjU2dEQTRNZ3pw
            OXM5K1E1NlF5ODdGdnRYL20ySHY4elUKLS0tIFh4RUIwbm9McWczeXZ5NjlucEFI
            eXR5SUl4azNHNTZIdGhvUDhaMkFhTlkK0GmQ+/0UfbxTKcvhz67cvKe8/SsGrwVP
            jBma7V6NVqynda+nsJ8cavAH5sfjjM24Kls09oImgAi39ma298VyYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:04:17Z"
    mac: ENC[AES256_GCM,data:eWsaPYcha3lWe+wcl6kBGBcnTeRAOTk5LAGinAQMpl6VlxbiDAI0DjhEBjcmUOX/PNeK+UDXxcYC/A8sh/R9ckwOeu/hrPWaIPhbgu0WyY/s1ii0yk/Z6n54eL5Llj1JmEbf/k1nZn7ZrE5PhwmSkM6kAVcd/IDTAVa6SEKSdKA=,iv:17wqWtItq6Uc80jZqFGTacOjGMznF98esqJk2zN3C84=,tag:yjy8t3LV4GOdHSGW2AeZCQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
