# No yaml-language-server schema available: kyverno/kyverno (no values.schema.json)
reportsServer:
  enabled: false

grafana:
  enabled: true

admissionController:
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - volsync.backube
          resources:
            - replicationsources
            - replicationdestinations
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - postgresql.cnpg.io
          resources:
            - scheduledbackups
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - postgresql.cnpg.io
          resources:
            - clusters
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - grafana.integreatly.org
          resources:
            - grafanadashboards
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch

backgroundController:
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  rbac:
    clusterRole:
      extraResources:
        - apiGroups:
            - volsync.backube
          resources:
            - replicationsources
            - replicationdestinations
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - postgresql.cnpg.io
          resources:
            - scheduledbackups
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
        - apiGroups:
            - postgresql.cnpg.io
          resources:
            - clusters
          verbs:
            - get
            - list
            - watch
        - apiGroups:
            - grafana.integreatly.org
          resources:
            - grafanadashboards
          verbs:
            - create
            - delete
            - get
            - list
            - patch
            - update
            - watch
