---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  timeout: 15m
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 6.6.3
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      flavor: fpm-alpine
    nginx:
      enabled: true

    nextcloud:
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16
          envFrom:
            - secretRef:
                name: nextcloud-secret

      defaultConfigs:
        imaginary.config.php: true

      extraEnv:
        - name: REDIS_HOST
          value: dragonfly.database.svc.cluster.local
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: PHP_MEMORY_LIMIT
          value: "11G"
        - name: PHP_UPLOAD_LIMIT
          value: "10G"
        - name: PHP_POST_MAX_SIZE
          value: "10G"

      host: cloud.${SECRET_DOMAIN}

      mail:
        enabled: true
        fromAddress: ${NOREPLY_EMAIL}
        domain: ${SECRET_DOMAIN}
        smtp:
          host: smtp-relay.default.svc.cluster.local
          port: 25
          secure: ''

      configs:
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              0 => '127.0.0.1',
              1 => '10.96.0.0/16',
              2 => '10.69.0.0/16',
            ),
            'trusted_domains' => array(
              0 => '127.0.0.1',
              1 => 'cloud.${SECRET_DOMAIN}',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );
        ingress.config.php: |-
          <?php
          $CONFIG = array (
            'overwrite.cli.url' => 'https://cloud.${SECRET_DOMAIN}',
            'overwriteprotocol' => 'https',
          );
        misc.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'NZ',
            'maintenance_window_start' => 2,
          );
        logging.config.php: |-
          <?php
          $CONFIG = array (
            'log_type' => 'file',
            'loglevel' => 0,
            'logdateformat' => 'F d, Y H:i:s'
            );

      datadir: /var/www/data

      phpConfigs:
        custom.ini: |
          memory_limit=512M
          upload_max_filesize=16G
          post_max_size=16G
          max_execution_time=3600
          max_input_time=3600

    deploymentAnnotations:
      reloader.stakater.com/auto: "true"

    internalDatabase:
      enabled: false

    externalDatabase:
      enabled: true
      type: postgresql
      host: postgres16-rw.database.svc.cluster.local:5432
      database: *app
      existingSecret:
        enabled: true
        secretName: nextcloud-secret
        usernameKey: INIT_POSTGRES_USER
        passwordKey: INIT_POSTGRES_PASS

    imaginary:
      enabled: true

    ingress:
      enabled: true
      className: external
      annotations:
        external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        nginx.ingress.kubernetes.io/proxy-body-size: "10G"
        nginx.ingress.kubernetes.io/proxy-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
        nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
        nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
        nginx.ingress.kubernetes.io/fastcgi-read-timeout: "600"
        nginx.ingress.kubernetes.io/fastcgi-send-timeout: "600"
        nginx.ingress.kubernetes.io/fastcgi-connect-timeout: "60"
        nginx.ingress.kubernetes.io/configuration-snippet: |
          rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
          rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location /.well-known/nodeinfo {
            return 301 $scheme://$host/index.php/.well-known/nodeinfo;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:\.|autotest|occ|issue|indie|db_|console) {
            deny all;
          }
          location ~ ^/(?:index|remote|public|cron|core/ajax/update|status|ocs/v[12]|updater/.+|ocs-provider/.+)\.php(?:$|/) {
            fastcgi_split_path_info ^(.+\.php)(/.*)$;
            try_files $fastcgi_script_name =404;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
            fastcgi_param PATH_INFO $fastcgi_path_info;
            fastcgi_param modHeadersAvailable true;
            fastcgi_param front_controller_active true;
            fastcgi_read_timeout 180;
            fastcgi_pass php-handler;
            fastcgi_intercept_errors on;
            fastcgi_request_buffering off;
          }
      path: /
      pathType: Prefix

    persistence:
      # Config storage using volsync template PVC (local)
      enabled: true
      existingClaim: *app

    cronjob:
      enabled: true

    startupProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 20
      timeoutSeconds: 5
      failureThreshold: 30
      successThreshold: 1

    resources:
      requests:
        cpu: 100m
        memory: 500m
      limits:
        cpu: 4
        memory: 5Gi

    strategy:
      type: Recreate
