---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app nextcloud
spec:
  interval: 30m
  chart:
    spec:
      chart: nextcloud
      version: 6.5.1
      sourceRef:
        kind: HelmRepository
        name: nextcloud
        namespace: flux-system
  install:
    timeout: 60m
  upgrade:
    timeout: 60m
  values:
    image:
      flavor: fpm-alpine
    phpClientHttpsFix:
      enabled: true
    nextcloud:
      host: &host cloud.${SECRET_DOMAIN}
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        runAsNonRoot: true
        readOnlyRootFilesystem: false
      extraInitContainers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16.6@sha256:c1d3a845d47fe1aeebd110fefb5f43f54c4735aec1d2b0c01de8d4d5e8cdd6a4
          envFrom:
            - secretRef:
                name: &secret nextcloud-secret
      extraEnv:
        - name: REDIS_HOST
          value: dragonfly.database.svc.cluster.local
        - name: REDIS_DATABASE
          value: "1"
        - name: REDIS_HOST_PORT
          value: "6379"
        - name: OIDC_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: *secret
              key: OIDC_CLIENT_ID
        - name: OIDC_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: *secret
              key: OIDC_CLIENT_SECRET
      mail:
        enabled: true
        fromAddress: ${NOREPLY_EMAIL}
        domain: ${SECRET_DOMAIN}
        smtp:
          host: smtp-relay.default.svc.cluster.local
          port: 25
          secure: ''
      configs:
        logging.config.php: |-
          <?php
          $CONFIG = array (
            'log_type' => 'file',
            'logfile' => 'nextcloud.log',
            'loglevel' => 1,
            'logdateformat' => 'F d, Y H:i:s'
            );
        proxy.config.php: |-
          <?php
          $CONFIG = array (
            'trusted_proxies' => array(
              '127.0.0.1',
              '10.0.0.0/8',
            ),
            'trusted_domains' => array(
              0 => '127.0.0.1',
              1 => 'cloud.${SECRET_DOMAIN}',
            ),
            'forwarded_for_headers' => array('HTTP_X_FORWARDED_FOR'),
          );
        ingress.config.php: |-
          <?php
          $CONFIG = array (
            'overwrite.cli.url' => 'https://cloud.${SECRET_DOMAIN}',
            'overwriteprotocol' => 'https',
          );
        misc.config.php: |-
          <?php
          $CONFIG = array (
            'default_phone_region' => 'NZ',
          );

        sso.config.php: |-
          <?php
          $CONFIG = array(
            'allow_user_to_change_display_name' => false,
            'lost_password_link' => 'disabled',
            'oidc_login_client_id' => getenv('OIDC_CLIENT_ID'),
            'oidc_login_client_secret' => getenv('OIDC_CLIENT_SECRET'),
            'oidc_login_provider_url' => 'https://auth.${SECRET_DOMAIN}/application/o/nextcloud/',
            'oidc_login_end_session_redirect' => true,
            'oidc_login_logout_url' => 'https://auth.${SECRET_DOMAIN}/application/o/nextcloud/end-session/',
            'oidc_login_hide_password_form' => true,
            'oidc_login_disable_registration' => false,
            'oidc_login_webdav_enabled' => true,
            'oidc_login_attributes' => array(
              'id' => 'sub',
              'name' => 'name',
              'mail' => 'email',
              'groups' => 'nextcloud_groups',
              'quota' => 'nextcloud_quota',
              'is_admin' => 'nextcloud_admin',
            ),
            'oidc_login_scope' => 'openid profile email nextcloud',
            'oidc_login_default_group' => 'oidc',
            'oidc_create_groups' => true,
            'oidc_login_auto_redirect' => true, // bypass via /login?noredir=1
          );
      phpConfigs:
        uploadLimit.ini: |
          upload_max_filesize = 16G
          post_max_size = 16G
          max_input_time = 3600
          max_execution_time = 3600
        www.conf: |
          [www]
          user = www-data
          group = www-data
          listen = 127.0.0.1:9000
          pm = dynamic
          pm.max_children = 57
          pm.start_servers = 14
          pm.min_spare_servers = 14
          pm.max_spare_servers = 42
          pm.max_requests = 500
          pm.process_idle_timeout = 10s

    internalDatabase:
      enabled: false
    externalDatabase:
      enabled: true
      type: postgresql
      host: postgres16-rw.database.svc.cluster.local:5432
      database: *app
      existingSecret:
        enabled: true
        secretName: *secret
        usernameKey: INIT_POSTGRES_USER
        passwordKey: INIT_POSTGRES_PASS
    redis:
      enabled: false
    metrics:
      enabled: false
      https: true
      serviceMonitor:
        enabled: false
    cronjob:
      enabled: true
      securityContext:
        runAsGroup: 568
    securityContext:
      fsGroupChangePolicy: OnRootMismatch
    resources:
      requests:
        cpu: 200m
        memory: 400Mi
      limits:
        memory: 1Gi
    startupProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 360
      successThreshold: 1
    livenessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3
      successThreshold: 1
    ingress:
      enabled: true
      className: external
      annotations:
        nginx.ingress.kubernetes.io/enable-cors: "true"
        nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
        nginx.ingress.kubernetes.io/custom-http-errors: "502,503"
        nginx.ingress.kubernetes.io/server-snippet: |-
          server_tokens off;
          proxy_hide_header X-Powered-By;
          rewrite ^/.well-known/webfinger /index.php/.well-known/webfinger last;
          rewrite ^/.well-known/nodeinfo /index.php/.well-known/nodeinfo last;
          rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
          rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
          location = /.well-known/carddav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /.well-known/caldav {
            return 301 $scheme://$host/remote.php/dav;
          }
          location = /robots.txt {
            allow all;
            log_not_found off;
            access_log off;
          }
          location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
            deny all;
          }
          location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
            deny all;
          }
      path: /
      pathType: Prefix
    persistence:
      existingClaim: *app
