apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:WhNwXQr3jrkZ,iv:G7do0LxW64Ec9tgbdYEhmPX3kD5fUPu3wRT3Qlaz0yk=,tag:ikO0sukY+/WI4MARZ8OnGw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:rPTKpFsNWSvSIecS/Ny40lkGmggDIYnDFMZ4FnprZwSWzf0IYyuvrg==,iv:hTT4QksvYC5gxFTkzB5ic5qRFMWGLv8KD4xvn8aVLnw=,tag:rGvwiBFO2GOQGg5218X7yg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:BUDsoIdWnkmAeSGdnRlPZfk=,iv:sC9GB81Pwa7qSeZIbFFaIgWpIYa2Qoi48C4KDt8daGU=,tag:k4C0AEYaF6GN0sXLaX0XzA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:/XdaOHKdOJ9PtGu3adZKDYokcx3ILB9Jb9GDjVE6UhE4WM0jyTLaijpPomg6504DShGzNpkX8Wq0o+2iwJzg2Yg9Cy9DgPnwdovx4ua7XNd9ey/bevZHnCmXzvR2ucS2g9N2AucY0krdJjn2LTTM9WWjDcuq8UFs/c5gDpdZJqw=,iv:+PVNSHZAJ54y04xeZoeYpr6lUhsCEqMLcZ85Fd1h4QQ=,tag:POu2FTDyKMR1bPCMU2nyCQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:nPj4GI7cPp9rV2GpkU4n5dgzbsnxvyH2smA5ZmmlXLnT1kN1Z6gmvZc0dLMSsrUseWTrYYFccfgEUAtrHPXu7clTexnIom1MrX/fEnaNjk0Rou6IM8TUoc9X3ZXW/AYfFiOdlr/F7MZpwSsfiOEqmvIS6Wz086s8fCPswzsv8i0=,iv:GgDntlPz98CK3LSJs0fXQ563Rg/A+iJCF0uH+qm4E2c=,tag:56fUWQDUpBm+2+BArO7ItQ==,type:str]
    NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:C4bGW23qNcL1iEc=,iv:PK4mYsgn33VuswX4IAD0hoE2TwYlSKQRwHJvSELlCsM=,tag:YAxgREU2QVvA0tiaub3YJg==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:kmvy47FejSzy3idvZJu9EozuxEKD/Sm/RzNnk7Js7jQ=,iv:Uac1LcMpp6pr7pV6elmvP5sOHJj/NaTSciDN0HP/Ymk=,tag:oPENJP3lR/ZbQmwZCD+4dQ==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:tjJwZ6NOOT7U+bU2BrHgDuo+dUuf8QS0EKn6q/XkV06mXHydT3mi1w==,iv:8eLW2vvuT34iDH6wr9w1eYBz11yIAGW7WjEVkcPmwZQ=,tag:wNn/uAeWohUdnoGDE9770g==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:29YvF2aIg/QsAcGjQNwHtnP9FWfOvHZ5Lq1VaLLfvhxQvXU6TNnwobPBO5L2WC4rh6Fpt9+HheqGMXVIXgIVxvHPAcwOHv1T1kUvvs6faBFVdLlGb8brqFzMKh6OvfYkzglujUmAhRceI0H3U0fs/J3RMh1foGsJIt03r8kbvxg=,iv:Lkoqk8WXMj4uKlZ4U+1uoyWJpqqEeofvUROyUk6z3HA=,tag:3m3la1owWlGqcPpN1Yav0Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnVENaa0Z0OWp2OEsyeDdC
            eFZRRVBDOXlaWi9oNWNHdWhkcVBtbmZZSFRjCmRpUnF1L0N4Sy9GdEYzMldhZkZE
            TGdsWXJIQlA2VHRyZXc4Sm9Ic054M2MKLS0tIHVZQVlhd0ExL1JyMnNVT3RmN1g4
            eDJOblQ4d0FTdTJZeCtHUllQQmJKSEkKwp1Bh3Q8RAVL5ccZEb81z6HmPXW5R9mt
            fZ86i9EnBwrjjCjwzeJqEDnEgo/adLssmY4y94y1+Zs6B2Fq223Gig==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-19T02:50:25Z"
    mac: ENC[AES256_GCM,data:nAtLaCgfAIsV924WIkF1kSjisBjlg0fpHPNHPr8ovom5pFxFdcAkEzrbxKLDKVXlKjXeAbReXN0wOkTPtImxaGv37Ognw0PH65UsGwhjeRtqI5H30KXofkQ05JIuotW7Kfg6OdA64osVswH57B6XKx8D8mLmCtpQODGQI4D/mao=,iv:u9dxXg6GuWtdOMtGr9HHyhKoI/4A9EvkD3ecLLOI92w=,tag:5rsZA0RLXf/A3OJ0q1eU2w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
