apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:4g0gX1cF+RFy,iv:Xj6qI+yryZRD4uDT7dLg2qaTPiJmZR07Jf6y71xHSnY=,tag:ylLC3iY2P5n8uTnuKVCGZw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:R0tvkSiYhwKmFi+fwJjazJU1mSQ0kG4qIYbMAM/YlzWIRh68Sd3FVg==,iv:+IDSpIQH6UrYpeen7xYMDRO4eMXBVWmmYoedxydnP+4=,tag:hzPLI5aAaYesQl99GUv8Qg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:IPWHEFwfH94DHqu7PmEU+EM=,iv:jH747+WMlHCHdDrGy9gNo8/nhMDsFNLMTsl2ZsPk314=,tag:pHP0+EufUTssRt4qmcm+UA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:jUyBBEOAoOG//7Mu2xz2bM0pt1C4/94eG31ttiWeL284svIi9vdURucc5kVf2HCfPHNguKjin61CKdNM7VYGV7ZaKsYqHqPf+qCwO3yk1wgEPKru1mARghiGAZpkCnfSx25zMhlgaXbShbWqHnkwNdEscMMVHbBBQchhlF5Szdc=,iv:lq2cFcmh169aqkndMA3qPNZBIFHMgwn9sNx8IdiyPHc=,tag:28XvTvHBJCa13BXQUwKUrQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:vjDHUOsu0x89yQgm29K8Jy+2T06Ata3j1ZdFeece3/Rjyxh9cZttArxaDhz9A8crfVWw9/qJgswnoCw5QAoRPzIpnhNClPia1zkUbrccvO45uZYbw+dYpDDuvIXlcerSM3E+xnJLHbhfZiTcRos9O1pDT0qGo8mgnddRYUYTW0o=,iv:SwxTvATN5AmMBxHkcO7yott1EW6WkZ3peDDSkK2+eMU=,tag:pqlmgq3oLnjuBsGK3WJCVg==,type:str]
    NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:cjyRosLYL+/BrPU=,iv:HajL9Bp5k5mbmBOXbG6jqmjelAC3VIh/DAN1TC4rHC4=,tag:X7hIJDBwGD0MJBdhE63taQ==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:dhweXoGR8Dd8MfY9QZogCoBcmgWx3Jz9L3T57sSPGfM=,iv:Ikzzp8BGSQN/SUaQEf5xCUZKdx4dZRVlWmGxvoGEjzk=,tag:5wuKc9F5Xqzgij6PLJD60w==,type:str]
    OIDC_CLIENT_ID: ENC[AES256_GCM,data:eHilaF5lbwPoma88/Dw2y0gYkp31Ct4SuXNNUIzmefguXS7+7pxjgQ==,iv:if9mcaOlOZmwJp/rugWtIbGaL47E/xUz8K4sVVv2xdc=,tag:CF2OXPt2H+ZovPE0DT5LMA==,type:str]
    OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:UeXUYlL+hay2Ib6+aHEqpC/d+HeJCbJrsec+i7IGc8otFNh3qrgRsqXa50St2G9J5xylB8kuWxj9BNReZoygB0nC5PwgzBrlIxlr/+2VPgI5p7DeZAAn9KxRlibQUIWVxQyrPAtfYKiSFxNGIu8SXggyAJiOe+3YXNcE7cKTqyI=,iv:9ILf5o2dZqujNtOlXB33B4y9Oy3jVY4JhIHt/oaunQM=,tag:i67wLwnQA9bGCVCdFDSZoA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcXNsMmF1WjdvMkdhQTVU
            VXNVaUdjbWNnUEpOdUdDeFBLZ01rOVFObVNrCkZ2M1FYelpYZmtlUHk2dmxxcVlu
            a2ZSaEMzVlZDdWdlTFYyYytaN1BPOHcKLS0tIC9xeEdLOVRWMnM0VzhIVlRrTFpS
            aVZrSUVPWjNRbEhNYnRCekhYTnYzZU0K3QO7mW/WL3HgWWBAfmXsMXEqk5nSZovS
            UaxEW30c5B6t4G40QO62m5hp5P8ZMCtazsKmHQxqyVlADdzolkVweQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:13:26Z"
    mac: ENC[AES256_GCM,data:bmPcRR1W0FW3flwHdB3y0BtYIo97XPExLJRG6sKvn8CLGMXXRf1TJs7HyKbhwfTtESMMSlxpftIzoORn2dFv4Pa2MsquI0yYI6v6sVyQZ524+FAeR0XC8sLnGVr+PJBkiKj9abPnW2fU1UzUpm3ByBllcPl0/qqvfQozq3tLtog=,iv:mp+Ktidm0VdxOeB6cNGY4b6JQLlZRAyRf5giDM7au2U=,tag:qTwpUJHtlFNhdtdaeoKFKQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
