apiVersion: v1
kind: Secret
metadata:
    name: nextcloud-secret
stringData:
    NEXTCLOUD_USERNAME: ENC[AES256_GCM,data:qnvTJXteMK/t3Pk=,iv:3U6VZBV58UK689CCvnoubcT6nYqdGTgyy2Wvm2YA4+c=,tag:qQcislGHlyUAkdDJXAiBoA==,type:str]
    NEXTCLOUD_PASSWORD: ENC[AES256_GCM,data:v6srO3Cf3f15HBIiBM8uGdfqkcR8TUOnqVTB5S5iIZc=,iv:xHxb1tajawn2zZelNj1Ajwqcg5xVs2+2N93Dji1NQUw=,tag:Ha0yKosUHZ6A6xyx8eTb0g==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:oQbWBUxp6vK9hRpLyoRf3VaawiRfLKRtgs/jUvIlkAXtpakRbscS+bBXNq5I8ySHE1ig85O4s/X4nLRmK7AcC39kc/70HAY62DapFp+3sMt81L69MXp1UfyXplVBO88qRN6iMGJIyhbBGIGXGgxfPpXDDBJ10QSt1CKNm6traYmg3kTWZe27b8r1vcA0uFc7MXq28DMlo7LBJBEah8VheDgQcezTnmUQgE6tnmUdK4/OLolb5gTdFCb/QvNf/buTBVANgh9ac5Qojqyfp1jZreXTxvSadteK,iv:pcAwHVSlU/eOgKC795e+BItlNC8nfwo5orr/02hhnqM=,tag:CudzrjHo7ssxbuVdtt2iPQ==,type:str]
    #ENC[AES256_GCM,data:FVfeTBOFGzvufrfRJe0=,iv:X8F0N/gvwq2T4uqa68BmGlIsNqjUOpCVq9vHiwvRNe0=,tag:EMwbToNDZPuC3Od5wz6MGw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Xc2nFG+oQ0TR,iv:DzseD89s6Auwk8RGUp+/hYhBldwpLosbpkqHGkxHdO8=,tag:Vqk5FvXhaOWw81eT7BpjPA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:BFxYEa2Cif5FVt5oKZXrT6qTxcM+LTZRHp7hRQadegSALP2rPB2vew==,iv:H/O1h56z/TspU0fvK9i1ero+QHJBkj1ektsb0e7k9f0=,tag:Wdu1l1trYWYShCfqPSfHMg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:6BW9o8Wge4jnQYkDERJakZ4=,iv:YOsKpU7SoezQbkwEmdGg6gXDlE+FMv/lHyCyDELvnaY=,tag:pCAGuq3yXsRduNtNlWXGZQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:mi84Lc7wg1gq6Q4bKxX5JA8aW67CSd7AM9ZqSaG/o7mymn17fDixW0IV/rYzr9hr+XEVgncaGDWm/PCejXx4TlO31tDfTmUDYxPMmw3zTl5t4gOdDFz19He0hMJhVuqSguJk5I4SBp99ZiKzmWaXiWieHzdJEr8CLcM7RuzoTnI=,iv:gp9wAU6T14nPN1f3HbPKDZbTyC/IwJxiRcOsR+3SY/Y=,tag:3L1eHgJHpMX2BYkAQNKBxg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:wuzt7AKMJk8BEeFWPZvEujHxyndh7JT674ZvMFloEvFE28nKQMWxZGYD8OzK6VbW+gE/RuknCeSkaDyVwOtvQpTmYXzFuhospqxQzMlha4zVCMWclHHTcKXBtBUc4SDWPIsKiGkia7Z9jCQAqAX6onaDzkd2GbMPOLR72YKJ30s=,iv:0qABSuXxFaUZEghgxc2BPSqw5EFbSnVYXEcNUuu/l9Q=,tag:xQao0KxhAjWSqsjfuF5Jfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoM053MU9xSytSZnB4dkIv
            cHVhOW4yWDFSNms0TGpVM0xjYUFYaG9oQ2hnCjZKZ2VPRGdRWHhmTnhkQTVhaHl6
            THNDcmdVWmQ3MXFHNkdRZWdMNURtT1EKLS0tIG03cGN4V1Qyc1FyMmE1UjFXM0VC
            b0lEZ0pQMnVVNXMzaFRXT2lEOVpoUGcKMYEvQAOnyjov7O+ji6tQCVjMeLPuBwzm
            o1DhSpDBSVn+1liO/cfGOXzb+3sMfWF9AdgFqPpzoom5kP1LCoFduA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T14:37:21Z"
    mac: ENC[AES256_GCM,data:jOhf/sjyC2Ya5OeLZ6XfiChK6Wz4dKqNbmxL0g1V0aV12iSO9+NPTZpm1wgh+v8KnYCjLaeoci1NEpvdqrL1bD/1EBeoOyLWwpuSjb64uswrV83k+OimbKe5yMhP2KjeBe3cAocBonvGpYJUUuxMev1gy2YxtAJPhu8ReGsomUY=,iv:ntODAFbkl8kgZhGTyMkf2UH7u+tKBNhCEjI9PRhEcjg=,tag:+h2PHbHvcknKoDEg0H7bDg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
