---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-init
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: forgejo-runner-init
  data:
    - secretKey: CONFIG_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /forgejo-runner/token
    - secretKey: CONFIG_INSTANCE
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /forgejo-runner/instance
    - secretKey: CONFIG_NAME
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /forgejo-runner/name
