---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: forgejo-runner-configfile
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: forgejo-runner-configfile
    template:
      data:
        config.yaml: |
          log:
            level: info
            job_level: info
          runner:
            capacity: 1
            timeout: 3h
            labels:
              - "ubuntu-latest:docker://catthehacker/ubuntu:act-latest"
              - "ubuntu-22.04:docker://catthehacker/ubuntu:act-22.04"
              - "ubuntu-20.04:docker://catthehacker/ubuntu:act-20.04"
          cache:
            enabled: true
          container:
            privileged: false
            docker_host: "unix:///var/run/docker.sock"
          server:
            connections:
              forgejo:
                url: "{{ .instance }}"
                uuid: "{{ .uuid }}"
                token: "{{ .token }}"
  data:
    - secretKey: instance
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /forgejo-runner/instance
    - secretKey: uuid
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /forgejo-runner/uuid
    - secretKey: token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /forgejo-runner/token
