---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ghost
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    link.argocd.argoproj.io/external-link: https://blog.darkflame.dev
    argocd.argoproj.io/sync-wave: '3'
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Darkflame72/home-ops.git"
      path: apps/comms/ghost
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/bjw-s-labs/helm
      chart: app-template
      targetRevision: 5.0.1
      helm:
        releaseName: ghost
        valueFiles:
          - $repo/apps/comms/ghost/values.yaml
  destination:
    name: in-cluster
    namespace: comms
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
