---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: matrix
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Darkflame72/home-ops.git"
      path: apps/comms/matrix
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/element-hq/ess-helm
      chart: matrix-stack
      targetRevision: 26.2.1
      helm:
        releaseName: matrix
        valueFiles:
          - $repo/apps/comms/matrix/values.yaml
  destination:
    name: in-cluster
    namespace: comms
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
