apiVersion: v1
kind: Secret
metadata:
    name: gotosocial-secret
stringData:
    GTS_DB_DATABASE: ENC[AES256_GCM,data:cSGkMY0tGjgqOw==,iv:0x1Zr+ElOBTtxxOliRMLZ6n3HXViykQzrqYTp3O7pgY=,tag:OkEkMSgusDXYb5ZnnHiHVA==,type:str]
    GTS_DB_ADDRESS: ENC[AES256_GCM,data:k4qhcK6RJ46HLyvSAi5lY++Jx2ZBtitTejU0d6PqiDEmK3XmOLIFFw==,iv:WglOLT06EQ3Eg4IMvzLivH6xLNojHehYwi/w9SQuWgk=,tag:WGLeRNy5X+TQX3fylSDcBA==,type:str]
    GTS_DB_USER: ENC[AES256_GCM,data:Onpgi2gSd1rZrhETaxH/5M//,iv:aGcWbGSCjaxTcoXFsoLaRRj4oO5K2Bkjp9/Fb36QoX4=,tag:cpDgQNayx3jzANfkDKIujw==,type:str]
    GTS_DB_PASSWORD: ENC[AES256_GCM,data:rd4M85IiS70GcTMz5s4CKBS6iod2a+iQZUITNY0cKbP+GqQUhzdzFBmxdnzgMv192XK5FgaE9gq4x1/8IUq3Nf6IYZ1pyaYym8xlQ5phTqhGOKxMdTweXDl5Y69JDGmWHJcKUXRCcOFTGylK4jn+raiHlsIQidlAUm6rgJ85Joo=,iv:gEUp8JK8Gpm/rKBauRpKTScSkW4Xn3nyG9RLxul5jeM=,tag:15g8dBQzubNl2PL0DGLR+w==,type:str]
    GTS_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:F6L7lY6fGUWK,iv:MImoHGecePDZHo6420WImkoUXtLa8fOyMyaQgVrzMsg=,tag:3GdlH/afIWxtrUfOtxAlUw==,type:str]
    GTS_STORAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:l5Bbz8D+nqFneAHrAkfAcMIA//3A+RDU/LlcXKTSZrE=,iv:2JnbSyFtJiabsIPs5bJrgUT84b2Hk0w/AFAWIYY8P1E=,tag:l6S7rIzwUtj6lTAm0N2iow==,type:str]
    GTS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:wY80Yj4+OXLECvox/UNqnQh9OJPzFfWNmDn/xcFmPMsCIMflyf5TEg==,iv:8A3UfJ9C1dp4WXS/MUJAzf5Z/CkW6l1e2iidh223oF4=,tag:+C21M4GmKXdlW96y4m2b4w==,type:str]
    GTS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:jI6h94ZROqeSgJtfWPndmMnvpifQXVmoBKSJNjNWGGaerU3DFXbyXOq2pYC4rrEWuXsT0BufJqThGT9FIPFBvxv5KEjg0tSsewdARhl1ci5bqCCMeebHOhryk5ewYS1/DtxMCbqe22SbP5I6B/TrBhVhVGp6HjF6Ql6HjIgslec=,iv:nMjznfeKyP2aFH4OcEdYYS58sF9xZfy5BNxHWasGl4M=,tag:FWKBenKw/5ax9dt5MG3ldA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV0xTYU5vZ3d5NzFkZlkz
            QU84TS9yZEZPa1h1RXhDcnBPOVA0aU5QVEZBCnJjWHU4TUxWT3psSzN5RzJzU0Zy
            ZXMzMUkwN2VOODlVZXFseWVhekI4V1EKLS0tIGRMV1VabUN2eDB3MTdkYk11c0Q4
            ZEpWZkRSNGNXck1pUnR2T0ZLN0llS0EKoYGTj1cuojR5TVHD+nGG3S8nB/AvLWOU
            AHpSTWgJPXHRgNqm04aj5wdS78X4hkNjk+T+SCXqJj+cu8uqfuRTBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T04:07:54Z"
    mac: ENC[AES256_GCM,data:R1knsDEEpM2OCkg5OgSpVdCTaZyAkqDHGD+QvJF6lcNOtwIl4PzO+Uq2/Cr4oRn6Q9AAM6IzGFQoVMpIT5ng5LUuAY9H3cYrJUd4znM24/5HmIBokpgNZAz2rlCf+G+QDWPv/sP+OF2q3RzzLrkXRSXq5X7d9bjG8H6jF5yTp6o=,iv:kxh0d4YqhqdNQgSY6K1v2kXp8onDxvEERE2OoTgUoqo=,tag:DvzczqHALmEfRBauNz94TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gotosocial-init-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:6E4Z5xQKng+Vxw==,iv:o9KGw/CHCtFEHZWSWlgmEEFxQV8MEJaD0xSD1AZWzdk=,tag:5DM7TWQM2cZsRfDo9Wetmg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:pCmhuBpe9oGWsOaqlqyuC73DzYKtwk6s9R+a2AVly9mAY3lGsYVCGA==,iv:qBbpfJCsJKe+0z/UAsn/uuwqdQbUv8RlZloWoAYho5E=,tag:ReblYb1mgi0GJATcfm8FOA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:oXUs2lhWOuaV59b9v8YKQXay,iv:Zche1ryzPPyrnm6VYxoNBLPA0mHCsoLPyneGYFH90I0=,tag:lMDjb6KDT/YT/+KlBfjGkQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:O9FO8kBwoJJvKSJbnJ/V2rFbS8rzFU0BVN78hg/VHnZQL4oW1AlMgiNP9zjUxayYtguyRrPbFl7Nz6pfncA1CA+6aE1FoICLvtSiG26VzIClsnguv+JhqOz4CqeNizgl0knCL4L807GlrgsOObfAu9hRe1I71zO+00U1irSw2TI=,iv:Gz1VD3mfuyJp/u9QNtM6DBO9IgCuQcDi3uX55eOW+xY=,tag:lp3LsQWk+cmZyeksWmxtbw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:ftPfDtS4FUgMUF6rCgbpl3YAckmUjBsAIu01Oiy/MN65STb1L1JpuJzcGyxAU4EvpqntTa80j5SQM1lNqhTYj86NeFmopIfxpeP4efCmiCERlv0lP19xA/B3lCEDaa249vWnFLvrXw1Ch2+a/KFYjMS3ckZAuVA8+Kq8dUiy3Gs=,iv:XrGtBWJAjnbf8TQxZFuI11Z4bwX2Q9KZVhzlKclraMI=,tag:gMWcHBNaATW4QMdhtsOMQQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVV0xTYU5vZ3d5NzFkZlkz
            QU84TS9yZEZPa1h1RXhDcnBPOVA0aU5QVEZBCnJjWHU4TUxWT3psSzN5RzJzU0Zy
            ZXMzMUkwN2VOODlVZXFseWVhekI4V1EKLS0tIGRMV1VabUN2eDB3MTdkYk11c0Q4
            ZEpWZkRSNGNXck1pUnR2T0ZLN0llS0EKoYGTj1cuojR5TVHD+nGG3S8nB/AvLWOU
            AHpSTWgJPXHRgNqm04aj5wdS78X4hkNjk+T+SCXqJj+cu8uqfuRTBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T04:07:54Z"
    mac: ENC[AES256_GCM,data:R1knsDEEpM2OCkg5OgSpVdCTaZyAkqDHGD+QvJF6lcNOtwIl4PzO+Uq2/Cr4oRn6Q9AAM6IzGFQoVMpIT5ng5LUuAY9H3cYrJUd4znM24/5HmIBokpgNZAz2rlCf+G+QDWPv/sP+OF2q3RzzLrkXRSXq5X7d9bjG8H6jF5yTp6o=,iv:kxh0d4YqhqdNQgSY6K1v2kXp8onDxvEERE2OoTgUoqo=,tag:DvzczqHALmEfRBauNz94TQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
