apiVersion: v1
kind: Secret
metadata:
    name: gotosocial-secret
stringData:
    GTS_DB_DATABASE: ENC[AES256_GCM,data:BeZrRxiuCA2VCw==,iv:nrCvgQfnbxswX76XOfmEhLCikXz73ta7pRUrK52gQ3g=,tag:vZSkU/sgK/LZ6+lSsgUWJA==,type:str]
    GTS_DB_ADDRESS: ENC[AES256_GCM,data:q2HfkFcQEXCzujMo21u9gsHn3BPv3sKPfV2jlDzxi1JsrZo16PiRnQ==,iv:s2eHfdFxbwzp9i1nGOjs8eKQ1PWB7N6IIfTUGZW0VBM=,tag:YCuDZ04MORcTDxBbuWjgdQ==,type:str]
    GTS_DB_USER: ENC[AES256_GCM,data:jFxy4lsvuGs07al211bDJIG5,iv:d1AKNOfigscwJLYQuqQTERKbHirl0HYqV6AgyKPXcxI=,tag:XkAzX0E0MQ6ad1guNRnFXw==,type:str]
    GTS_DB_PASSWORD: ENC[AES256_GCM,data:mlgDrPXP90qF9m02x88ZP3NH0JHJen06HKbIHQt9pGFNFTn1HlPu58/9f7ulxHeqaXolm21QOlgqSMrRCP/IuithoTbrHwnp4Wf8YJGNrq9l1n+Mh/WxuCgnlVmmdCqGUZDOSSLoaNerV4/YOmG3KAtDQPdSCehSoEDRhYMehJE=,iv:l8tfiAAMpEZzNdMIWmLJwIQ0lBTw+EFmWBQxx2wR6J4=,tag:GVps70Aexh3Ij1uCj1QJ3g==,type:str]
    GTS_STORAGE_S3_ACCESS_KEY: ENC[AES256_GCM,data:LP8+fx3H+2si,iv:BT2BpW/IOmt8I/w24n12jHOIJKqLKyqterl0tS6z084=,tag:K9o66Z5L6uabiJdk/YsMXw==,type:str]
    GTS_STORAGE_S3_SECRET_KEY: ENC[AES256_GCM,data:fE5L4A7Ym452ZIOyRbEwCCUHGI3RwgFWhpXeKil2mC4=,iv:881BYoTuwmOWTSE4zpDWQMtd+q8PLAnd41M1VYPKUc0=,tag:VBNiMQ0vDSUNWpqv5cGEdw==,type:str]
    GTS_OIDC_CLIENT_ID: ENC[AES256_GCM,data:HHZ/oRl97cTTrQu4ZCyjvElzx9RAC3sHT+YM/zgA87X6wfI/z4GPog==,iv:ng/Ebx5ZpA+WmmYmEhKn0Z9YOLkPUvpsNZPnT0B5xYg=,tag:R1NB+zGLDHd7e9T04iUBKA==,type:str]
    GTS_OIDC_CLIENT_SECRET: ENC[AES256_GCM,data:kMhWjTN0HcP/TZHh4hSu+oL8lMVp4AUMSVW1ubawrVScEeA5Ow8N05pRdHLJoLNgrhBobdykFVWvkAhcqmmToehfMhZW4/VeX7jVA20CL1F6wSmezyjB8KDQljJNTFOQngqVVXSLIp603zZmmaa1n9z4Y0ZWE7U+QUoIdOy+jIQ=,iv:sqs+78l6AP9h/lUbclPpCfbTEAowR+OZ8PHZgKOiccM=,tag:Fm9XEtbxzXLZJLmsaaupgQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU2diZ243VkxGa3pjNXlF
            Sko5Z1BqWHI5Vi9SamFjMmsxRzFiMGozZWt3Ckw3S2p6SlYrbTlPWDBacm1lc1NR
            UkJLenVSOVIxdEVURFJhbzRZTnIzNUEKLS0tIHFRN1loUWN4cEVGQnpWbjdLZGVq
            Qmd3dFlqTEF6TFBTYmQzZ2RSRDlyQXMKXaWQ0yQMOee6b31lmKyEpp72W0CU8kdX
            P35XTNBp5x7gJBPEK5wRwvSXcO5ymMrLdkoEhJ7qk3AATHSiBZeYGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T06:21:56Z"
    mac: ENC[AES256_GCM,data:dODImYr0s0Cgo4tKmdFyw+9XKgbSXLRSOBVFVbDA7d4OMhntSxsu7ZXW/E/a5iRNSDZZeg2bU+8PxhwOMtBLmmvW7k8z/ozw9rHFqqda1gTFGQVPd+e/z9d+wyUfC8avczb2myMutHyyO2Vyv5j/o4lfqIDy7+5Q11uxLx2O4Fk=,iv:z4QuPHY+wrXviULXSNSrW9FKqO5BbvjdEAx6PvHddBM=,tag:TIo14K9sdcE4J9B6BqglLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: gotosocial-init-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:eR1H72NLlWAM2Q==,iv:FjzcQxANl5pKESszeXce0xPkk21wPPoJTHTxamKkR30=,tag:mFU0isLr4ua+QuJ8R9q4Tw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:2wa2UYSLNFTYoMtBLRet15xMdLqSksb94zyTxhsC0xjHKtpspP9xGw==,iv:sQIrME1EMYp8175GkkpQi48xULdr1vJ/VvwNmZib0Ho=,tag:2xLtVTG1dALhQQY2U/sm9Q==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:kYWFaSe7PI+6xPHlX1KBFLcp,iv:84wZoeiTFRzURhtSVJ/MEbCN31LsJEblvplWyTgqOd0=,tag:RfSicoa92kf+XSPp84IzCA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:eX7CHV47qwWI/RClHPR+B6+3yPq4zrBWHjfVwv7Nn+NJbYkiLfmhmTq9UOIrvKVzIbAvB4Fm3hSHDFrc8OA+6dxVLnc55FDtrGOWtKP6u9I3M6GrpLiNHL6di/46IY+FfO9b2rI/By1KA7VaII/zadHbW38HlTDCet1X5hWt5bQ=,iv:OPmOWoTk/5wNlX5WhvZ2SxRm26J6s6F8B53cqWv7DeM=,tag:lROb0BB9wYlglrwwXDeOPw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:NpODfbOwAIZPRCI2uSRNXLSB/7Pkizk7dghEFFa5IhiAaO5K90rSc172ySdD09Wvl+0gNyQ8avm6SAvf7vRPQ6SOa2chYgd7vBgXEm2jWKqdF9hZlcyOrXzIVW/K0WT4D7QXmGCnhlLlJW/1zVqvFcG9BkdpO4kvRp7iTHvKd00=,iv:QR0+oZbV0iFw90VBtzHBaL/jWwbH+y5LagGeeKBq4X8=,tag:1QLe/QLI1mLYdCGhhAt+Xg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEU2diZ243VkxGa3pjNXlF
            Sko5Z1BqWHI5Vi9SamFjMmsxRzFiMGozZWt3Ckw3S2p6SlYrbTlPWDBacm1lc1NR
            UkJLenVSOVIxdEVURFJhbzRZTnIzNUEKLS0tIHFRN1loUWN4cEVGQnpWbjdLZGVq
            Qmd3dFlqTEF6TFBTYmQzZ2RSRDlyQXMKXaWQ0yQMOee6b31lmKyEpp72W0CU8kdX
            P35XTNBp5x7gJBPEK5wRwvSXcO5ymMrLdkoEhJ7qk3AATHSiBZeYGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T06:21:56Z"
    mac: ENC[AES256_GCM,data:dODImYr0s0Cgo4tKmdFyw+9XKgbSXLRSOBVFVbDA7d4OMhntSxsu7ZXW/E/a5iRNSDZZeg2bU+8PxhwOMtBLmmvW7k8z/ozw9rHFqqda1gTFGQVPd+e/z9d+wyUfC8avczb2myMutHyyO2Vyv5j/o4lfqIDy7+5Q11uxLx2O4Fk=,iv:z4QuPHY+wrXviULXSNSrW9FKqO5BbvjdEAx6PvHddBM=,tag:TIo14K9sdcE4J9B6BqglLg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
