apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:LStDimZWge8JJoaERePbL0Fw+kQgX8Dio8Gwp1Z+v+icIS9B,iv:G4UbS/Z43SZXPk6XtYQVOi9LXjT9Ggrf5jdJqboSaRw=,tag:1ZTJuMxAchurPqXHsMkB0g==,type:str]
    credentials.json: ENC[AES256_GCM,data:Du8sPQZJPYojg+d+4kot82LiZBpy7Jwu+iAsA+I88MJpv+2RlJbr7mqRtrZqqRd+NbScOGwNYXGIL8RtWOrM9xrixlOoZ740hySlt3LjzEBPS5ri0/Gz0J/iYKj4COlT040C6ggUOEuzE/NUsUwQYNNrkSbbQsOY49OcOttkB8X3UGKZKG523P8k4ON3Ull4MebjfxS4Tn+N1KKjKJEWKE5jp7YVahT1Ac+jghaZbg==,iv:vDca1kLlf3OpShfFTWKUrDjQp5U+SiMCbiTtPimUEsE=,tag:avt7XINEelFTpuQOzSYTrQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzK2NmUjI2MzcyMWVJQTNm
            RGNZdTFYRk90ZXJGWk5zVWszaVpEYmN6a0YwCms1VUg5WFZJUjJYbnUrZndYRUhH
            M1pEVXJYbS83aHM2WjcvS1RVbEdvcVkKLS0tIElIQXlFTzJrZFFHTFZ0TTVDdnpK
            OVo1cGYzVVFUaTZrTlJCc1ZFN0N1NDAKDjDLgIlykYAlSsVHqRdIQGggkAKsMuJq
            xOEeWRpBTkpKcZ7+XTPwk60x4VY7pbfet2dy0KngOx6Wo5lMxhPKTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T22:22:52Z"
    mac: ENC[AES256_GCM,data:CNGxHVbi4Axw56WQzWk1OaTVda+xO03xTImXjv2alKH6V43eWTxbarYOfRbcLHApzhnfYS5zX38M3fezVnetA1CAbs1UF6wLEub5Y41ziYmvjPp5KKEomYzE5pCikDmcdBIhgbJvGBKtXk3k0AXiRBZdjzUWXdYMmTLTvhw54lQ=,iv:23PXqvNBM1nKCCmKxb3dAvfy9O5drv/A0ksKM5F9U9w=,tag:CGDdirjU0LrMEkw4moG9HA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
