apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:ulrJKi58HUyaQY27jIpfHWmpaowo45WjuLhe4OO0Qt4UVpMe,iv:bzXaF5OZGmwmvcp2bCB2pkT0iZYmEU6A+bq1fKD4rLg=,tag:qWEPHlNePP6LNHK569a+Jg==,type:str]
    credentials.json: ENC[AES256_GCM,data:7YdH95A+97cJqrcIhqdg/kV+PUsyZu2IhGeAwq1+xPfCO3+eMshgynHQokY83JIz62jLJB2cpEuYkf+HFGSL1tdzQ1RbmKa/EBHAuUY/YtLUfur4FTbeHu1LzL5ljqvprzMl32N4RYohl0bin/l6clRLi4+PURlfDFHmbukZOgKdL2ItnDQpw3HZPexfi3yYmzEp3N+U2i2Buaj5kDZ+YkBEJ4Y1ba9e/zGiHDhSMQ==,iv:g5Tiy5M3xPaHjocsGlp6uF9GUNvmoYJGou6s0aWeU40=,tag:J0QqqcdksHAvIVG42KDVBw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOFpmNFgyNzVIamhKWFVr
            WU1hbitBOEFjNHNLYXVCbERjaFRmRlhZSVJFCjVuY1VZRHNWcVhRdmlhNmVPeWN2
            a1FSSHRVZWVQcXY0a0hoVGJhaWV4YWMKLS0tIGxDTDFWTm9mRzJKUlhqK3ZiRkRm
            YlF2NXo5N0poUnk1b293TEs0ajVjdFEKMa15A2pgEd3fJ6ViGYrtzSPwsNMQsOFk
            ey5oO3CbM8HMmTgsdeDCYpCdWd9+ayuj2IHJHS73ZKxGMYgmeouMHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T12:36:18Z"
    mac: ENC[AES256_GCM,data:+bi17m2jnrcvdMzZ/bBbvmCMTOPX2XjUpnNKBIgZmPMEFdcoDygRWhalWPv/2u+t1R/3J8CR6MjNFge5AGrGN6gBumrTUtQJ9ADBMQzjX2QUmqic3u/0tTzgYP+lXf4R7/lfBorEW5opbEQqrF98dVTYInkGk4qh3S2j7EjwveY=,iv:2bNWb2HJQrxNxbEI8tgkaDrvngM1fDAFv4kwukoyZwQ=,tag:7Aom0zlQc+kqsGsgr0EkcA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
