# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:BOFZEOPc8pNbC+bIvLyHpBxrcfF12UsGxKgcXPWfkjLW5PIhYfKFbA==,iv:GlI5LUkSYGDgFCzWKiJYHFTKLwGaXgamgnGYYG/p8Y0=,tag:SwehQmmrtpYcNoIqBy3evw==,type:str]
sops:
  age:
    - recipient: age1pk4hw4gdplvq3tz6ma96hx3ja4w303ld5n5x82yqzyhj4g45qadqq9nf4n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBudHNUc1NBUGpic0E4THJJ
        cUMyVEhvaXpiL0dxRHNFUXd2bkNXanAxZ1hNCkhrMEw3Zit2WlRrc2FtcUNyM2lu
        TFA1Z3RtOHhhcUQvaW5NNkVNRisvQTgKLS0tIFdLUWVmeHp6bzhQRVA1ak42cVYr
        QldpUWVkTzhqNG5iNzNQb3BuNUFZaWsKDx7/+MV6UJV2AoX+40PfFxekGLGM7Cv2
        pXOaQsPXftPxgEo09m0P1sL7NyksYDZsITOaRHLyoNNKAhwzL3q8gg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-25T13:03:57Z"
  mac: ENC[AES256_GCM,data:Yb5sZ2CiKmrjpjfWucRddguNZU8MTlacCWFMacw1gjBivBdTs/IqOzwx+IY1XT4WqERIT3FHIrNOR8fSsATx/PASrfSvgDPqVUmo0bzKB6xa7jDus/4nEsxzitsHxAb8S5uK91WdhEHMQTTOKzBYTOMa3mPHF3VNwKBCGv5xDsU=,iv:yMYlFkFpx8boSAyIZg7NYeW17+2B5Bc6zQNMTifzzFU=,tag:UWBSEKNbAUAjm206WUOlzw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
