# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: v1
kind: Secret
metadata:
    name: ${APP}-volsync-secret"
stringData:
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:8BWoV7pYdAprzfKUbrVm3ae0,iv:nEDQffQ7GUDrthwNG/EeCdrNOAQ37Wkud3kP6FRzXzI=,tag:m2lvntzox9RGLpMqMJ4I2g==,type:str]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:xKEJZO5YCMN+WdCTd/orYIEcBHRaDrF04fih0EpJekI=,iv:1Hmib48A9Ouk8Ji48DnkDBQlevOE7qq5TQjFbl5kQlA=,tag:4hxRJVZ0gAl1NcE4sox4tg==,type:str]
sops:
    age:
        - recipient: age1pk4hw4gdplvq3tz6ma96hx3ja4w303ld5n5x82yqzyhj4g45qadqq9nf4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQczFJUFZvUGt0YmxOc2E5
            SjBNTlgwSzJPMXljMWI3ejdESXFnbUhndmpvCjJxYnQzZ3JGWnJpS1dGSy9yNnIy
            eWxSRWZyVXdtcVhzWG44M3FUMlB5anMKLS0tIDJmNy9UekpTUmJ1T1FPL0pya3JR
            RkJVejZlTEI0aTh6Z2I2SE5LTm90Z2sKaUHqVjoZ1Fd9GNWAGmrBzMcSTfAi12GU
            +/ahi06IzOO4IxsA0I+2328blA+Y2EuJWmsUGucL+GCWpB1vStaJmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T14:39:46Z"
    mac: ENC[AES256_GCM,data:rfSLFgPtfeYIFww1hOYD3jQ1lbbZblH/mBgTRR7iyxKaZhoZ94PYeVc4B0CQaooo5zd2rUV4UKEFYpFs1h8rrHBViCd9Jxr1OzLtu+aeyRRQLn7fsbAFe0w3YWqBd6iukCfFQ3JGdv05hUxnzzH/Y7oo44XbpZzyDIgwY0kFwb8=,iv:b0ifkg0prTD/KGFYWToBeAqc7D9zpjmmb5nLMObYMQs=,tag:dH2EVVxvjWBNzScOWVj/6g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
