---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openebs
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Darkflame72/home-ops.git"
      path: apps/openebs-system/openebs
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/openebs/charts
      chart: openebs
      targetRevision: 4.4.0
      helm:
        releaseName: openebs
        valueFiles:
          - $repo/apps/openebs-system/openebs/values.yaml
  destination:
    name: in-cluster
    namespace: openebs-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
