apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:gyiVUr5kJvM36TQCwZDSwP7J7jl6te81Kwa3/I+Mdo4rrh7yubxznG6ke9ICg5vDPmPTPWRe/e2IgQ5WLMYIVqpzjF0UmNfh2TvOPbCX6TDMT4Y3YgtVyyDV6S3wnK+hgoqpVfZqc8usizvPAh/lda3/L2FXRWKI6pTg02IWsGU=,iv:0aro6r9X5icTT3Owm+jGYtNrRhbgLvt0NYX3PLjZR58=,tag:mZ+IhayU4fp/S8p0GWXbRQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:5er4wFqPdGf4ap1X63ZI+4jSl9VTGlNYq+LRwLeKIVeWH3aNdDbxdl/j/ZlF8i8brPQ27LPp/EMp7lZ4xOget4qoinkHPKUDdW9LB5CFmlwkfCbvMHLfTHFeeCrBnIfiL7bdQDjoHlw5wtYXeISG1DAaliKSc1dr1jqbYh8mPStyAq2SWM0YuBjBv1npmBC/0wE87GOLaMNtlb4F/NMObnKmwtstpErCpHLxGzv9rnvH/yeYhzrRDQvvEvpIW7+WWotZ5GiojOSZZyiedbuGZe3cgphxnGyEIRMNAg==,iv:rfgCJeIM42JZC8nxVH15EFg93JSYm9Vsepu3EL5i46Y=,tag:cMv0/m6HrZU/EoFDyFAx5g==,type:str]
    #ENC[AES256_GCM,data:JTSvMuFQgZFIAfArJtA=,iv:9QB5nbz38yFZXqcw1sLCJBM31JUvYModNU1QeYPDwhM=,tag:BRBRK6pXhS0I9vjVaCxLAA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:pvq8lWtgOQvx,iv:2FAeWRMin+ZWN2ikFITni91+K0bxH068uLRkfliiUW0=,tag:KwBWuf30jryUfshKHjWGUQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:sXNZkq5bV2BeHyg+QWyZoIPEUZG64qJ63N2upKtPrwT1sEtrJci42w==,iv:bwKa/c/rEwujYbRZurt91UKl7SZI2M+w5o6IZDmsZas=,tag:8Rw6vtiMzJjh9VItMTIfAA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:wCV9RNnXmHOXZ2j/o+AhMAg=,iv:4iKCuZzve3KzYxVm4Q85WSinVpyoZG0mCc6++AStUa0=,tag:crBLMU3J+LQZwkNg8R1IbQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:GXB7cOFs6LHn4DZn78UcRvr48u0UWa+00Ir9aYOcOrwvDjN0shtOTU8YyKQg1ETtO8kMnsUDTLII0/5qt5KIwHv1x04TrON9QdEMUU49mUgv2nIKoZWjlmArbsFrdSZRABUZb5wxOWg8FAesKJkFEQqL60CxGk8fLYjlUJIFVUY=,iv:dkcSIdG19lfJUD2D7sRVBDEXV+azx29UD+nQqR4pugI=,tag:Pb6KJLsKf9kyy7iMdqRv4g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:mAK6hi0PV0c3PVHjyXmP/1Zxkc5O9lDPVvOB+ROA3ebjUZydRUjhVty2CxPHkgoT6347kZxXHQoBwI3MIpuHryWAWSPTOc6XBPBA0uclIFObIv4PPi3tnoWzUirnZgN0W/xqn4nm+eqZZw0f5FO86wRQZkkdh+O7L5ldOdIGRrY=,iv:si0hI5biiyFpeHFyNcsszr4kS72SUNBQf5015hvg5cs=,tag:1ityjPpOZ7ASeGVgU1HARQ==,type:str]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:KqdOGWNPPYJv9hdd1LiVtHth3x7xytnScGM3vrI9JsFy+1pGXFHa9g==,iv:ZtkhhEZOZLygDHZCrtHTiJP5hvY0nfHwjuBSNeWi3tM=,tag:zHNHZr5zjo3FmAVJXze1hg==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:dkR6aGCrTjmy,iv:3oyOS7B0MrXPfYbIW0FNzGjXOONt2/SR5+CmmgJrhBQ=,tag:UoQG54uH6fEn8ubuQC/DGw==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:mW4cHakEYwEaXrsvkkrAHxU=,iv:KeCHFwlcWRbLgCpV4O5jz/SWpz9Z9WzJOYg6OEhbjO8=,tag:K0ZwTEBnZ9MzIEKPYokSfw==,type:str]
    AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:/51JM2wu8hEEwp6urlwnStV88w==,iv:cwYnGqTj0h0ZIGYRMqN1Rd3DuaASTG+rGhNUaWVOOfA=,tag:brfOrMFLGehptEEGE3Y4Tw==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:w4T2IzKsyhrIOXrT9Vzo/49T3vIYHKwO5UxkzmIvgzAd5XHh/Od4lp8HHG8fqq609jVCmnnyNcFItEwt7TypYUr/hj23PIXzMS92L8SUXQxeCjv7GDa5Tpy0vZBylg3M/ePxf5HTpnOMY2PTdIJE6nZcFglgjeKD8BilDsTNq4E=,iv:3c1AabROVCgiAd6vugjnAO5RgyHecbkMeqZKKComZN8=,tag:hC1Q1q3K8BWUefl8iwjG6A==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:r+10se9OEEWPRF4+MPMEq55YE20k8TGUq3eNmOw7XTrTt7VGgZrF0IFQhwzcG6oQEqT62HvWly/RHpVta0AS2TWTkDGq0SjhWWJWKE1jh1c=,iv:Odji8ktb580ivlXhpbe4NbfRKXUNM0NAVumJkJK+R5c=,tag:JewhogXQwjUkiYhXFe0c8A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1Ujc0T0s3NWYrN25uamF2
            eVFZVlJJbVJyWFRId3pid2FuY3RhMjRVMDBBCjA4d1NCTzFnVlJNcDJSVStldStO
            N216ZyttQUVGVkszeW5tTDd0Zm16d0EKLS0tIG9jYWhtTGxLa2QxZklJVzFuMlVB
            bnhxbFNwMEVZVXZXcWNtakVxVlR2VzAK+V9t/QhF8BXJbDFl6Tnf/Dz3jps2qy4E
            co0eDOimx2LrBdR/3JANhFFlIxa8FXo2nc9wbtG2bw8BhOP23ITZYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T08:58:31Z"
    mac: ENC[AES256_GCM,data:SwF885u3yrlItBP1X43vWojWXaq543wKQ3oso2vAXX7GiLDDvyPfLWAeTJqqT4qQIzGQMtpHi+IdmLMktZXF+oDSeZct+m5ZBpWER2+wAj0OjS2mu4oMGMIJV2gutKJNc5NuYrlG1J5U+82dlsaQFXWu2M9QmFCOkB14j17sAPk=,iv:TuFo73Ri/14bvK3kLM1m+XiTEZh8kfGtZewzAc/YUp0=,tag:GEwZfucbSZrhgImpbqVLqw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
