apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:31q8AXu5WDmnGQ8VQCI6GXIjIXAH7nXKy6MJNm2raDFaTecBOCgl5/hYx1Tsi3OhkPz2txZ4PW3s2rfrQassgVrQ+2nPRn2RIS8dFFmlbmZvMaI+3ZaUlZjoaJVFPckZtdaX1oI7KJrsOHLkcTIm5G/CZxjzQjRmpSqFK0A963Q=,iv:Hme7eeIxeY/hqJWLf4hXivixn7Vq1hw7//R9n9VTECI=,tag:6TBuY2ZFui/lyFucu4w9qA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:CRUp6Fn+684SO4/wLwj0njztle3vRSqCnqR73q4CRRb8564IDVxjtNw/+NHqg8FkdFiE3nNS8TA8IC/mLXILyLMDb83XG6aLlLdIL+iddYfRgqyAPRIm0/KnKQ7YHMX9HhgfPoQfYyFMoziBeKxl5uLk56C8k1qMf6PFkPtOjuRULjwUOhJ1NdszkvD6lOuYbdjwcCpnI5Ddqb6GLMVTcIpCJu+uBpTtiqNKJwTVqfv3uVTV5TzRDf4zSiri081ZzUSc3XV9LI0iaETxJGx2or9pPv9Vt8qY,iv:bjdNT/ELXNDYDyEsLd5RmKXlhn4eJf59xLIrFbYH0/Q=,tag:WjgrmgIsOoJBSq2FTaqQ6A==,type:str]
    #ENC[AES256_GCM,data:zL0GhnnTuowp3sD5AAI=,iv:pxDKjvHJaSF3o1z3Ew0cewoSlvZnjsHpXgUra/vET+M=,tag:ZHSQPkuKaU3++Nzh9+i+Nw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:1gzGJWMg7Yk1,iv:dcWsmafFAAmoYZVf2Ogd4XLfXB0yXyAI4rJiDANEnWc=,tag:jfVgBgV1UudKRpx2zYkf3Q==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:eOZjMFWzLfEyILzIcpeqjk0dLD4aNWmzdGGxRwrFyK6ZrvCCW8BBxg==,iv:E28wmHXizxj5QoVSdUhCKRQ8pLIvs4A4IuaA1z+qReQ=,tag:PWPK58CfUPYS0HStTB3lbA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:VeoViLts+njKbpOmqO1alVg=,iv:53TU4lwJAI7JjVNU8DgDLRmSNXTK5ssausnSX7MpDbY=,tag:5TG2Fra0gRr0TkmXo36Pfg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Oi8RQuXSNhO0py5Lnb5GsYYVEO3us3vTdvFuSIGaO2MiJB2lpHxmzIvzH/SIMNOm+flZTIoOPqL+peJMYVhcujRz6+2AQrCse0eG2ep0VqdjA7h/xgZ0r3e1tOSav2WqBBpk89yNafd2hsBsedRK/oe9QScHN5X3+0iYalcxd9E=,iv:Ikt6bTlcjaKue3SLynm2EEj002UTCD/NwZukV6d0kFY=,tag:Q3KB3VFlCtXEIzkL2orNlA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:xFrkU7Vr4RoI4CoMB9tjKvnvX3N6I8aCXIPLZVFnd9R1lple4A7Q3onhLQu+ceFySEMgW7ho6opgE1m1gAxDCI3JA7hvjvO1cqlqhJ5K/x+ro+1yLxITbLWbKnV8YKXyghztBdkj7+YxtfekK+f3vmvxcl2RsS4I3MRnXGbUoYE=,iv:f+1byp5jaGW8JMRORdRcvzQPIe1s4oX7Ve2HGzu1rfQ=,tag:zrAWmIuLljZGZ3LNoAEV3A==,type:str]
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:noy9GYEH/FZvjz5HNyN87FlQ4CpLLoXElBSQgke6MLVjBBWXJ28LHD7cKFd5kfC/heY0Jw6EcE6jnn7ErqZofhT/ALY8A8uZuxuBlTzMCy8=,iv:fo4E2Ew95OCD//DvZsf3qze6Y0N0rH2psA0iplRzYe0=,tag:TovbNHm+tr6BXmUy5rJUug==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVTlLYVg2UUF5OFpVc2Jw
            ZklzaWpzSDZFUXUrR09qS1pQV1dydElOS0c4CnVHbzNSWllzZ1pibzZVQUF2QkhT
            YnFPbVFnN1NUSWQxa0x1Qk1mZHMxM1EKLS0tIFNXYldIYVlPbzV6Q0hFSnpDT2ZB
            a2FsL1BSK3FlWFZiQW1rN2lySVpRbzQKPMhmmQkp5BELd5/UYupPumlmlEJrkP4P
            Is4bDa1sH8E3R906UmfaCrEsILQl9IcldYAyKRpS4AhMo91NZgFPlw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T11:59:12Z"
    mac: ENC[AES256_GCM,data:22M1y2o12josIkvYveEIOcTGBOkuK1DRKJmYeQ9JhKT47kz28kBMGNzHgpHQJ8wPrYB+UaiAmYV2944K3KIE5ly8n+1xED8/laDYyo6jiIJHjCBLiflrfE2A0rSX3l8WRbyPYD9ymjF3XY9EqF31w3Uw75eqhvazpb2wrdQfIfk=,iv:gPNUc6iOcd4ix2AuMqTj0UazyLrI6+DYJrLc7BXr+4c=,tag:64fu0cc4eR8gCaUnG/pd4g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
