---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thelounge
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: thelounge-dst
  resources:
    requests:
      storage: 40Gi
  storageClassName: ceph-block