---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/refs/heads/master/v1.34.0/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volsync.io/backup: "true"
  annotations:
    volsync.io/cache-capacity: "10Gi"
  name: thelounge
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: thelounge-dst
  resources:
    requests:
      storage: 40Gi
  storageClassName: ceph-block
