---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atuin
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: atuin-dst
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
