---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: atuin
spec:
  accessModes:
    - ${VOLSYNC_ACCESSMODES:=ReadWriteOnce}
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: atuin-dst
  resources:
    requests:
      storage: ${VOLSYNC_CAPACITY:=5Gi}
  storageClassName: ${VOLSYNC_STORAGECLASS:=ceph-block}