apiVersion: v1
kind: Secret
metadata:
    name: synapse-secret
stringData:
    #ENC[AES256_GCM,data:GX2vhhLx3bjqjgu8DsQ=,iv:K6oENq7WB22alGYLoDHoDuHAzaz2lvaf9tDu7v1H4qE=,tag:aVGIOoFfWiqmUSNBUIC4uQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:9G+YUD7kAQ==,iv:npeecujuu/t/8/27TtnfqMo/q5FaQRIQGkdYTHVo2ig=,tag:c1F8npQjo5ieZy1rc+lB4Q==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:C0HWEJ8/yIXQghkZKsMOCCGlo8Age6mA+FnpIott0qH8KREw+RqorA==,iv:EQB8Cx4CIuhbKckkHYsJHWVZ/HTTrc64bKcKG4ke/uc=,tag:sLW+IDCZ51pKso8NsK4jgw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:BuiGWm6Q6X1sDbjt6oBp,iv:qJPnDBo6geaSwwUNjoQhnzswxjv7m4NZwkuRo4KKEKc=,tag:8gvNzhWr0+IFFxmQQEgWEQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Jrj2/aPvDz350VhBJXdDEqGUK7XvpzUV07eReQWpdCmRx+km0M7kFCRYiEq/sga/PLPkkywAvx/jhe1eb0UYwQh5vlSyLojIy0CpHr3lwpQhPy2Idvxe5BKZNoodquTcgd4TtYTXeMInkJEzJHXN3UPvj9hQabX3bt5c+k7PnPI=,iv:oECDNsJk4W3D5APr/UTPwkKeRA8OPOSzEvkAmawUtdg=,tag:AaXttYDydK5qc3vmgV1FBw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:wb5UWmI8UYSAAx5CLXIf6g9rb+r94T6M9mWPY4EfL21m0iA/0VLTPHbYMXPTkLL07j/MBKshBaKdg8v6Ca2SAF6E3KXc5BTOFq9BgfYp3W+fkgpSz43jBuHdtjJkYhNA9T/1eXhoy1b6df6AuEalj/0iUWME9GEO/XNTosb6qxY=,iv:iP2p20v7Nxow6fSC0KCDJAYZ6PVDjfDP9UJFucHqT+A=,tag:0+TndJQPdioyTWi8jiR9Mg==,type:str]
    SIGNING_KEY: ENC[AES256_GCM,data:51lsCQCzzg5urN+88eYyW0Y+OV1ZrxVl14fTO4shke2Ivr18kVTMe5P9ESVrQsmspAfSQanplNDfZw==,iv:C2f+QjuU3RI+9e/x9zhsvLLpyhlDVknebj7Gx7tA5dQ=,tag:d2s2GimQOmTv1xrFMo/TYg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYk1uTHRTSlBPVVRqN1JL
            K0J3WVdVYzJSRjRvNXdSOURveUpVb3ZDMFdNCjJEN05iMTB1V1BjMUYzLzBNWjVy
            UUMrNUlUUUN1ZGJOdGpXTWFRZ1NnSzgKLS0tIG82eUFCTjR2TGNDbE8rOVAvdVJk
            azU4YmRSZ0pzYXdYTGJoTW9oMnJSTkkKeC50h9ch2lasv50CIRNGvNrrFUfR7h0R
            sIQwRVzLb+Ucj2gthd6cQDcoRFePNhzNI13aXVVSdC7oUvXc4dJNDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T00:38:00Z"
    mac: ENC[AES256_GCM,data:q02CjAswlKHHd/GaNj7M9Jx2UIcEOsahncGYQHARI6Zu6Ih4/VtUCdCkkPCdASUARW6eH1zCiqp44KToqkRQuJOCfWFVWCohT97K0Y1ZVFJxwezintiAjvRaBsT7EJf8voqhxl2aKItybvu/RJJTNIUKmaIh9ynGiZu+WgFns+A=,iv:0iNX+IGxgj1Mt9IR236Jx5tbhzhCCTWkV7/41MvJVTI=,tag:XE2+L6BTNga3ZfIWs6hTaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
