apiVersion: v1
kind: Secret
metadata:
    name: synapse-secret
stringData:
    #ENC[AES256_GCM,data:vOsx2KL8eiqOUWW3YQg=,iv:59G5jgwS+Ooj6OCpfTpS44P4zeEOsRd+MTQ7DpCJGuA=,tag:W/S+eEvNgj8+ujBfwg8yog==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:tU73txOMUg==,iv:hnvnbzw+TFu8DHjSO1qFbSeTPxApy/NbYsHUDj1aT7g=,tag:lexskRV2E6loCjItIe1/UA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:xYhZ27/tj/dE1iBnSORHLGMNZdCidy1MIMdb8+HDr4h1oyG3lelO5g==,iv:j7wGdmuVAzUS5Qm7mRu9i7IAyv/puCT5OCBV4V7ofwA=,tag:WSN0Z40JultrV74LzMS+og==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:qG44vX0TdVFHvc6Qu1U6,iv:OIKR5W+Y5car+JigwRFzm8LKsg/qgg6zptmYtsejK7c=,tag:N6TqV38wJj8OU7a/+1n1sg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ESpAWlq/mX6Igz3QrrKf/BnzCuumOOuWdd5lC/YnrvX1KejTmAUlLcspvCbKDm17igLJXTAONs1ez2XApgtvuy/4WeKFsBpNJNd0OxdfUjdTyStZw0/bH4Znjnq7wXYpmRN9oShF9/YuUkMnoWKSfC5BXPuNFSxg14ES+Aw6szo=,iv:6/7dEcyhWd/5A8zD5O7cwRKxM0O45/X/Lrs50sJVe/4=,tag:+rjXLWpS79F6LgaXhEIPHw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:iRtyE16MdrCeJgZc9ktXnaFLZarfA5vdTJIWNtwgk2k8+TkNPvWmlyAnStfz3pw2ffi9jIC4V5Mgn+XACbyNUcZTGDylk9tgy9+IwCBIn0IvipZFvE5Gx+tR3gORswQzZammCB2jYOGM9O3An2HoHX2Tbfud1EQveRxleUnA/N4=,iv:NOhh1Hwixz9q7wdDHS2ehkOEtjOXP3u7RSFmD/9Ha+Q=,tag:Z0cx+bdOz7FEPBQ0JG+zUw==,type:str]
    signing.key: ENC[AES256_GCM,data:HvbIoHNLzrcH2r8IlOXCDM1RhVn7PzCkt4pk+ffbeQus48QVV7idrCUIZrwqi4y6g/rbqliCBj+MpA==,iv:zeH4oowumccbF2HR11FOi8YIPniFswDYVSHP1f2ApaY=,tag:BdITi0bnE5zsEZXalxdMAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdklWSnF3RzR1dGxsMThM
            QWs1WlloS05rbmU2WEVnc3p2bUI1WkhkS0RrCk41cUdDNVJkMFVBRUMxUzZZSjZt
            L25pcGdCcDhwa09NSXVQVmNkWXZwR1UKLS0tIFZYbURSNVF4ZWUzcmErYkV6RDRK
            QnJwVzc4L2R4WStkTFhWaWhkVWI3WVkKUi7a2bp2PatrePpdvDHi/kfTmg58+Qcn
            SiFLSZF+ppU1s8dsqJKNrkkv8ESh2TZMLjLJnO9JMrw1P15IcV7m+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T10:40:11Z"
    mac: ENC[AES256_GCM,data:q1v0MMqXpmgChHQNGIaYGDH4bKvL5YVHCol6+BHLIZAA+vecC0ts4VJfGWCGFE8Lv0QNimOD3maly/OcjHyzWYwSIr+BlFBcah8tx3WqPzWETnmFoBRQPNe5K9I1Zdns5nv5wuHl/awKVyam0t3+mxPqN1WJpmFHr2jOkTUC8UQ=,iv:+c6QaWOIRhRZtTKGQ2PjUqDQwpyG27OWnBnpyhN1k4I=,tag:8IwzEG5XxKQaZEW34nNSCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: synapse-authentik-secret
stringData:
    key: ENC[AES256_GCM,data:L4cDT3JHrD0udSlgbXjqnuwkWtNbiMEKvKL2wSRWa2ahGUNZYwBbmA==,iv:HkTu6p+23E0K2S28ZQeyX3KRPZwmFh0n68ptH9pDDPY=,tag:r1aig4uY7sLOG8q2PkHxug==,type:str]
    secret: ENC[AES256_GCM,data:iWfE6/Tm6obmNuT1ImhPlELckzzKPqpyljscc3iR4Sh8Eht5rtahL2zCLHXWckizK1hgOGGaUbgNlwYAzMXH2bO3TRym0xAQqKbfoPB6u751et/jHKs5JwZVd2mPVWqNSUi9fVKwnmWmH5gm/PuCiSztyG+IxX1lYNjKvWa/dx4=,iv:k5X2rTfw0798h621FqBU8/sdVy9mftatSLih56tnOVY=,tag:8RRO4shNqnxrNpCSfmvtyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdklWSnF3RzR1dGxsMThM
            QWs1WlloS05rbmU2WEVnc3p2bUI1WkhkS0RrCk41cUdDNVJkMFVBRUMxUzZZSjZt
            L25pcGdCcDhwa09NSXVQVmNkWXZwR1UKLS0tIFZYbURSNVF4ZWUzcmErYkV6RDRK
            QnJwVzc4L2R4WStkTFhWaWhkVWI3WVkKUi7a2bp2PatrePpdvDHi/kfTmg58+Qcn
            SiFLSZF+ppU1s8dsqJKNrkkv8ESh2TZMLjLJnO9JMrw1P15IcV7m+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T10:40:11Z"
    mac: ENC[AES256_GCM,data:q1v0MMqXpmgChHQNGIaYGDH4bKvL5YVHCol6+BHLIZAA+vecC0ts4VJfGWCGFE8Lv0QNimOD3maly/OcjHyzWYwSIr+BlFBcah8tx3WqPzWETnmFoBRQPNe5K9I1Zdns5nv5wuHl/awKVyam0t3+mxPqN1WJpmFHr2jOkTUC8UQ=,iv:+c6QaWOIRhRZtTKGQ2PjUqDQwpyG27OWnBnpyhN1k4I=,tag:8IwzEG5XxKQaZEW34nNSCw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
