apiVersion: v1
kind: Secret
metadata:
    name: synapse-secret
stringData:
    #ENC[AES256_GCM,data:vOsx2KL8eiqOUWW3YQg=,iv:59G5jgwS+Ooj6OCpfTpS44P4zeEOsRd+MTQ7DpCJGuA=,tag:W/S+eEvNgj8+ujBfwg8yog==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:tU73txOMUg==,iv:hnvnbzw+TFu8DHjSO1qFbSeTPxApy/NbYsHUDj1aT7g=,tag:lexskRV2E6loCjItIe1/UA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:xYhZ27/tj/dE1iBnSORHLGMNZdCidy1MIMdb8+HDr4h1oyG3lelO5g==,iv:j7wGdmuVAzUS5Qm7mRu9i7IAyv/puCT5OCBV4V7ofwA=,tag:WSN0Z40JultrV74LzMS+og==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:qG44vX0TdVFHvc6Qu1U6,iv:OIKR5W+Y5car+JigwRFzm8LKsg/qgg6zptmYtsejK7c=,tag:N6TqV38wJj8OU7a/+1n1sg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ESpAWlq/mX6Igz3QrrKf/BnzCuumOOuWdd5lC/YnrvX1KejTmAUlLcspvCbKDm17igLJXTAONs1ez2XApgtvuy/4WeKFsBpNJNd0OxdfUjdTyStZw0/bH4Znjnq7wXYpmRN9oShF9/YuUkMnoWKSfC5BXPuNFSxg14ES+Aw6szo=,iv:6/7dEcyhWd/5A8zD5O7cwRKxM0O45/X/Lrs50sJVe/4=,tag:+rjXLWpS79F6LgaXhEIPHw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:iRtyE16MdrCeJgZc9ktXnaFLZarfA5vdTJIWNtwgk2k8+TkNPvWmlyAnStfz3pw2ffi9jIC4V5Mgn+XACbyNUcZTGDylk9tgy9+IwCBIn0IvipZFvE5Gx+tR3gORswQzZammCB2jYOGM9O3An2HoHX2Tbfud1EQveRxleUnA/N4=,iv:NOhh1Hwixz9q7wdDHS2ehkOEtjOXP3u7RSFmD/9Ha+Q=,tag:Z0cx+bdOz7FEPBQ0JG+zUw==,type:str]
    signing.key: ENC[AES256_GCM,data:HvbIoHNLzrcH2r8IlOXCDM1RhVn7PzCkt4pk+ffbeQus48QVV7idrCUIZrwqi4y6g/rbqliCBj+MpA==,iv:zeH4oowumccbF2HR11FOi8YIPniFswDYVSHP1f2ApaY=,tag:BdITi0bnE5zsEZXalxdMAw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzdklWSnF3RzR1dGxsMThM
            QWs1WlloS05rbmU2WEVnc3p2bUI1WkhkS0RrCk41cUdDNVJkMFVBRUMxUzZZSjZt
            L25pcGdCcDhwa09NSXVQVmNkWXZwR1UKLS0tIFZYbURSNVF4ZWUzcmErYkV6RDRK
            QnJwVzc4L2R4WStkTFhWaWhkVWI3WVkKUi7a2bp2PatrePpdvDHi/kfTmg58+Qcn
            SiFLSZF+ppU1s8dsqJKNrkkv8ESh2TZMLjLJnO9JMrw1P15IcV7m+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T00:56:38Z"
    mac: ENC[AES256_GCM,data:b3p8Oz80DEDJcPgsv7wTm4vT3cnA3eoEyJhJ1VB6SnK7BYUBhHwzDs9i2X7/iy1WGNDpViS2BLgVPgZYVjCRTtbl/Ei7B5CLv9UwoM9cNmJNJ5+sGXxtzLHe7QLvAFUqcydfwz96Rtiu7OrLAe4EPm4AIYxt23YXwK/d/1xavzY=,iv:upaH5q4FmmajzShtNf/sz9yovvvzKmEAfPOM24vec6A=,tag:lEwvtOJjvxkr7YU+059VqA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
