apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:Y7bLcypoD4hr,iv:24fB+oa0o2iP+RTEdGucdtdTj12IKj/qhEgHC4Pe0/M=,tag:Suzi1QXuobAodliuxIevug==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:PF4mFda7zYutYrL7oZQG9aAywnF75NvybS9gUwQfoxM=,iv:SI6WYXSQT+HBiekLxQYDhmZ2+8/MhDt1Xls10TVdNY0=,tag:8t2rf5ms88+dRLOcLwjBHQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YW5pdWxiRVRnenYzNjRl
            WjBURStadFMwekoyZ05NTm9nVVQyVGg1SzBjCmFISWNhakYxRWh0MENBem45ZVFF
            NVJjelBvUHZmMEd4QUZSTzJobWpucVEKLS0tIGNocE9JYlFITzRqeEtuZFdHMEQy
            WDV3T3ZpUm96VnlOdjdNcGZyQlNsbXcK2aaW6TZO/gOas3FVDJOdhvLBLBP3c0ri
            3A5yejxH9z/s/9W5g7DKUxa/BGB2pleYtkrpPypcRmBGVDcCH6SoIQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-08T06:04:54Z"
    mac: ENC[AES256_GCM,data:87frre2ry0f/TeSxukJ+eiBtzbzX1+z0lIRzKC+LzIAmxcCsR12+EZgF99PQXnbfnFM8PrBrTcZp2VxOUiBX6eitF6KCAhcICOp5Wn1X6p3Pf8KknNHibX1IjRb3ATwRIR5MdF6S7I3iZ1w4n+jsjoKYJ4gLMdZmFFN8VHwvzAU=,iv:eJAQRudDZb+cQbo0c80IZlbgACjhkaov8vxr3n8pSaw=,tag:mhCRp3uMYXUFxyUZCnD7JQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
