apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:2/h5QbVwJb7v,iv:DTEKslcza7N0ACRHuzGvMYKxhxXJaqKH9TJcjQ+7cwQ=,tag:DeQ0XQR540SHtNfJ5JPalQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:/i01Cn95Hy4GZ9879HWaIBOKyLFsYbQmgEc2BWPuUzY=,iv:5tvmPZCblHwSj/nxQyiF0RYUlkjeZxIxmluhOMT0pss=,tag:4qriUGEnIY2gz1cN044R4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoa2g2Z0ZrVzFSS2VBS1No
            TWJaemdtYzFxM29jbVBObXZUTHdBL2ZNa1VVCmtiSCtRMll6L3FZZ1U5OFpYSXV3
            a2o5ZXpKY2NPV05TK0daWnB4bFdFVEkKLS0tIDJFWUp0aGxoZlV5OGFSSU1jZFYr
            aHlQd2RFVWhYc3pHRE1MQUdwQ054M0UKUmwimrFvNlGL26cJvmNiohw8f8yoDn//
            76zurI21DgO+07oRd3yh5MKWoZNOpJz5ZJaV8AbNHUsU4Jkbh8y9iQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T05:17:58Z"
    mac: ENC[AES256_GCM,data:cqR5+Uxs6PB6b18/ubC1NtMbpgfv60TqflSVABQnVExD1Bfx8Rq6IGChNd50J6FiVni1kXygyNku4Baa5ilLOWMUS90wYgkCm//mhPsdT2WEVHOltJrK4H5lf1A1bHWsVhILunFSRfAL3Oq0P0zK2opRrBPfHsksbqseV9KWS7c=,iv:RFSUGupP9teycX02jzO5nWay9zrvwxFnKn1NwHvtzgs=,tag:bo2GDiJlzmZcD9VIGS3sJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
