# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:dp+cNCiFWP4s5IOVXMmMiZy/QhcYWGCO5rlyHa8zJaM=,iv:Dc4NOW3oWYVY41zvxm8MFmZQGZiS337BXaNdjU6E+LE=,tag:yrx5qbt5hi5T84rtbpcS4g==,type:str]
sops:
  age:
    - recipient: age1pk4hw4gdplvq3tz6ma96hx3ja4w303ld5n5x82yqzyhj4g45qadqq9nf4n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0MlpMaEdZbUNpc1pMV1Nt
        MkJVSmNCRDE5QUpQalpzN2pnY3Z4WjNLbXd3CnhUS3c4bWhMenlSYWR1SG5QV3Z0
        cDFKOEh3MzFnT3NCelRxakhxOUh6MmcKLS0tIDVGVzNYN3RzYkFQZ1NHMEs2TkFq
        YWRzWGVSdzBrMWVzRTVLZndZVEZKcFUKsPxzp307XaT9vO+q7wT7/RD0fTN8bOYS
        GDm3eBQDX5JQ+Do3SQga3NxuAUT4R/W62h57lGyheSgIN0oGrqpXgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-25T11:44:32Z"
  mac: ENC[AES256_GCM,data:4fkmbXiw4VPR/yeEw3kHXeOzs/LZOmXXuH0wslbGC9lP5WvG2UjGqpFTAshbd23c3Cna75bmuVF4/DtNX2eAaDkN7ebtLwNlmv0Y8ThqP+NxDIEZHBhWuXxnsNxJUJbInow5xwmBR6pZnVpWznf1WAC/Bz+TjLUBLlkvw33zRzY=,iv:Wycf1Q2h9/oEJjQ35Rv7nGWWRWY2VI8qlZ8VtyIjKdQ=,tag:9wGlczoVoFnPZI/s1oNNHg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
