---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  data:
  - secretKey: github-privateKey
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /argocd/github-app-private-key
  - secretKey: github-appId
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /argocd/github-app-id
  - secretKey: github-installationId
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /argocd/github-app-installation-id
