---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: mimir
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    type: prometheus
    name: Mimir
    access: proxy
    isDefault: true
    url: http://mimir-gateway.observability.svc.cluster.local/prometheus
    jsonData:
      prometheusType: Mimir
      httpMethod: POST
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanadatasource_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: alertmanager
  namespace: observability
spec:
  instanceSelector:
    matchLabels:
      grafana.internal/instance: grafana
  datasource:
    type: alertmanager
    name: Alertmanager
    access: proxy
    url: http://mimir-gateway.observability.svc.cluster.local/alertmanager
    jsonData:
      implementation: mimir
