---
apiVersion: batch/v1
kind: Job
metadata:
  name: forgejo-init-db
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init-db
          image: ghcr.io/onedr0p/postgres-init:16.8@sha256:7c339ac0b2eb88ab41878ac3a71d342343fe7e830b7ccd2adb6c7b5bbee8d66b
          envFrom:
            - secretRef:
                name: forgejo-db-secret
