apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:uC16+Et0Lg==,iv:dTp4lEEOQaeTm7drduZiQ3k3sBO3bzuHfASRylPXOew=,tag:B0zzSWMo8thbkD3gTj3rmQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:8b+f0+5skCrGGoEuH+hqFvVTgqPLimmLdyhQeuOYiQ+71eOFLf+M+w==,iv:pZiXy3kKH40PoIuov1vB+lJPkFiLi1bfLbuSPeCTOsk=,tag:epGVcZkh9veL/B4uzmlsLg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:PAYW0gzSmtKy0yYZayXv,iv:1q97o9iOia0dBlAByifawEAeO2edhobVzt9tYzyI3to=,tag:ZA7KaewZ4MBV4VN7tFqAZQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:qjVsHzsRkmfkV5Do231xP3dC9tF5PBoaxn7sBDfPnL7Or5/oUJap6SZszA8p3TCp0n0IzLZbe78y1cLflbwvTYixaoN9MhVDaBa73NTkjIUQGEIEw6LXhsr3v+qG9tGC5SGZNxdlXsPU/B6F8WbZyozLkn0ZeqoY5v0S++PGtrc=,iv:itPeUf7Fu9NzJ9TjRSeUa29uD3ROp2RevTE9bPzOYHU=,tag:4wxc68ONT0vE3t1e7dWeJw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:2Y5OwyAIMMx++jiVYwvpUHXjhjZB/WFR+hpNgwdHhGbn/E2fy+Yt7y2OiYsbXkbsgRfp5owO5cjZe9y+lPf4lNAw5qEClG2WtVVdRQlVmUDAgT168nMrWUKcWnEjZWhM1WOqcnzOepI+5mcw2ronYRLSc63DaKhZRLgTfc3szhE=,iv:tMp3ee77VDpxUhayWovLJdAiCaecOSCyJKOIaTHoWuw=,tag:Usuj2poKwcxuIAZ4f4h/Pg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUUW5Xd056RjFXcm5rZFV5
            SThkVyt2SGtvUGVPc2tOaDJVOTNScGg0eGk0CnF3cXA4S1lUSmV4U0dDRTh2Y0Qr
            Wm9GbGRvYUgzTkFORGV5ejV6RjVnZkkKLS0tIHRRV3pyeVRnbkpXYXpxTFV5V25X
            aVZ5cUhlZnJNYnhKWHBKSG80UDJKd2cKxiMBQ405udSYDmglfmPaIw4nzK5opCos
            dK8vXtv5l49dtQcXhICLakcXxa6fZs8eeh2QUiuDXPVMF+MN6pi8Ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T12:55:00Z"
    mac: ENC[AES256_GCM,data:uMXFzmtS9jeoRITKb92J8wdhVZu7VdTtMUZb4FcT0NSn0LsgP0vBPSS8uK3ynr3HeWz4zpeN2OCRhc8ZutMfJ4aBR7HtOkeashCNAkaeh2+FSuo0nhPoJivdBd9j656HKwe3xNAuo+7OLz9L041uT3rG4+i0YpFJA0U3VYU6s80=,iv:95RuhByQA7MhaKtwzfa9od8ZmSNAM0vLEZgVqFrHpO4=,tag:s6RgRFiblAKZCM6J2NqpDA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
