apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:JAdCYdc=,iv:k6s3F+X+wBKJZjz3muJ2uHYvAUf844bObgBvF5LoDRI=,tag:vjfD7tI+aNLgwKbgjNboZw==,type:str]
    admin-password: ENC[AES256_GCM,data:aAVvfdtZAOeWxDvne4M=,iv:NMpyRrlJtGMKrFh6ZwxI7SW9WnANzvDfJ/04XB+M/6w=,tag:caJAm8aU5uRVByVXtrCvjw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQODhpRzdqOWJOZ0craEd1
            NjBscGpnTER5K0VSd0VTSEt0WFJzdEZUbEZjCnB1WnBJL1JVcTl6aTQ1eVJYaWlz
            MTZwNEN0aEtZMTBVSVFnNFRZd2R2SUEKLS0tIFJ5OVpEZ1E4akR4ZTFBS3prU3VY
            UDZYTXZ0cW1KbDBSekpnd3pseVRpSEkKHKEziIk5SckBbQdhr5MyRBdYbgiK/RUZ
            gjcK245bGZhH405N9DFMw0npaxFxh0tTKuRlcfsxNvNuLuP3gvQM/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T06:55:08Z"
    mac: ENC[AES256_GCM,data:2W/nO6UIK5rhITlzmnBvnOCIJUhh9Sltet7ikWKAztoiOcXQp0tz+LLDP0MBLY6YxKy5Kq3/XItNxFHYS1aGgUYugxcQP9H6h3696IIXu6WQ1Yr7bLhg/X6bpwnxVhBEYbU9Z2UmxOGE1H423yrXVOVqS89JDUPWIYll5fCg+Kc=,iv:0RNBaGotuKWC3vDkLJXCL+vdrNK8CY0YT3zUeyE1gtA=,tag:k8VRGk0D2vkwIRPJ91oB1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-authentik-secret
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:eK7J51A5rLfJKLdABbvg+I/9u16Rsoif3NlNhfdobcmS/yjtm2gesw==,iv:WIyG881cowOUUset5+kL2CYpbxF+SIxNbSwL3ptdmjQ=,tag:yoKcSJLBGxRhY2tZaDNawA==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:Z6W0fIxPLE/8pW1QxYrtYxIu6M7Na80VrmrrpgxcYTPqcVBIzRnd47EOPHdFJsFRCxLNCXvRGK7xaHkkvH8ueYhfRXj+2j0bQLlSPIKUE66wXKQx42Dwulp7YHS+hWhW3oxSC1aEurunmDfEbN1fpX1+inMkdtgtAoYoKFe7+08=,iv:Rk3p695/lm6xVAHKSmkmBFPFxy6z3BoNNKTiVCy18do=,tag:pjp3AhSEMe8tS/kZQs9BdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQODhpRzdqOWJOZ0craEd1
            NjBscGpnTER5K0VSd0VTSEt0WFJzdEZUbEZjCnB1WnBJL1JVcTl6aTQ1eVJYaWlz
            MTZwNEN0aEtZMTBVSVFnNFRZd2R2SUEKLS0tIFJ5OVpEZ1E4akR4ZTFBS3prU3VY
            UDZYTXZ0cW1KbDBSekpnd3pseVRpSEkKHKEziIk5SckBbQdhr5MyRBdYbgiK/RUZ
            gjcK245bGZhH405N9DFMw0npaxFxh0tTKuRlcfsxNvNuLuP3gvQM/g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T06:55:08Z"
    mac: ENC[AES256_GCM,data:2W/nO6UIK5rhITlzmnBvnOCIJUhh9Sltet7ikWKAztoiOcXQp0tz+LLDP0MBLY6YxKy5Kq3/XItNxFHYS1aGgUYugxcQP9H6h3696IIXu6WQ1Yr7bLhg/X6bpwnxVhBEYbU9Z2UmxOGE1H423yrXVOVqS89JDUPWIYll5fCg+Kc=,iv:0RNBaGotuKWC3vDkLJXCL+vdrNK8CY0YT3zUeyE1gtA=,tag:k8VRGk0D2vkwIRPJ91oB1A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
