apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:/Liu8tU=,iv:mbFaIo8nat47jAdKQvRiECuN7POlyU8WgUE/O4XxqjU=,tag:O4vXBrB9YLm301WRtpOG0A==,type:str]
    admin-password: ENC[AES256_GCM,data:gv5bRGVXymnZeid4nm4=,iv:RbjaKGZyoFRpWxwshl2FGdcNQ2VLku2OcVjC8iOca1M=,tag:k+CicRGXz7iwP2Pm2iWgFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOEVidDA3R2pCUkVNUkQ1
            eFhPNGRNZGZ0cTl1cGd0bHJpTTdrVzJSZEZ3CmcvUnQ5U2dKR0lJU1NrUkxsM3Jh
            dUR3aUNML0R4bm1ITi9UYnFjQ3M1a2sKLS0tIHU2SnBsMWJLSS9XUkRrelMvM0xa
            RjFoMWwzd1NCTURuUmF3TjNMejNZS1kKnezhyJ6iQaKkbKD0wB45Xu5W5cnimffj
            l615mHKZOB2R7tb5miq9pzj95YJZMNZ0FhYfCl0mw1ZBJQ5+smQM+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T11:51:30Z"
    mac: ENC[AES256_GCM,data:FVz/31juI5x1dycW7APuYVb2NnEnpem17UGtTRdfljaEH6Qr9zXGrlhq8dkWNsqXhZlDdejwOqQjcy9yrvl3DA3Ok6YV6MfWM8izgLSpdjoLQRN5EJy0R6ChZUvrVYZ1JU9dxey4tuHLj7iov5po7r8ZSu52bfMqgmnIIA79ow8=,iv:UYQUpZ+cfzgjK3qGOZqcByd9q7TjoQpt9pzlVN2LoXo=,tag:d9h0cxLHcHXBTSofzxo19Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-authentik-secret
stringData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_ID: ENC[AES256_GCM,data:Un/Rug44KFoF4siGgJZUPfe6NZAsKpOhdgYPavZ0Viw51iVF3MlmCQ==,iv:31uUdmhjrCUif2rrVd1PozL4dN0WeiuJEkCxVs0EyfM=,tag:Biw3nmEQ1cm3tzLqOKkjpw==,type:str]
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: ENC[AES256_GCM,data:qa74a6vuO+SV0gHYyFLfK1xZ/r/rAHjV8NzkCGLjCFTiTHkerfwEtBNuuThYMZc9nKR/0FoJVUE7g3HJgYLqB7EO6pETB+mbQRd9T2HYfB2rXcNxbDJJvriA/yfIkbyZstd9bk9JaXrtQ2rcymkzhnGHklEt7ibOLuotc3olLWg=,iv:NqkzRQizB/tvOHo7pWAuHDN6aS7O3iDw2JO56BbSxbo=,tag:Qj4xIj89ESsueY0PgLMJew==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOEVidDA3R2pCUkVNUkQ1
            eFhPNGRNZGZ0cTl1cGd0bHJpTTdrVzJSZEZ3CmcvUnQ5U2dKR0lJU1NrUkxsM3Jh
            dUR3aUNML0R4bm1ITi9UYnFjQ3M1a2sKLS0tIHU2SnBsMWJLSS9XUkRrelMvM0xa
            RjFoMWwzd1NCTURuUmF3TjNMejNZS1kKnezhyJ6iQaKkbKD0wB45Xu5W5cnimffj
            l615mHKZOB2R7tb5miq9pzj95YJZMNZ0FhYfCl0mw1ZBJQ5+smQM+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-28T11:51:30Z"
    mac: ENC[AES256_GCM,data:FVz/31juI5x1dycW7APuYVb2NnEnpem17UGtTRdfljaEH6Qr9zXGrlhq8dkWNsqXhZlDdejwOqQjcy9yrvl3DA3Ok6YV6MfWM8izgLSpdjoLQRN5EJy0R6ChZUvrVYZ1JU9dxey4tuHLj7iov5po7r8ZSu52bfMqgmnIIA79ow8=,iv:UYQUpZ+cfzgjK3qGOZqcByd9q7TjoQpt9pzlVN2LoXo=,tag:d9h0cxLHcHXBTSofzxo19Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
