apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
stringData:
    admin-user: ENC[AES256_GCM,data:/Liu8tU=,iv:mbFaIo8nat47jAdKQvRiECuN7POlyU8WgUE/O4XxqjU=,tag:O4vXBrB9YLm301WRtpOG0A==,type:str]
    admin-password: ENC[AES256_GCM,data:gv5bRGVXymnZeid4nm4=,iv:RbjaKGZyoFRpWxwshl2FGdcNQ2VLku2OcVjC8iOca1M=,tag:k+CicRGXz7iwP2Pm2iWgFA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGOEVidDA3R2pCUkVNUkQ1
            eFhPNGRNZGZ0cTl1cGd0bHJpTTdrVzJSZEZ3CmcvUnQ5U2dKR0lJU1NrUkxsM3Jh
            dUR3aUNML0R4bm1ITi9UYnFjQ3M1a2sKLS0tIHU2SnBsMWJLSS9XUkRrelMvM0xa
            RjFoMWwzd1NCTURuUmF3TjNMejNZS1kKnezhyJ6iQaKkbKD0wB45Xu5W5cnimffj
            l615mHKZOB2R7tb5miq9pzj95YJZMNZ0FhYfCl0mw1ZBJQ5+smQM+Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-13T14:24:07Z"
    mac: ENC[AES256_GCM,data:ZsaBqc38r0wBk+8WWcG0V00HBPpY1vgE3N6Ccc4a+TVLKt1f0B9krmqBNeQW1bpZU2ttjMUjBTz6bJCI2gz+gr6fosowGOhZbl4uAc//M7Fkh96FERM4HHMMU/m2nvrhQzDxJTgMiWxKq9VhwPDNgsbNwb6oHs4ZSP9ylsFZTy4=,iv:133rTytwhweRvQtWRQGeYcDxp4buUE9T60+IB3I/l0c=,tag:f7HvCzIK4gVzyGeepNkTzQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
