# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json
controllers:
  redbot:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/phasecorex/red-discordbot
          tag: extra-audio@sha256:eb1d5e56914b370304fd34d1e00381b7aaf5efcaf53af984cac09934fe07324b
        env:
          PREFIX: "?"
          TZ: Pacific/Auckland
        envFrom:
          - secretRef:
              name: redbot-secret
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 512Mi
persistence:
  config:
    existingClaim: redbot
    globalMounts:
      - path: /data
