# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json
controllers:
  redbot:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/phasecorex/red-discordbot
          tag: extra-audio@sha256:daf6596a253969ed2aa44a854fd69842a54b50623368f2d532a4a05c96e3ad8b
        env:
          PREFIX: "?"
          TZ: Pacific/Auckland
        envFrom:
          - secretRef:
              name: redbot-secret
        resources:
          requests:
            cpu: 10m
            memory: 448Mi
          limits:
            memory: 512Mi
persistence:
  config:
    existingClaim: redbot
    globalMounts:
      - path: /data
