# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json
controllers:
  redbot:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/phasecorex/red-discordbot
          tag: extra-audio@sha256:534fe17e83ee35f396bbb2092a69e2983a2f3e67a22567d1d3483b6d7be76ec9
        env:
          PREFIX: "?"
          TZ: Pacific/Auckland
        envFrom:
          - secretRef:
              name: redbot-secret
        resources:
          requests:
            cpu: 10m
            memory: 448Mi
          limits:
            memory: 512Mi
persistence:
  config:
    existingClaim: redbot
    globalMounts:
      - path: /data
