---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./httproute.yaml
  - ./mcp.yaml
  - ./llm.yaml
  - ./external-secret.yaml
  - ./ciliumnetworkpolicy.yaml
  - ./tracing.yaml
  - ./claude.yaml
  - ./codex.yaml
  - ./openai.yaml
