---
# No yaml-language-server schema available: kiali/kiali-server
auth:
  strategy: openid
  openid:
    issuer_uri: "https://auth.darkflame.dev/application/o/kiali/"
    client_id: 5VQJNXnfnTEnY0kfqtnvdIl2iwkNzZFht16JDdkW
    disable_rbac: true
    scopes:
      - openid
      - profile
      - email

deployment:
  cluster_wide_access: true

external_services:
  grafana:
    internal_url: http://grafana-service.observability.svc.cluster.local:3000
    external_url: https://grafana.darkflame.dev
    auth:
      type: bearer
      token: "secret:kiali-grafana-token:token"
  istio:
    root_namespace: istio-system
  prometheus:
    url: http://mimir-gateway.observability.svc.cluster.local/prometheus
    health_check_url: http://mimir-gateway.observability.svc.cluster.local/prometheus/api/v1/status/buildinfo

server:
  web_fqdn: kiali.darkflame.dev
  web_schema: https
  web_port: "443"
