apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:cS+8lfvwaGW8++G4a/kJV9EQWDJdasZvJKpYl2uuvb79nD2T1ECAZ/2u37Djq5ecpzrm+SrWMymlRATi7gYWcCIkag1PSgjCFFCe7BkU5zdOl3suiBg7AcDciLhl3pKrG5UALwPIGTUitrU8TIFN7zs5DC24PtLXUTd3Y31cCk0=,iv:jLdjPW8+Z3VB1emQQ39OFOTl0wvHDBKYXyJsNnS3Xoc=,tag:93RO/dyYfvYit8NVfe2BLA==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:LGHD3gTpDq/yb2WpFh8K4ob2rvbGsbEXHaUT0tZGu4HZj1ggZn99t1NLmtNpvO6zDM5ONDdoLGnreGB//Z5d9LJhMD7g6uyelKUSzHxg0pZR2I8WbAl2+IFUf2kfIth7f1UBX8pOOF3AxB5QsNH1iXGDY3uyBWi+vGJ3B6sMmXcf+rESiC3CzXPVU4+EwYj3xGHC/KDHTObUPLh27rUxIx7YzfDwYSsflSG+bfos+M+/rs2P0brTB2Vs4jC0m6C+Veii3pyLwmu7Nocgm6Uog5o2+kq3DUZv,iv:wN8OvWKhDfFQU/e0gO2az13q1SMRb2Emh+RHSv6vUbA=,tag:akQ3tIcoNn+YExSdi27eTw==,type:str]
    #ENC[AES256_GCM,data:WzQ8utWOnrNs4XhHHVY=,iv:Td8oVXCm1Kqb25bh5B8zmLduPEzuR1sbMiVAyMz9exU=,tag:XG5xs0uitdNnrG7323+zyQ==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:qBL9gop9yUQG,iv:YxPBYuaWVqxiEQ97b3Cju/TyBshqfW3IvQ0BFx3FqgA=,tag:IgeASHXGDPWxb2ADb3uBlw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:RRXzKWB2G7Fc17+i7M2EgRWVY7tI2sKadyGKkpqTkLz/seaZu8UnFA==,iv:yEXUl7P45eZVZgsNrGVbygHn9GpV+3XECn/zZTEbIJY=,tag:TOCicMeRmC0TBZ2YPzAHhw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:3cDVgB15N/Oa/4WiIlx4KC8=,iv:BdDKXWQSiAXoZDqgYNnMPUTrveFzNQmgi1YZD/mhB6Y=,tag:GjmuRKv3qvyvPX9fL6ViLQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:8Yld6nW8xb4tZXY8OmBRlg5mkX/qwPqCFmJDu4n97FrXcTVD0icIy5KraCBCnZ3lssKoYrc2fSPdKtPZarjW9uzYPbURPmVcDCsqr8LAB5x1RMVT2e1MhGbRfu9KJDAqKVncgjcWbxILYzlBfDEZXoioH9hIZRzn4QJLxD8HaYc=,iv:CTMAzlzDtTL+H4LdCtzoP0trPzdvp9sv3joUyzoB5Ys=,tag:rscQN6/PpR82raUXW6FjLw==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:82TnrsEk7hf041mZdjXjUcJs9Aq+Pa2GyY5xb0IDUQCqZxdhT1Rv0mpkWzg3QJCW+XUPnnTPugQOA3idQPVhcupP5fSdz7KrTO+brtQsTiy8NWWKJ29QJlXuAT+ZnTJTTQNBrsJQsDi9BoEF9Y0O3qb5ZZpJK6JpnGMabM9OwAo=,iv:yLWS2U1LKs2OERFh+uinlAZSemUctlA/pTNiGLjf7FE=,tag:jQF+7PocPbR1ydGWN/FOmg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:I5vOkjhaaOhhRN1NzLvH1pp7BGU3FeHyu5fQgKAZLZ9BS+nyqANFNFz7mocrzAMr1Jviag1t9i/nExxOWiRqIk8diy6EoN8w3H65Gf4TP6I=,iv:WWd7VHcqKci4mhEI7idpAyWaLhkAp8nYYxXKCx6vc9Q=,tag:MJvMvwk0JbuNcVvd4nhB6A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdFJEVnRzNGdtdjc2LzQx
            elpiSUt6dDhMRzJGN1h6TEVBcnhDT1YwT0Q4CkNJYytRVldqMUV6TWtyeTFlR0Qv
            eHVKQWt6YWx5UzVoKzNMNklEUTVGZmMKLS0tIGV5WXVrZ2tucE5VQTlRdlFnNzFx
            VmJHMm5Qc0lUY2ZzN3FkNGIrdGphUU0KJPOjymIcH5b34Ys5xeQrHtY/qih8u5bi
            qs74/fgr9DF8G+yOiv4BGs4Z7PBJU4FoXZ56xXXdOIFEagph15lguw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-14T12:11:58Z"
    mac: ENC[AES256_GCM,data:UJ9zP7ZkOMXkt6xRh8KT5BMzMv2j6MbYSIyghyUizGMatp5YRjSjmcs2bB3TsZ3jHl8wnwITjal083ZuAfR5IHDE+XP5GF1RYzFmNFMNYgvfygBiiHCqEA21VaCa/JHgLecMKOI9c8xuMzenDqMKCaFjKXF6S+Kxt0vL1svixks=,iv:OpYOPWVfpdiqWt/NBMi3ThIhdXalu2oyUGHYuu7sWpY=,tag:5JiLhOMl30d8vzTSER9U+w==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
