apiVersion: v1
kind: Secret
metadata:
    name: authentik-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:frPSOHWFhnlvbdVAXJqjCPTSkUltHpj2GXzXtMPa004kKrV3EazTfOeItc0/tazsftCOZ/LNXKq06KWBPq+AYR7WmfRk48AV5u3piWFpDvzNUBJYmj1ZtpjhNGahk1aL5Ucf1V72mP+tChF5ewLgGJPjQBBGHG9bf9ywfT3BIDk=,iv:fxUGy6qiT26BkxNk1Jk/4qRLmVykSyY1T+ziUQ80F8A=,tag:myP7kw3eFXsznLin53hGMw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:PNmiluSrNl5WpZM0Ww4bBxHXK3Pg04ppWmgCnRvBsK56+fXVNtUoClAwuH9YGVClBPymvx5+NoETxGGTiU8+wxspn0PcO3BPWpNjXIltEMwnasyqqep+zaZWMXqlrvpDFXAm6tr8XK57hL3qVkjJMqm/N0k/O6rZUnycFQk3EM4m4182NdyO7DwCaRUFlp55Ji6sgykMqT2M4FqeQDaTAPU6B9bG1cOWpEXWjxzEzthfU38G6hl0EoQee6buS68svIIWxNj46kaX/jeSYT4BKndq8msKq/WP,iv:mKN48kNBrikMXYTSK29qLpSHuL0uSuTSfpQKzdPzesE=,tag:QwbBHjNgEsNd2ZLly8PPxw==,type:str]
    #ENC[AES256_GCM,data:nOvwtDWC5sAkGOUR6ic=,iv:Jtsyf8flX/1ruDGwPTcXAmDHOmCdFf8pNijLuHSlngo=,tag:QrP1tqxMfOAb+cd9kZZJLw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:UeRY0rqm2KSq,iv:GnB4XAiAXujlG2Ta+eGgsDrOA3AHP4NPvZlW8A+ydsw=,tag:2Eowp8BodzIQ5FZVs6AN6w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:/SBYMe7ShqfdSkTQxyuH0Vhp/iVS2Gm4YMVqg1ptR1cqeA6vVpJYZA==,iv:vA/QPVbUeQIKxfBuXJFQOFZ116lLhqm/+PoS5u8FJm8=,tag:xr8NfMP71zglTb9fhDQVyw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:F5Bl3JgLlMeU0CLHvDv2GIg=,iv:nk/1n8gP54GhjbaMQRDlusSFc0RkxLzbhQEO2rHGHFw=,tag:o2XAtCJcmAFyiTK04E8pug==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:wudmyGTRgS3DtlXsIS7jJXACur/GZzt3AX6+eM5zuaGLJNuiuhdExHBpKInodVi/hg3wdJhqDvVWfEFJ1O86hek3w0ccWqoF0gdBe7KdAwKHPF1/RjZwP9uUSDnhEnYoejOnfIbamkCOiqgyu0N4kwzsCoSc2RYKfGxyVjTLYOE=,iv:+JytvybMtHHJALKVwBt0xRhvULJDkPBZUQZTKH2a62s=,tag:ujeGcWGgF3DFjN9VS04P3g==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:sK3JccjjSOa5e70ZNLWryP6H4HnBL+Ta7GIvOL07a1sEvOMR7wRtKR1N7qU8tiLy1G2dvMuZLKJJf22DIi/Xw66Lu+k2Lfnd41hHw/EiAh6DEhtpX/xbIPSdY36/Sp+GapuHUvjS+4GUgVYrFYWFmWlPa58hQtnXD8TDO3UfOKQ=,iv:j8/NzoM69upLn/UIkDbpbVKPi7o7tOOXut51EJIhRJg=,tag:F/dMQK0M8B5neXWozTHESQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:88IXhl0v9UxkosrlVO2PEgI1YrLMN2XT32+V+rtMKDdgzsFmS6qbDHCtMVDRlHj1aMNU8au7HGHARcmvGA5aOE/AaVLSZvm6iuH/OTeCmfw=,iv:4rRSQ4M6N98hSYUJQGbujcu3kAYW9rbEMKQ9muqUt2k=,tag:ANe1eoTbjWfuQD9hRAi+zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkcDdIUTB0R1piWDBHL3Zy
            VzNjZTNSMXpoV0ljYmxMdi9tSWlQMkhTT0VnClRCQTEyT2s5TzJBY3J4TjlGdUVs
            ZUhIanY0RG8zY09UL0wxay9UQmhhS2MKLS0tIFl6aVluTm9oQWtOL0RoYW50TWp3
            YVBwL0ZVVTVUTWdqUHc0OHZCVEZqR1UKbsAunylJpHRReo9HwsIQd7972U6+AKNm
            mErV72yGefUqNvhkq1ah1XJCtY51l4bHyilq43MbCVDTJ2I7yw2Vow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:04:01Z"
    mac: ENC[AES256_GCM,data:HdM0XGsSGzlDSvdC7oMU7BiZpm7S5VO8PrvWphlls45IrXFKWx5yUD6dU4PeJub1xAcXNbFxiPQj2c9pN5Z57YH3CGvSlEVG+MBQl9MiYFu3cUJZNPlEP/Fd0m5xBa0p2ov4TaLhr8rXsVGVz2fcZkHSNTgMEvEZlWx04Fs1jS0=,iv:V+soaC6oPjCfKXZh4q5T4PR5fmqsdJFoe0FKv2ZpbVA=,tag:Xaa3y3bBYv61BBXo/i9qtQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
