controllers:
  thelounge:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/thelounge/thelounge
          tag: 4.5.0@sha256:197048ec6e1a62a1abe7a55b466b24954ea22bd0998c8887b4a8bd1cce696530
        env:
          THELOUNGE_HOME: /config/thelounge
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 512Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
service:
  app:
    ports:
      http:
        port: 9000
route:
  app:
    hostnames: ["{{ .Release.Name }}.darkflame.dev"]
    parentRefs:
      - name: envoy-internal
        namespace: network
        sectionName: https
persistence:
  config:
    existingClaim: thelounge
