# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json
controllers:
  thelounge:
    annotations:
      reloader.stakater.com/auto: "true"
    containers:
      app:
        image:
          repository: ghcr.io/thelounge/thelounge
          tag: 4.5.0@sha256:b624275b88f88a08f8ad56833d3b1b3400cc39faa410c3790ea30fa24d39b675
        env:
          THELOUNGE_HOME: /config/thelounge
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
        resources:
          requests:
            cpu: 10m
          limits:
            memory: 512Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    fsGroupChangePolicy: OnRootMismatch
service:
  app:
    ports:
      http:
        port: 9000
route:
  app:
    hostnames: ["{{ .Release.Name }}.darkflame.dev"]
    parentRefs:
      - name: envoy-internal
        namespace: network
        sectionName: https
    rules:
      - backendRefs:
          - name: thelounge
            port: 9000
        matches:
          - path:
              type: PathPrefix
              value: /
persistence:
  config:
    existingClaim: thelounge
