apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:SQ3xn8azt6Ntg30qtfSykzawOSIBud4pjEmnaKeM0uXXNTnqU9UrvA==,iv:u5/Oxf22GWOJFsc05KYImNtJLs89fm4CkCMn5SLzJ2s=,tag:/+h0+VRj5Q+Msae2mysIpA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiVU9IUGRvWXBQbWI4WUVM
            MFkyZmpTVU8rM3IxV25FMTlwWHJCdGVaOWtFClRqb1dnUmh6RTQ2eVRWUXY3Qnds
            STROWE9PRDRtQUh2Q2FUcy9oemFsVGcKLS0tIGgrV21vUHpMcVhQRlRmakZXaWVV
            ZEJHMnBQR1g3N2RyN1k1VlkvQ2x2Yk0KJtnDxKqCF4Rpq/rvQQsoO+JJKFlNxZfH
            q3yMaAqtixgAEUkhOjsI2mXaxzyroeXAsIJ34VqvKDus0kDHagNvgQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T12:36:18Z"
    mac: ENC[AES256_GCM,data:0rHjQ19oPcLL3mqeC2yWSK+RiAIPCs3c2gUEq5/oflviJ3M6CYr/JImObAyJ3UU+OkIBAHRTy2T7Rg5VW629QOhq3XudyU1o1/mUcu8rgd0pWDmtQDRddFg/WJTU9COk3/XqOtP6K/IUWeZuCaEQAuhVP60jAaK8C3m8NWTeM1s=,iv:W5bxzPQyaxbv5PhQaLPDygyu8sGVnK9S3v1pNrBf6RM=,tag:wlD/8lddAs2B41CUYkoU5g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
