apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:NMCorW9RdTn7XYdR926XwGTfxV4SQHliBu+/s7CrN+hUtGr8l15PGg==,iv:hoB1a4rgEnpL0KIVQCjuqsCB17tR8F+32k01kYTtcbA=,tag:vBCu3/pXZTuKW6pv8g383w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHazBCNkJWMnJCUHpNZzVw
            WFBnREhGYm43UFBwbG5JTGRHRXRlZ1d2MVhnCkF6TURWTklSaWh3cHhMcGRHcUha
            RUtQTVlUbklOZUVnb1UzcEV2ZGhXTjgKLS0tIFhOVTdlOUg5YXo2bUFNVGZIeVkz
            ajFHZm5xQVNpLzZSWWFqRmJ1ajR4N28KkVseAlWiL95R6tnbGS57nCuwyYxwsVua
            oF+mXXUfKuw+7z5Cg5ntMioTrurQvAtWYrh+8VgRdTzB3DMIyvcqrA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T22:22:52Z"
    mac: ENC[AES256_GCM,data:/AdULgmPZi1xAhIeK03w0FaItdoLHTeHfEmwiXliBoqA3LBV4eDtY357L0SgegkDzaNP6nq8mNNKa3FEXZYVs4FYjndHr+1RkB6GzEKi68pUQ6IiwNy3CZRG3GFId35BeAERlOZ9fFzV8wl8vyfMlPRKKu5WrtDtHMVEYM9tk5g=,iv:5DCx4IjUEkb3mySnLYKc+j5freREYH2PKWdeDL5CjWg=,tag:a+PaM7oGo+hQKnETPlp2qQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
