apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:PlnaOhk7/2tUR6xwJzWuc8Hm3qySd1dOT+WdL4RRsVEy/EHu,iv:Am19ba4awPPuvRDU6z0eG4lp4BCMhxfAlnmq7Lhzpdg=,tag:Dl5VARj42lmyFZwW7Bx/Tg==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:lsNvoCgtCBONUlL2ITcfJw==,iv:O7kiumP3zsGMboVQu7C81ElYwUxBXjWeIwjveNGmZYA=,tag:MJKmZWg6ZcbIOjUKL2KS0g==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:Q2CgCFieyUV3kP5sGwuITS+z,iv:oNzS6iriNNyT26bqQPfYCU5kxnuBT8YNE+8RuSXMXqc=,tag:3hDQ8PTcyjdJ/7fP5IytVg==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:3YwHWhT8/0erNYfG,iv:knNgySMblGuRmLrzHiq2yu1tti1oQ6AVh8fK2vCHBc0=,tag:6t1WYVpk9NZO1Ltnk31eWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpcGl4Q1NmaDN6bm9rNFph
            R0xYNGZUVG1LUVhNL1hZd0VmQ2szajRBUDFnCmVVbkx0TGdIK3VTQUs3SkU3RDgz
            c1dXeXBkclhTVDQ2VHFhZHlDQnprMU0KLS0tIENUNTdIY2FMei80dlgxTVN6ckZY
            Q09pMDgxcStUYWYvR0VLYkVldUZzQ1EKNT26s1a2FWyPrlllDkmimPM3IshInuJ2
            xjbtuqBIcskdWTEPN+Q3+vLUoWPpH48g3VVOJs2VhrEayh55ge/jNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-09T13:51:53Z"
    mac: ENC[AES256_GCM,data:9ANYI+tLea7plZTYI0NcJPiAxUa0CXeJYBkqwa0llDMXTjsrDUmmJHLjaKgWjnpPtCAxEECdelQFLazOugH1FrlkKc56HxiBQbqSlZWrqmVTFakn1bZanPG71HExvDhxl/Av/KJP2Ug7bXqVyE/5aALNJZSzHD4MrI4Q4Ecmwr4=,iv:6b9PvQeUeGkpjQ0EtSAveiWbKNwJC3a8SJX54IPn9QI=,tag:g+rvILerz8s9kkTxzOsYUg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
