apiVersion: v1
kind: Secret
metadata:
    name: smtp-relay-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:4tnmgqEGbJ7YD7KbLZSPoBvvwkmFaSFatyjajoq+SrH5BZI6,iv:aJSnurEfJugp63XN4BulB1yoiR5bJvnPObcuYzHELDM=,tag:pe2TYessGMWUE5QX5+dWTA==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:RUL849vBrxGWVZ+eQCD6qa1S,iv:79U2xClja75iIyoz0AQ9c7V8O/4XhoFC26rBu+y+8Ko=,tag:vXoWlsVS2PCEXCGxsXwc7g==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:HTxn6nXS1BFaknSh/gA5rk4uXbMT,iv:I8bz6LYYNlUNmy4Mh5FU6tcE2JshMXFDdbikW2L072k=,tag:ufGyDKuG08zo9BLkLjfLMw==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:12XIJsdefqK1bELoj9zaKqV1RKDQ,iv:51XYvoHUz8dHmve+R6LdYHECvdQokh2R8ZCCVkcwm3o=,tag:tLUzk5ZyfqZL8ZSD+Zvrog==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeGdYZlphMWNHT0o1QXJR
            WElybTQ1OEwxUVk1bFV2Q1dGVUc4WEgxSTJ3CnBuazhxSG5BUUtrL2FlVzdxS1pZ
            bW1lSXNrbUx3ZGZsYk9mUzJtbi9qcUEKLS0tIG5ic2c1MVBBc1NpRkgwbFhBLzU3
            bGRYYVB1a0RQaGhMZ0lsNEJUZHVDOWMKNhTpj1hbBQMd2wRUWwD5JTjL2C5sw9Pq
            293rdYM3zKVDM37RaRqE+pTekgr0X/fG13vfhBvIffGS54qOvZ6ckQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T05:22:43Z"
    mac: ENC[AES256_GCM,data:h/viZ5d5Ut9KMuftOkOVbPn6NU2jUGgO1bjjadH9KrzEhEkWoq32uvc/Oh3bQASVDi1TzYxRwPh/zPeLJsLcSpbiEygP8jzoui4sz0O+76by4PDgr/yuETX0IN4KYbqc3TS5SLZpd84f3Mqt0kXHWzldh9f8S2ghzF+I1JZURTM=,iv:1mmHy7kH2hDg/98tl6/5X2LSQYK8d9m0QtA9KMICQEM=,tag:gbENmyiavzEPcsusRCWHFQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
