apiVersion: v1
kind: Secret
metadata:
    name: minio-secret
stringData:
    SMTP_RELAY_HOSTNAME: ENC[AES256_GCM,data:/ubawei+6DKG2t79LhrB1wvL3SHGj9VMTZjmEN4lmw5dY2IV,iv:fDviz4q5s/madk5jt5fqrMmHmeB8MuH24IFA2MdmLwU=,tag:LyWI7psKFCDxMwYWaXcpcQ==,type:str]
    SMTP_RELAY_SERVER: ENC[AES256_GCM,data:PTmFeMti6ujr+G/UUdBqATME,iv:X3MjbpnZ1YXaMke9HNkBqKqEuSA4k6HqE0QdvhQ7AxI=,tag:Xqy/Lxp0+hnKko0pCFoThQ==,type:str]
    SMTP_RELAY_USERNAME: ENC[AES256_GCM,data:L0yv0+2LpMGG/xS+Xh6C4OHXEN+4,iv:IlyPTGoaxc7ygBRKkR6/7UUx1DYCHlj65v5rs7uSplk=,tag:bdHPt6zrpbiV/w7NRb8fXA==,type:str]
    SMTP_RELAY_PASSWORD: ENC[AES256_GCM,data:zexO8oQskrS1g8cCJhuXFksTJbRxamCMP/deVs528Rc4Ahe9nYEWnKi57misDk/Zk4zUG0YqxjUeTtHJX34SyGqJysv0IEiey19ZOM+wlXa+O4saTKCEA0zTI4n16fda1iYD2SjhNIpYQqwMMhaqmFV4bI4jCHVvkxxAdEMzMH4=,iv:wAMOZmv5tOX/kqGF3GOUEBI7ZMv/zBI3Lnv+4kDP60E=,tag:tFxI/8RcFrlaymaQybnauQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeVE4c0ZJR1VGTU5yUGZJ
            dDVRZE1uWE5EWHRRekNObTBTeS9wOFl1VjBZCnZxbXZ3b1NJVkFNT1NJM2p2NDRz
            RWJESUxLdVNRMjRZRCtPMFZUdnRqL0EKLS0tIGpyMFNWTDNiT0ozbWpmbVpmSXU0
            elc4N0dibXlFMmswejJZdU1KQ09pZlEKE81mpbMoXPZ1urJJAZXAJeiWE4drhdsK
            9eFDFnGtF3zkCsZ0w0UhbN0c7c0FQdJteq+SDM+01/nojHH85ZxnMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T13:08:51Z"
    mac: ENC[AES256_GCM,data:zNntmymv+VY3WkBgzoh3lZS0Y6jd2+FkbjIV5YlQAdVTeZt4o0Au+DQktZVU8N8hZaCrllGx+/vuHW+YgXRrs5ict49d012yI01OABTURZN6H490KX7VfiMd0wz3m4rqdPJ/rzNJDKhjwXorGcevYwx5nVBKBGKx4HsnXKcWbEo=,iv:Gdo/91genh+PBRwfstMUq9vntdJ6F83TiIIVzR+JI+Q=,tag:CElj+GupfYAqj6brna2/Lw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
