apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:VI+jWws=,iv:31N/VY2Q3/5w8QVGyE4lTbXtwbXPfzHPvNYD6H4l9ck=,tag:gBBqDLsSnE1GprbvQwoZ2w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:YNHG8wmSBWQgrnNN1dhfOU2lAN0YePG/BBXfTWbK1MLECNED7fcI8Q==,iv:Uo7wkyEYyY4s+K9j37ibeLRNXUufiHNGiHkjgzYFSJc=,tag:j55tHVoFCw3JzA0SwdMjjg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:xQPw7MV1i3I7cPQODg==,iv:u1zGdnSQo7t0MyZWGHdMsFGfbI8kpYvx3qk7wr/PG6o=,tag:evIEhE/KWwddm5UbbRPx3g==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:0/RF6eVOQMVGKKuxMded0viWGaPKY7O2lD/5+HJoZxy+5cvop3CGieMh27z32Z7Ow3IXUXNm9iB3+Xf6zjv2CeLta8fivBSDY+hXRfkc2NgKA+LMcUNiVzl9RNJgnro75mdK20B4BDL5i5D3FAzpfilfyt6MKgeXipY0y/KgCNs=,iv:RGzimxEdX+7Z76J6ClVEcFPZgtjCluvXSMwr0kwKxKo=,tag:HMA/DTwIuko+9KLeJKo9ew==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:V0aR+7dXvB01xiiULS+F3lSAffx4g2Boe5bJUly/6rSDBSNIvOybjJriQUtxU5oS8YlXt/nr1boLUiu6GgeTcTeYfL7diEv8hF0umIX54tA9ZMcLFcjKnxcowA0T0JDqjpR6e6zhGEp9FgczuZnC49Gf9e87dG7J8cg+f2qh/Zk=,iv:lCktS26wwD54gPPdecHObsIWdHrsdrRTbfalIEj7IiU=,tag:oULzsgccJM7pbSK037j0lQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMcEwvT0dHdzNzYkhEY2VF
            d2JwS0xXaE13dkRzV00vNWw3TFdIalJhQ0FNCmFUY25YUERtS0VrYjVuQjJnaHpi
            enBaSWFsbmk5OTFFWWZYWlJTWXJCNDAKLS0tIHpRWFQ1Rk9HdFh3NDllRDUwNzVs
            TVFqRjd3S0prdEx3MG15a01rMm5sSFEKkUqZBZxm+TTfKB/VNA5Iunz0NkXuw71/
            FSos/nUokhJIV5b1fH58ZuAK8JVWN5Yf3cKrgbLTdmKVc1W53yRebg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T06:40:14Z"
    mac: ENC[AES256_GCM,data:5FMx/J9SLQkZTvdS6W5yk+yVVanlF/ua4ZNptjc+sqo9gkrw2H4l1RUii+qZBElJvvDItHZ+/AYIn1nHeLpUpX4jSGu+c2owYGAHFP/bxgbPbnaSIivToycH10ZM0AE2iyT+GYFQpmgukubBcXUjIDRRsgOq8fyzQ3tApVync18=,iv:yf6p8iyVX0R/+r77ws7kH1xJUWAm4Qz14WvcmSiKkOk=,tag:uJFxlelU4xP/iiCxZm2IzA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
