apiVersion: v1
kind: Secret
metadata:
    name: gatus-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:MX/5NuU=,iv:YEjJ2oCg+HddGissQQkfX/3t6AfBVeHiG6pOJ6Ci7GU=,tag:A4sOl781fW5kWdIBlhvGdA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:AV1tZ9oLnxyI2Jioou7Q2LVZlll7bH54y47wjPd86uZDDWnaiba5iQ==,iv:0gpnO0LvhJLCGAxdrrt7hNTNiQStmNohljE5qjUwgi0=,tag:0OIajg56yHQRHeUJ1iW/Ig==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:ZaWwB71xK6ZxJgcF/Q==,iv:leK95cXqU2JznA+Afxz5NgLFYuH2vboDYEeI+lvwLes=,tag:k0SZZlcdUw26LjCRBPWryg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:XW/0JpN9xr/cPU0ew1B2umCDzE6MGDFdYwomOcXhq1pqjDeKjBjlauMfaNXylsbxIjV6tthW16z+F3eNQ31twJAQ5t8mtx4KgcxBTm5W0c44rDMDcO5EyABlr/2+2TXjmf/kykvg3K30Dvgw6zk8CdbZbUzIsV2s9yhEfcPhWT0=,iv:k+c9LXVTch6M6sIVFrMSQPmxu6/luVWBideBP2R5Ths=,tag:AYm/zU++nOiZ5ciuF8aRAA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:qpVJSZEAFdwG1s2naAgqglKdep55exJrsKjr7WR9m3sF46eGVF94ViywTiR8Oa3cQhaaQiDNaXcNP9ViuZVe6sBNkrwIMn8N8JollnpgMOwqZ0NjgkEiomtwmiFPj4sspmAFdN6YHks+eTJTCzf6nY3pFylWWtL3vESoOlTn0Fc=,iv:8NH9tTFSrFd8a8x93WO8dkBpUIpq1zkym7oaxYTioQ4=,tag:2ddpbP4OQ3zT19IT3JUBhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKbmt1RnZETTFoaFRFT1ox
            WXpGQkNMRWZQVkU3VjhlRDZ2aXZ5WXZGYUJzCkdwZ21QeFlsdVQ3VjBMYjJZajVE
            TDhiNjFhYm1ZeFJ4R0VnQXY4cFBRL2sKLS0tIGhRWUo5Y3hpNWFJTkg5MVBjdUJi
            L0pvcVhtNklZaGhJWVFLZUVlSW1UR3cKcOUfiZ0is1TTluupLq/MXnV8CdvRU5p0
            SHl9pvLj0ozm1tWzWzoddWSBoEEfTl3PxCyvVtTpH5ApAmdtng8SAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-07T05:42:56Z"
    mac: ENC[AES256_GCM,data:8gf8Bd5k1m3ONQ2uu4kMgpqrHwywxXIunAk3UeFnu9J+i8LAUNlQZjN60ah5KsF+y6RzP2dA6oel7LtmDlc9sDlLXQnHO+rTE1RjT604TraNjUx3wVnChqHdtgt5PS//Gza645r35VwUBc+M0j6IcsGxB/Ra65X/66jdY2F/ehI=,iv:9Ym60OEwUDOtOhi0D+cVPPs+f2rI3EYIU5edOxE3XV8=,tag:IU9//8C577ZGGO3cvmtqIg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
