controller:
  type: deployment
  replicas: 1

alloy:
  configMap:
    content: |
      mimir.rules.kubernetes "sync" {
        address = "http://mimir-gateway.observability.svc.cluster.local"
      }
