# yaml-language-server: $schema=https://raw.githubusercontent.com/grafana/alloy/main/operations/helm/charts/alloy/values.schema.json
controller:
  type: deployment
  replicas: 1

alloy:
  configMap:
    content: |
      mimir.rules.kubernetes "sync" {
        address = "http://mimir-gateway.observability.svc.cluster.local"
      }
