---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kopiur
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '-2'
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Darkflame72/home-ops.git"
      path: apps/kopiur-system/kopiur
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/home-operations/charts
      chart: kopiur
      targetRevision: 0.7.5
      helm:
        releaseName: kopiur
        valueFiles:
          - $repo/apps/kopiur-system/kopiur/values.yaml
  destination:
    name: in-cluster
    namespace: kopiur-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
