---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./minio/ks.yaml
  - ./atuin/ks.yaml
  - ./excalidraw/ks.yaml
  - ./jellyfin/ks.yaml
  - ./thelounge/ks.yaml
  - ./vaultwarden/ks.yaml
  - ./littlelink/ks.yaml
  - ./authentik/ks.yaml
  - ./forgejo/ks.yaml
