apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:qShH0YuKgazbSh5Grru0RU7RZetU5mcclc1cT6tdCCffxYMTSs2oKbjijs1QuSfI5Fvp5d4P2U/s2G6qJm2Xy/q4F2xC7om9P1Z51GSgfLix0OLx+UQXsCaY4h2xCRBGmDwMBgCcWgPYBCtCk+8ObDAdSr4moYuvQBM2Esrs7Ls=,iv:aek+/UZsIKbmQIs2/gEDOuDOXWRcuBKjY8Vs9A8Fr8A=,tag:7v6orZiZu5i0w1YhJBf+GQ==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:nR8n9qQk4Ws+rGVPh60NaEvb/Bf7RofskgPs9x2VlQSqNzovnB3Z46NbnZMQmFlxBCx7EXrTMPfc7x9qHMLmKLMY0DipnZlG+j9otLrW5GH0PWI1638jC1lszhS5eIGZm5gcV58iF/h/5EsmxI1+T6uy0mBmR+ZlkIug/43z4jXOrP9JIsSoGRc5Ne20kvhLhEHXMYECk1anh3YNJBzsozU26OVLFSktbNSJImJfEPO2a3y3eGv5keQbzpmZCwf2OjN8VRqQFPH2WcB02IALcsjktwg=,iv:J4+X7TaRLtSM7fBoJ+ZEaLIjmJLFqomHnqoAfBQojCA=,tag:J3pXGEqaRl1vpHvD5NNWfQ==,type:str]
    #ENC[AES256_GCM,data:gZgy1h1cO4F3khAWnJQ=,iv:8dx016pmLoGjW+rurtL/j6CKGjs5bUxQickpiBpTXIg=,tag:FvVhYbNaOHOZSUTJWwa0yA==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:q2J+Khtvyw==,iv:+99mhH603I/eWoHSje2NdAoO5AcvpLnlj7HnuHfxEU8=,tag:JykCCy8ngJebs932iKnAzw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:L+FulFK1GqtaJdZz4y/QVzdO3jXzOBf744CX/tYvERMiUWs8Az0gvQ==,iv:VrtGGQJayJ2UEn5HX7dWrlxKz0U2mSArLvJ7sgfQYRA=,tag:K+zDmwpg+9fdILevp7vMDQ==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Vg7Eo5+luiuR/3pLn5QO,iv:Nnz0bi4c4L38QTbSf1VzpEHvEU8IinlNqBHOuMobc50=,tag:UbA+l7FjUd5uimilO4Pa9w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:137RRs2M6E71qLk0TqUBwW+5Pf/QVINoUoFKqmH5UPj3lkUX1i1uI4qniYlNOAEYMTqFpe6UK55+JOM3p8NY5k2401DRwO+OeHRordDPQ+/OlxK+KzQEo1ApmNwlAwDKDFiJ1f1RNyAutuNWELhTGkTCReAtP++0FygXxB+dx/I=,iv:nV8RadyXJ8eokIhfJma4OCmrlQLXL0N2PFgVAUwO+rY=,tag:yHdiArkafjEVsA5dfbFgoA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:A8sDiYac7C7d0GqiNlUJzzyLUW3CIW+v14y45nS2aA4qp3N74txFVEje0sN+oNtQSi6+szBt8Pu2ov3nO5yzlzPKXvpK56Ade20CrAIiUKIm8LOUpl5sYcphBXIxQRziIZ+i7eXA1qmoIiFFhTXtEFcU1nkSSKk4i145DyNEzao=,iv:Hu6SCnBG5ZXCW++FFjWtsKReUgSkwjoyvuqHVynw6vA=,tag:z9TVOthJGJuxLRscjLJoPw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3emNGSytHTW5rcG5wTkdi
            V1NPc1Z5dWRJT280ODFrRHRpQWtRK1NuUkNzClgyTTZCaWIyN29rZkYwYmRGcmRS
            czNOZUFYUytiYXhiWDl2dHNSV25WdzgKLS0tIFRSR3crVUdhMTE2YmVwK3RHSEpC
            VTRpR3lNV1dLRHQxTFBCenZiU1hiM0kK1+56G4/xmpjRByRD70WWQhtWY4NrGTIK
            ZbkxFBAuBq4S3zFIjkoEsxAaaTodpZpCrkvI8tC6rB3zwbwCk3Cq5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T09:48:17Z"
    mac: ENC[AES256_GCM,data:tlkrplhVoQFJspcu7MCyPQa2chgsInathcKVE4gy3EvzFRjlBGTQRFhJW7d8hJBC4L0Jf29WvugPoSM1GJSkm89iKEtc/E8tRhMGymWbiDcc7/S30xHSdISim6WSEJUiMjkZRe/mS/VO5wBGCmNOXPFYWTCRFDvAHcmEM/ZfPNo=,iv:0Hu4AS6c8Nkf9WBI5EbB/e9zb44cLKUvV4jdL878Vus=,tag:j8nCHh9bfyRTSB/i1j2zjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
stringData:
    username: ENC[AES256_GCM,data:7+GycFR2Jl5qYQQ=,iv:hdCbD1klY7H6KzqtXNy4W+PmuZ++QHk50IBFL7+Kff4=,tag:qDFjcHuxMVXIl7AqgXXrtQ==,type:str]
    email: ENC[AES256_GCM,data:AiMRANlBaVG43qlJqU92ltJq,iv:iOJ7+eM2g7fLp3maIIl4+D7Alu/5e0qRQjPR9jh7Ies=,tag:jIrgDnX0fwbdAXW6wwSz8g==,type:str]
    password: ENC[AES256_GCM,data:BtjxuI1s86ogOy12fUh3Mg==,iv:RKV4gG892qjMjMM4lrS/PsXB0qFDxgjD2YXFF5Ielqo=,tag:PWE6qjp+U5Twpjw0DTBggA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3emNGSytHTW5rcG5wTkdi
            V1NPc1Z5dWRJT280ODFrRHRpQWtRK1NuUkNzClgyTTZCaWIyN29rZkYwYmRGcmRS
            czNOZUFYUytiYXhiWDl2dHNSV25WdzgKLS0tIFRSR3crVUdhMTE2YmVwK3RHSEpC
            VTRpR3lNV1dLRHQxTFBCenZiU1hiM0kK1+56G4/xmpjRByRD70WWQhtWY4NrGTIK
            ZbkxFBAuBq4S3zFIjkoEsxAaaTodpZpCrkvI8tC6rB3zwbwCk3Cq5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T09:48:17Z"
    mac: ENC[AES256_GCM,data:tlkrplhVoQFJspcu7MCyPQa2chgsInathcKVE4gy3EvzFRjlBGTQRFhJW7d8hJBC4L0Jf29WvugPoSM1GJSkm89iKEtc/E8tRhMGymWbiDcc7/S30xHSdISim6WSEJUiMjkZRe/mS/VO5wBGCmNOXPFYWTCRFDvAHcmEM/ZfPNo=,iv:0Hu4AS6c8Nkf9WBI5EbB/e9zb44cLKUvV4jdL878Vus=,tag:j8nCHh9bfyRTSB/i1j2zjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
stringData:
    #ENC[AES256_GCM,data:0EuvxXbMWmuqOQ==,iv:8PHxRsAuMrE6yO1L1op9mso81Td+KdodcCzEW4Axm6s=,tag:JxRgoimSrRbO7wk9M1GzuA==,type:comment]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:nUZSnzGC8uPHuGTfnMu/bhE97Mc=,iv:pWJhshmUaa3QWmZLeGjCCqDbhidxhJ3zuSUUesM4G4k=,tag:Z+y3JArlcA3ClttmKFcizA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:Ky0edpYcqXHXrV1DToSzC9YdEWlz8D9MIebQ6Gmfj3vpoXz9n+TWsQ==,iv:TkBrW2RlJvLXhXeqJSaEhHsaZlmAqxFhKvm/nWZwcoA=,tag:+L/0Enj0O6uuCCTnZ6xLkQ==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:o7qzaEH9rxcfhYTWb9OkeGAuXmhJK42HcBuZCiktYsXCRYrs8269lK2KMwKgK1COOrQ0dmxrKD+xrBUorgn8jeOdRNooTWKlMytUcYsQQtA=,iv:H1YSts0oG/R2YabwvtgTIOX5GHkdBAvMpjkJXH1KihM=,tag:8rR+CyVNPQ38KVf20cgr+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3emNGSytHTW5rcG5wTkdi
            V1NPc1Z5dWRJT280ODFrRHRpQWtRK1NuUkNzClgyTTZCaWIyN29rZkYwYmRGcmRS
            czNOZUFYUytiYXhiWDl2dHNSV25WdzgKLS0tIFRSR3crVUdhMTE2YmVwK3RHSEpC
            VTRpR3lNV1dLRHQxTFBCenZiU1hiM0kK1+56G4/xmpjRByRD70WWQhtWY4NrGTIK
            ZbkxFBAuBq4S3zFIjkoEsxAaaTodpZpCrkvI8tC6rB3zwbwCk3Cq5A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T09:48:17Z"
    mac: ENC[AES256_GCM,data:tlkrplhVoQFJspcu7MCyPQa2chgsInathcKVE4gy3EvzFRjlBGTQRFhJW7d8hJBC4L0Jf29WvugPoSM1GJSkm89iKEtc/E8tRhMGymWbiDcc7/S30xHSdISim6WSEJUiMjkZRe/mS/VO5wBGCmNOXPFYWTCRFDvAHcmEM/ZfPNo=,iv:0Hu4AS6c8Nkf9WBI5EbB/e9zb44cLKUvV4jdL878Vus=,tag:j8nCHh9bfyRTSB/i1j2zjQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
