apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:FdnSfIk6+SOeekEZ2wlyJ433gHCkY3uHDlHwLn4UT/fpWvUaqhsmbem/5RVCZBq1zrVzqovXr9Qv9naRfeLPsDRJxaIT2Wn8YVv58aXDPpK/Yst+wMWb66mVL3ED3P6XFcqykHC2r+z1TC6seen5MwYRk5pbIxP/drpfnvIABzs=,iv:+4+IrXuIciPCQTS8EwP951+/jZ8akINJCqxUHPi7pm8=,tag:CVjyr9d+/KyQqKBzVAw4jg==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:iL73sxWDEM0a8gqz50Wxn3asoNUDgPuWMO2+2LYywTKgjMHu5zRK3xlKXhGiGzbeh3yzzTKjnTtIqXlWLqNbpB4KbdMy35DEleWB11Hqf68O6G49D7A64DTaJPXruTZ7xtG0Gn2NAHCEO4wvmk9iVdkHLQRl20lkfOP31555VwPeAPciKF+vjTFleOiNip6KQdzvWPJ2xtsr7Y98yqm5SFph6TzsY1iU6NlzJOwkdyZlfDq8wHEqUGG6/XXdRorCcjkb0cGmbFKenQAJauImZ41f6hk=,iv:KYmhsXcpvqVtP1eUgdM1AFjOackBYIVm6KGN4j80fms=,tag:Uk4fHah2k/V3tUNUTmEHCQ==,type:str]
    #ENC[AES256_GCM,data:15aFOkFFUx/44MpMN0k=,iv:22pyS6ckJrsiw/uK7rCGuZoEQlrjnNihDesRVAUvFnk=,tag:e1PLBqJOAhMwRJoOsSHBZw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:sNLQgK83LA==,iv:GAh+H6Aeh7f+6d9wWnNYxEKbQB5VRQTG1K5HxtOfArk=,tag:3FWEPTwZ/x6wP/2TobTxJg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:IfnaH74XAAyeyLJPfTOSsdYyfQw6a23QI+Wh1Ey2Acd5ZnBqDr9mkA==,iv:V2dYw1UwGJZJucrjvzF98xv8uuICH8ETQJYrbKzMf6U=,tag:idiKRiQy4TktEGPGyWXCSw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:Q75taCd48dr1QuMYDe7/,iv:QaqU/2i2fNcu2BRRkokn9Xqgk14B9GQ4KDn8OBrCcyk=,tag:7gWxtIs6pwOTfPuUWTSBHw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:arilBriCsm9i4GYjvj/Fak2Him37uek2hyC8kuYv+RnyJx6sNVNwHdg+UQHT48VsbNQq/dKedayeXS3VMBxudfE4ug/jyvpPhsMcE2QvmTga0NgMMB91sBEJhgnIuVHPgfTXCs3BjZM/M+wl/iMZ7CM4ac9hhprLsb44oJe4Rmk=,iv:Vz0SQemD5i6XEa9t5hLD+fH45dGFhl9EWvSh6ljOeF4=,tag:U/kRYMSF8YEU1Xv/ibH/9w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:dDzPxWzSk9QDPrqxxKiG4YWGGLi/0jHN17/LibIIqK5qgmW9rmqlxF4uDCaSD1FNxP2NQVE0RczEhDfMaoeCoSAY2vuLFY9GftU3+ukRvs9VkNZb5tDQj11uEQByX34+jgtdg4RTdVTkxuRaqowlGmwH4cF2t78gN99IoVZImmY=,iv:UgeSAbCQLr+qWsMvVnx4eWtLtKuaMVwPb7TNa3e3xDU=,tag:cAJH7RiwEWazQQ41pk45Kg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNmRYN09oRTQvZ0RXYWVj
            NjY2MmVwOUh0SmN3TUltMFJvQkVTdW5JTmpvClhCT2ZvMW9Ham1hYjZTQ0tKMjIr
            S0x1dkUwSkx3RVJvYVJ4YmQzUXp0aEkKLS0tIFB0UGxHbVZXRXFsaGM4ck43Uk9y
            YVA1am9xUE5FNXJLZXF1TU1iQXJkRVkK7ym19UUsfCfWYx4/tN0ndZBUt9ruYHxU
            gkBH6ZwpqqV0bzvgiPTPUFJbda1Gcxd1o/oje+ufVvw5E4tO/FKO7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:04:28Z"
    mac: ENC[AES256_GCM,data:q2iy9NdAk6NiYzluO9mHkumPtGBQ+hroYnHYGAmpKSO0x0oRpuuIvHyLWK8WszxzDIqMFmiCjHP+okL9ryaKRnut5gGmTH6I6Eyyje8yDppkRcHFqM9VsRoCh1TtvKg32enLkn9NRGreQMo8jNwWQmTzeJ57O86QBaBqsyVtLV8=,iv:5/3IbGG+YUDo01gnu7Zs4lsQUbQj3hkimuU0MjIbk80=,tag:L7TsSPVV0q3IOqsEhouxag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
stringData:
    username: ENC[AES256_GCM,data:vbBo0fq8w0NkhQ8=,iv:ry6pn921LOwvhecdjpnNANT9iCoprtVIBDbroTOxKC0=,tag:4zSolqpvnHRLV3lqur1kNg==,type:str]
    email: ENC[AES256_GCM,data:lF4ttS5kFPpErpCmbdky3bro,iv:dy2m/dd+WLdTzVZSgypbg8kStjDLJywKe+tlgW66MXA=,tag:riCQ3DZBZxAXfAZOmBlVLw==,type:str]
    password: ENC[AES256_GCM,data:e4kAeH6FBl8wNKp1vjudlw==,iv:jFdVbrB7labcgcWIYdpicQB+akjpV0v9xRFyUJPHzng=,tag:OQ8L14JOnv7KpbpQxujfMw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNmRYN09oRTQvZ0RXYWVj
            NjY2MmVwOUh0SmN3TUltMFJvQkVTdW5JTmpvClhCT2ZvMW9Ham1hYjZTQ0tKMjIr
            S0x1dkUwSkx3RVJvYVJ4YmQzUXp0aEkKLS0tIFB0UGxHbVZXRXFsaGM4ck43Uk9y
            YVA1am9xUE5FNXJLZXF1TU1iQXJkRVkK7ym19UUsfCfWYx4/tN0ndZBUt9ruYHxU
            gkBH6ZwpqqV0bzvgiPTPUFJbda1Gcxd1o/oje+ufVvw5E4tO/FKO7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:04:28Z"
    mac: ENC[AES256_GCM,data:q2iy9NdAk6NiYzluO9mHkumPtGBQ+hroYnHYGAmpKSO0x0oRpuuIvHyLWK8WszxzDIqMFmiCjHP+okL9ryaKRnut5gGmTH6I6Eyyje8yDppkRcHFqM9VsRoCh1TtvKg32enLkn9NRGreQMo8jNwWQmTzeJ57O86QBaBqsyVtLV8=,iv:5/3IbGG+YUDo01gnu7Zs4lsQUbQj3hkimuU0MjIbk80=,tag:L7TsSPVV0q3IOqsEhouxag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
stringData:
    #ENC[AES256_GCM,data:tDkrvYReXodAtA==,iv:RmISgnuma1jIVnFV6ZFpJUCQeWVd9d/xPhheH7nVsKg=,tag:BehW02cfARPT+vmE7ebPJA==,type:comment]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:yFrG2tKG9hWl,iv:eIJrsFBAXCqJJPR359Y1QAlnG8wddf6CGMFyMT3LjlQ=,tag:XIAH/FPrCQaDblZehWIong==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:ofaWxDlqASqKnrNbb/AGZsxpCse22BiUbZWSvD3jLX4=,iv:XI5QwbfrI6VCSZptBnUagcAmr14HLGKN06ylEB8P/m8=,tag:kpEfTRAtJh5Q5kIFN9nl0w==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:1ENX0vL0t3DhCu2JRV5sQYmzsdWzyGB0DyD7t4lPOxJ/xV9GAcMV6xC9zx1pW9iW+eu24Ao5t/voIM+pMFcn27dXrKBm46BNqKpFPPWsQGQ=,iv:vE9K/40Wf2bHcTuUNeUiL2S3kREZhvquknKKFdmB/mM=,tag:42qxmIAuvQfMn2aSGiFTuA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNmRYN09oRTQvZ0RXYWVj
            NjY2MmVwOUh0SmN3TUltMFJvQkVTdW5JTmpvClhCT2ZvMW9Ham1hYjZTQ0tKMjIr
            S0x1dkUwSkx3RVJvYVJ4YmQzUXp0aEkKLS0tIFB0UGxHbVZXRXFsaGM4ck43Uk9y
            YVA1am9xUE5FNXJLZXF1TU1iQXJkRVkK7ym19UUsfCfWYx4/tN0ndZBUt9ruYHxU
            gkBH6ZwpqqV0bzvgiPTPUFJbda1Gcxd1o/oje+ufVvw5E4tO/FKO7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:04:28Z"
    mac: ENC[AES256_GCM,data:q2iy9NdAk6NiYzluO9mHkumPtGBQ+hroYnHYGAmpKSO0x0oRpuuIvHyLWK8WszxzDIqMFmiCjHP+okL9ryaKRnut5gGmTH6I6Eyyje8yDppkRcHFqM9VsRoCh1TtvKg32enLkn9NRGreQMo8jNwWQmTzeJ57O86QBaBqsyVtLV8=,iv:5/3IbGG+YUDo01gnu7Zs4lsQUbQj3hkimuU0MjIbk80=,tag:L7TsSPVV0q3IOqsEhouxag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-authentik-secret
stringData:
    key: ENC[AES256_GCM,data:EcOA/5LhTKmMUvRHUM5iyArBWdwxZDubXGcumRFNMWFCLZRDZNPWFA==,iv:3Ox/UE8Iew7Nti9eLMAnf8EBSIDipoo3dzYAacEJgAU=,tag:IZVlTDi/jnUmvX3Jfp2itw==,type:str]
    secret: ENC[AES256_GCM,data:RhLqfxO9YhIHoU7dy36JpDDla2xNVmHBMVTQKseIcuzAV63Edr2BI/5K54XmVhnaSw4c/2l1U/7oykC6NFLymMydr65ulwsON6lR1eEYwXmS+GYB/944lmqmmY+LbXtDJxM4STy58hasfymxpxseu/QrG8AkS0265nLYTkZm/MU=,iv:smcFySZWmuDxYbpKYb11R1lNUs8/6GbDUVNtiJNpP00=,tag:gtUgOVYQKAk2CsK7zFjBNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxNmRYN09oRTQvZ0RXYWVj
            NjY2MmVwOUh0SmN3TUltMFJvQkVTdW5JTmpvClhCT2ZvMW9Ham1hYjZTQ0tKMjIr
            S0x1dkUwSkx3RVJvYVJ4YmQzUXp0aEkKLS0tIFB0UGxHbVZXRXFsaGM4ck43Uk9y
            YVA1am9xUE5FNXJLZXF1TU1iQXJkRVkK7ym19UUsfCfWYx4/tN0ndZBUt9ruYHxU
            gkBH6ZwpqqV0bzvgiPTPUFJbda1Gcxd1o/oje+ufVvw5E4tO/FKO7A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:04:28Z"
    mac: ENC[AES256_GCM,data:q2iy9NdAk6NiYzluO9mHkumPtGBQ+hroYnHYGAmpKSO0x0oRpuuIvHyLWK8WszxzDIqMFmiCjHP+okL9ryaKRnut5gGmTH6I6Eyyje8yDppkRcHFqM9VsRoCh1TtvKg32enLkn9NRGreQMo8jNwWQmTzeJ57O86QBaBqsyVtLV8=,iv:5/3IbGG+YUDo01gnu7Zs4lsQUbQj3hkimuU0MjIbk80=,tag:L7TsSPVV0q3IOqsEhouxag==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
