apiVersion: v1
kind: Secret
metadata:
    name: forgejo-db-secret
stringData:
    ADMIN_TOKEN: ENC[AES256_GCM,data:6NmYMS2muJ+gSIoZ1BTIkP28zKhEfqimUeXAXtlv2xmlzyVwA7DhWSzbwJF4QGMk9Y4RaUQU8QlP0GeSqeILXl3a8AA+JUkTJGRAUods+CV6lpjFAcbFiRoHGs9I9qf8zqSnsyCduWhb9EIw9siqGVKQADqY3K31m67DLn2Gw0E=,iv:J0vexGuOYOvy7Fa9dJqgzxOUyHaOslserPtyjPVwALI=,tag:ZMPSvi+4hHJh6qi+mtzI7Q==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:26LOcXNBBJpOTR8mKKIAVVGj/cMo8GD52GvtR/pzOrr6vH9Wmqqg2uWs28qcrrQbbY1N++7sa0ICcxlc9zO1IL6BWni6OYMz/y509YXdzQi+Fhh/CMqqNYHhEdJrU1GEhB8sLK/8CaYH2FMrChbLpkqjJAdSOezMreD6GP0g5exb06fZI6bKOCHanTsn+2eM1z0Boz9ZcglR1v7H7FpT25UBdopjMSmAv4056x3QUNdbLMSxLB8fTPBqBFsoWCMKUpJsDJz9DfW3Lc4Tchsq97VWlvc=,iv:atdj7dZbijS5UcDqoIQ/kCSbgzfti9iiphSqU2ssRH4=,tag:VcYgI+yXz3xGLJy3XhxJjw==,type:str]
    #ENC[AES256_GCM,data:AsZFvghNC8W6Jpup1ko=,iv:Ve3SSk4iOxe32QuDAwbMO4M18L/qB+t9JPof+IDoU+4=,tag:YvXogvxbp13tqrjryGaQNg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:Xck145lhHQ==,iv:9a8T/Naud/a4UUj1agUYC1GPtsPjlIKTqahvn2D9b1Y=,tag:gtGmsdo6NcoAQZL8pTmQ7A==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:cDNJ115CyvGDfUS85G16yR5gY51eOdb/HNbr4It7QgBTZsa3aC0rwg==,iv:9dxIAeAEZAv31JsbrBeApYZp9u9cYdJaWWj1IEpwNkY=,tag:FgtMDQ6RLNtxBGvOzY8UIw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:25riR69K3FtwK4sv9C3v,iv:E5Bcnl5CeTL6kbzJYJUWE/LVPLxxQDid4Akb3m8kgRU=,tag:rRwYOqsqX+DLtRxFvKjBEg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:b58NLNTW4PCo02duoGb3buEfovXGVZ5KuBQvIA2K/5pkExQ2fyikkI4OAAFQu6XZDqb5xaKA+VFaUHQSUeRxvvenS843oUTs3cpZ3xdwOezo8gKVz32CQRYN6K1/9Hy+r80eNRPhPb89dMF9zBpE/jhbNRVulR+l9utMTegdXiY=,iv:0Rk50no7spAqKHg3slNOdooPRjJRNrUY5zDhvgzlh1g=,tag:Oe8Po7E9DoUXoYryynKf/w==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:pDzfU3BdIIk3rKgy5ahg7ItreFVeUSCBODOZKTMj5IPNljqemYNXORiTbebY+h4x2jU/bMk6KGCa+3aRFK3Exs3GK5ce+xi2KusX1kjThAPUe2nVk8dk2Psmip/FfeDqTmU270EP4XCW79JZNDuyE5T83BTnJTzpgAu7s+KWHEE=,iv:qzFhdjkEgEW+NAOMYHkiGAqhmv9x16aVT7/bC3rUGzg=,tag:7MB0mK/cDY5Bd+nMY1IciQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVHFSaEJqdTdEOURMRmNo
            bHBKY0ZIZFdpRWVrN3JPUUQ1Z3luUlNYR2tnCnd6ajl3OTJtZlVZUy9Ga0RVWUNI
            WHZLK0RSeUZXSEh1RDBiV0p1c3Y0bm8KLS0tIDRXRDFhUzZQanZCdlMxM3ozaktx
            Z3kxZlNURGM3Q2cyZDZvYjZuaUwwck0K4ehxKnWq3D5k4f8IXQRIcKjaQ8OUsQB3
            Wdx7ELJD7mXL7TbV8W6AWsO+HMbC++HbgcBx91q3uCCcLCjnC5KCaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T13:38:38Z"
    mac: ENC[AES256_GCM,data:NaKiZ0Q2Q9MUbxpfXEqCwFudsA7ZfckfwTXLaRvlvICeYvPxAy1mLedvxMhSeWYtrPVws6dufIwdIVs6oOdWXc0WUXOR9lfEAJ6fi7wYz+J6EVMfaNzIiYCa+wE6AOuNCPbm2S3ZCKexIbXhbmo1Apb+BGUomyQZolBXulLiTXU=,iv:bVSGWcZklG1ePMbVCTQtLgaUTHdIwEWo/esdwjPgbm4=,tag:aHsnan29xX1EcbvwoMnOlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-admin-secret
stringData:
    username: ENC[AES256_GCM,data:i92QczxTHO17K84=,iv:L/5HKPaGrDkOt2oTd+2I+mCqHTJg/AFKMJR5J6c8IV8=,tag:5/mVWleC9qmQs7trZ7H6yg==,type:str]
    email: ENC[AES256_GCM,data:IgY9QZuu1jUuk6eGvunfHdeT,iv:RpBTJ6vNm13oDZmK+qid8D+i4Wgpn/3QcMjV9nOaygY=,tag:qjdRVtxVBHENzxsf+PqVtg==,type:str]
    password: ENC[AES256_GCM,data:yOrQLcHK3H0mUXyuET0yAQ==,iv:PYKgifKUZ48PuQUp8XBEmKYZbkDpm3NYXctFU83oACg=,tag:xOVQH0PL6zczNMD+9ySv+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVHFSaEJqdTdEOURMRmNo
            bHBKY0ZIZFdpRWVrN3JPUUQ1Z3luUlNYR2tnCnd6ajl3OTJtZlVZUy9Ga0RVWUNI
            WHZLK0RSeUZXSEh1RDBiV0p1c3Y0bm8KLS0tIDRXRDFhUzZQanZCdlMxM3ozaktx
            Z3kxZlNURGM3Q2cyZDZvYjZuaUwwck0K4ehxKnWq3D5k4f8IXQRIcKjaQ8OUsQB3
            Wdx7ELJD7mXL7TbV8W6AWsO+HMbC++HbgcBx91q3uCCcLCjnC5KCaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T13:38:38Z"
    mac: ENC[AES256_GCM,data:NaKiZ0Q2Q9MUbxpfXEqCwFudsA7ZfckfwTXLaRvlvICeYvPxAy1mLedvxMhSeWYtrPVws6dufIwdIVs6oOdWXc0WUXOR9lfEAJ6fi7wYz+J6EVMfaNzIiYCa+wE6AOuNCPbm2S3ZCKexIbXhbmo1Apb+BGUomyQZolBXulLiTXU=,iv:bVSGWcZklG1ePMbVCTQtLgaUTHdIwEWo/esdwjPgbm4=,tag:aHsnan29xX1EcbvwoMnOlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
    name: forgejo-secret
stringData:
    #ENC[AES256_GCM,data:5ZZe47F7KtFENQ==,iv:0yyryQXwc1O0ERdoCPPG6XehSkOOA5uO89kyBBSe0XU=,tag:F3tNEdTPgGmpGgUZ9BNMbg==,type:comment]
    MINIO_ACCESS_KEY: ENC[AES256_GCM,data:M3KLHHF0LlM4,iv:qoYuFO9+N5/DSsoC0vWAcfN7Bzq8I052XZBuW706/WU=,tag:ahrqgbO43p5sTaMJ2vggaA==,type:str]
    MINIO_SECRET_KEY: ENC[AES256_GCM,data:JndxgXYKqDq7t+QY7cShrwI/X3vSEQYv94HMnQZMVi0=,iv:apk99ZrfgTROPsdlQnM+/tYTs8eCqKOUR6lBJMEzMJQ=,tag:SMRNvOFYQwEIW3GgHrn0mg==,type:str]
    SECRET_KEY: ENC[AES256_GCM,data:gtLHYEfa4xA2W0/ae6w3WLrX2P17hMCL73fCexo2R29coGQq7akdhSR6OrLQzc/OF8uQW8L2LGHpKDcCPeZtAIyLWEFmArgjJFmEIdCCMQw=,iv:C8cUiqc/Jg3iYT7xN+x2KRrnJ7tUW4QgAXApC8pii6o=,tag:9YfZJAK1Y8s9FXLU11VYhw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlVHFSaEJqdTdEOURMRmNo
            bHBKY0ZIZFdpRWVrN3JPUUQ1Z3luUlNYR2tnCnd6ajl3OTJtZlVZUy9Ga0RVWUNI
            WHZLK0RSeUZXSEh1RDBiV0p1c3Y0bm8KLS0tIDRXRDFhUzZQanZCdlMxM3ozaktx
            Z3kxZlNURGM3Q2cyZDZvYjZuaUwwck0K4ehxKnWq3D5k4f8IXQRIcKjaQ8OUsQB3
            Wdx7ELJD7mXL7TbV8W6AWsO+HMbC++HbgcBx91q3uCCcLCjnC5KCaQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-15T13:38:38Z"
    mac: ENC[AES256_GCM,data:NaKiZ0Q2Q9MUbxpfXEqCwFudsA7ZfckfwTXLaRvlvICeYvPxAy1mLedvxMhSeWYtrPVws6dufIwdIVs6oOdWXc0WUXOR9lfEAJ6fi7wYz+J6EVMfaNzIiYCa+wE6AOuNCPbm2S3ZCKexIbXhbmo1Apb+BGUomyQZolBXulLiTXU=,iv:bVSGWcZklG1ePMbVCTQtLgaUTHdIwEWo/esdwjPgbm4=,tag:aHsnan29xX1EcbvwoMnOlA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
