---
image:
  repository: itzg/mc-router
  # renovate: datasource=docker depName=itzg/mc-router
  tag: 1.46.4@sha256:92766cd72262e4e13569463708af2bb87457ee5b3ba914b72ccbc8b09f8eb384
  pullPolicy: IfNotPresent

services:
  minecraft:
    type: LoadBalancer
    port: 25565
    annotations:
      lbipam.cilium.io/ips: 10.0.60.16 # pinned so the router port-forward stays valid

minecraftRouter:
  mappings:
    - externalHostname: "mc.darkflame.dev"
      host: minecraft.games.svc.cluster.local
      port: 25565
  autoScale:
    up: { enabled: false }
    down: { enabled: false }

resources:
  requests:
    cpu: 10m
    memory: 32Mi
  limits:
    memory: 64Mi
