# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:CT2AUhqaNvHBhanvfVEWc2ArIZNFb9xuSryjGYWa97addoSVhn8J4Cjwm4aTmyWd4/naBxfasWDzEQOnTIDpcvRe/dJcwEs82X6c56uhGfVc4vbwpuU0COe6GP0otpnKVBRllbcZFqj87whI8HsVKh8GFDbldeoPDvwEBqZzye8fWfbnPnNORkIe985OQkan5bCCqyxOF1M81g/YEjW/X9j8Om7GWc2fNqN2jbLkIc7ugNta,iv:L5vjte8blSzOfG8raNOMb5mYAGpyGXOJq1jvVLOvuHo=,tag:stuHTe1TbDmQhCsuh05YFQ==,type:str]
sops:
  age:
    - recipient: age1pk4hw4gdplvq3tz6ma96hx3ja4w303ld5n5x82yqzyhj4g45qadqq9nf4n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEMVRURWdYQjhBV2cvU2hN
        MXpjVEZXSUJGOXZuKzF6ekdieUZOUUFMSkRNCmMwTTJwcjRmRUluQm9GY1Q3M0Zx
        bnVwaGo4L0J1VU5keHdpRVdwN1pwQVUKLS0tIGNWOXJLa252SmRZdTQyRnE1bDd1
        cmJ6RzYyVk4vb01VM1hTOEtiNExwSzgKkPs8LUCWrwhWjntQBlPc6mpNZV2kMjIY
        yiQ+WMBaEb1FMPV1rCvw1dmeTxhhaQppGTQyXYlj846zCsThgdVdlQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-25T13:03:57Z"
  mac: ENC[AES256_GCM,data:L27KGN9tilih9Qg85qx6ZTQWWvQsq3biAP14FCapB59v+Il9AnZ2w1geFAr5PY46PXRvNm0d4DlmoHB7CRheceUzXhh04S/BZbZlx3F5Udo38vZOvgRDQ6l2UMZQdJzbf7TPWRGDhlPpLMB5TRd74qGaCAKmgEp5E4wgpsCPS+s=,iv:ZGegc+CxM2XYxhEqVpEwfk1YoH3uYjlkkt5xtvb+Wx0=,tag:lJqRtjqO6maGWZFHvL+gew==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
