# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:if15A+cRdj4m9qtUDZmUwg1jWhAoSy8B2H+1ffHTISbuFbzCwDRJcF6OSiqiQqE20AG+eM5H43T4idcwEoNSv/zbfkijsJFlC4CsNG3yeHxRDxDoajpvS7nZObai30ankzD/P/vK4GvQTX75H6YsIKaWymVsXnMzcyMI1MZQRElrny12GzMZfhXeH9P0Bm9IX7SnzkvYSSvuqYG5qR1+5Gi8fXB2L5tt0OmlA3C7027i8ZTh,iv:9WZe/mmRHkiXiYkjimo07Qj7bImPMmBEWeArQsDCTps=,tag:8BY8XZvv4F6YMwgr5He04g==,type:str]
sops:
  age:
    - recipient: age1pk4hw4gdplvq3tz6ma96hx3ja4w303ld5n5x82yqzyhj4g45qadqq9nf4n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcXNZQ3pOTHlhRUdOUVlH
        UzR1WFMwYkpwdnAvd0xwQXcyb3QwckFZKzBRClY5b0w0SDBNVEwrSmprVGI0eXJG
        VWsrbnR4VExSbDlydDNMdGg0ZldyQkEKLS0tIElPenl2WG1WUzhxSjAvYm5jai9q
        a2xUMDY2cnhOOFVINFpkRlZhWWx2UU0Kue3YBYYnu8oTp/fWZpR9sviMpi/A2lSF
        0bHJNRsr7OYtZslm9ypq25jmAOSVJEVEUTPuAixfy27ZeZFWRBabAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-25T13:54:26Z"
  mac: ENC[AES256_GCM,data:0pcyr8/pvrRkg2HeDn+sPkPLbwNz0ZpWTW2+DytB8RV/NUU03dw32Lo+HRVPoOUpbGJVFg+mOh03i+f/mlJ5VMFSZg+6DCvPD3bMS1Z5ohFzoO2OgiOpkkind9GtBw0pBMxHjDUbKWuy/iHxUOgBulXn8JnKF8jr49QHA8AOuN4=,iv:YZ95Y4htQjCXGYyQ0W2q3qTLjDY1onq8YgY67YqwK54=,tag:I92PXqOBa19na2TkPTGpRA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
