---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: paperless-secret
    template:
      data:
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
            {
              "openid_connect": {
                  "APPS": [
                      {
                          "provider_id": "authentik",
                          "name": "Authentik",
                          "client_id": "{{ .OIDC_CLIENT_ID }}",
                          "secret": "{{ .OIDC_CLIENT_SECRET }}",
                          "settings": {
                              "server_url": "https://auth.darkflame.dev/application/o/paperless/.well-known/openid-configuration"
                          }
                      }
                  ]
              }
            }
  data:
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /paperless/oauth2-client-id
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /paperless/oauth2-client-secret
  - secretKey: PAPERLESS_SECRET_KEY
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /paperless/secret-key
