---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: phoenix
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    link.argocd.argoproj.io/external-link: https://phoenix.darkflame.dev
    argocd.argoproj.io/sync-wave: '3'
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Darkflame72/home-ops.git"
      path: apps/observability/phoenix
      targetRevision: main
      ref: repo
    - repoURL: registry-1.docker.io/arizephoenix
      chart: phoenix-helm
      targetRevision: 12.0.17
      helm:
        releaseName: phoenix
        valueFiles:
          - $repo/apps/observability/phoenix/values.yaml
  destination:
    name: in-cluster
    namespace: observability
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
