apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: notifications-controller
    argocd.argoproj.io/instance: argo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  context: |
    argocdUrl: https://cd.darkflame.dev
  service.github: |
    appID: $githubAppId
    installationID: $githubAppInstallationId
    privateKey: $githubAppPrivateKey
  templates: |
    github-status: |
      message: |
        repo: Darkflame72/home-ops
        revision: {{.app.status.sync.revision}}
        state: '{{if eq .app.status.operationState.phase "Succeeded"}}success{{else if eq .app.status.operationState.phase "Failed"}}failure{{else}}pending{{end}}'
        targetURL: {{.context.argocdUrl}}/applications/{{.app.metadata.name}}
  triggers: |
    on-sync-succeeded: |
      when: app.status.operationState.phase in ['Succeeded']
      send:
        - github-status
    on-sync-failed: |
      when: app.status.operationState.phase in ['Error', 'Failed']
      send:
        - github-status
    on-sync-running: |
      when: app.status.operationState.phase in ['Running']
      send:
        - github-status
