apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-secret
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-notifications
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: notifications-controller
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: argocd-notifications-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        githubAppPrivateKey: "{{ .githubAppPrivateKey }}"
        githubAppId: "{{ .githubAppId }}"
        githubAppInstallationId: "{{ .githubAppInstallationId }}"
  data:
    - secretKey: githubAppPrivateKey
      remoteRef:
        key: /argocd/github-app-private-key
    - secretKey: githubAppId
      remoteRef:
        key: /argocd/github-app-id
    - secretKey: githubAppInstallationId
      remoteRef:
        key: /argocd/github-app-installation-id
