---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafanaserviceaccount_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaServiceAccount
metadata:
  name: mcp-grafana
  namespace: observability
spec:
  instanceName: grafana
  role: Viewer
  tokens:
    - name: mcp-grafana-token
      secretName: grafana-mcp-token
