---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json
controllers:
  grafana-mcp:
    containers:
      app:
        image:
          repository: grafana/mcp-grafana
          tag: latest@sha256:da49d967b72ebb4d08617295ef196b53b3294a9c1d484775dd3315190a166c55
        env:
          GRAFANA_URL: "http://grafana-service.observability.svc.cluster.local:3000"
          GRAFANA_SERVICE_ACCOUNT_TOKEN:
            valueFrom:
              secretKeyRef:
                name: grafana-mcp-token
                key: token
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            memory: 256Mi
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    seccompProfile:
      type: RuntimeDefault
service:
  app:
    ports:
      http:
        port: 8000
        appProtocol: agentgateway.dev/mcp
