githubConfigUrl: "https://github.com/Darkflame72/home-ops"
githubConfigSecret: arc-github-secret

minRunners: 0
maxRunners: 3

controllerServiceAccount:
  namespace: arc-system
  name: arc-controller-gha-rs-controller
