# No yaml-language-server schema available: grafana/grafana-operator
namespaceScope: false

resources:
  limits:
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 128Mi

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop: [ALL]

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  seccompProfile:
    type: RuntimeDefault
