---
# No yaml-language-server schema available: piraeusdatastore/helm-charts (no values.schema.json)
controller:
  replicaCount: 2
  serviceMonitor:
    create: true
  resources:
    requests:
      cpu: 10m
      memory: 96Mi
    limits:
      memory: 384Mi
webhook:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      memory: 128Mi
