# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:NAwsa7E/JwPCaEBinT629Qv6iGln9Czs9jxKEJKnyqZJAB4ECAHaTg==,iv:BjcA8FALPBEFtL8VdvzKjQOl6YIZXuFUl3JoGa2+f14=,tag:MilldE6uTkEojUTNYb+CUg==,type:str]
sops:
  age:
    - recipient: age1pk4hw4gdplvq3tz6ma96hx3ja4w303ld5n5x82yqzyhj4g45qadqq9nf4n
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaLzVQNjFrenMyTG5rdHRr
        Q2FUVEJlK1VGaDZ2bmthNmlCb0UwR040aWpzCmNMSCtGZ1MrTG81dHFHZjd4aDdQ
        MHA5cVVVbTQrTEZMSFFnQlkwWUR2UUkKLS0tICtQbDI1ZlFKb3pLaWZDQ3RYN2Ev
        YzRiRWRjSnlrUGU3TUFkS0Y4eXMwWTQKCmHACZxkTual8dC1OF15+HAnXy94FrVi
        ClXsF/x/3MclhceZ0ZRIrN2gRnbmyvW3SFtHNI6tthIrd6/AcOpmZA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-25T13:54:26Z"
  mac: ENC[AES256_GCM,data:HLbS+nSdN3fB3B/hisXRhKJyC3a9P3inoAQzl6mWyIVV8bb8vF1SMZHI+PYdC/byrEgWYGUXjzpDhI076DMsiyb4TznTd3q95CVKaRi3eT6Qka684r1Ufl1/vTNhK/jvgg1KSZ0ibJFzQZqU+NpuLA5+HMgbPHaG3QdXEVxXHGg=,iv:oRFDO6es2tb3NTW7gsb70qZOlVkWJQ2gxxeiJqCleKI=,tag:/Y9BUXFgiiAMM/oDrCiGuA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
