---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: opencloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: opencloud-secret
  data:
  - secretKey: INITIAL_ADMIN_PASSWORD
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /opencloud/admin-password
