---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spegel
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Darkflame72/home-ops.git"
      path: apps/kube-system/spegel
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/spegel-org/helm-charts
      chart: spegel
      targetRevision: 0.5.1
      helm:
        releaseName: spegel
        valueFiles:
          - $repo/apps/kube-system/spegel/values.yaml
  destination:
    name: in-cluster
    namespace: kube-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true