# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/refs/heads/main/charts/other/app-template/values.schema.json
controllers:
  bar-assistant:
    type: statefulset
    containers:
      api:
        image:
          repository: ghcr.io/karlomikus/barassistant
          tag: 5.15.3@sha256:2b2d228d1f1ad7cfec0aba4e5e7d0ab84c867847709917017f20a792a3012021
        env:
          APP_URL: &api-url "https://bar.darkflame.dev/bar"
          MEILISEARCH_HOST: http://localhost:7700
          AUTHENTIK_BASE_URL: "https://auth.darkflame.dev/"
          AUTHENTIK_CLIENT_ID:
            valueFrom:
              secretKeyRef:
                name: "bar-assistant-secret"
                key: AUTHENTIK_CLIENT_ID
          AUTHENTIK_CLIENT_SECRET:
            valueFrom:
              secretKeyRef:
                name: "bar-assistant-secret"
                key: AUTHENTIK_CLIENT_SECRET
          AUTHENTIK_REDIRECT_URI: "https://bar.darkflame.dev/oauth/callback"
          MEILISEARCH_KEY:
            valueFrom:
              secretKeyRef:
                name: "bar-assistant-secret"
                key: meili-master-key
          REDIS_HOST: dragonfly.database.svc.cluster.local
          CACHE_DRIVER: redis
          SESSION_DRIVER: redis
          ALLOW_REGISTRATION: false
          ENABLE_PASSWORD_LOGIN: false
      search:
        image:
          repository: docker.io/getmeili/meilisearch
          tag: v1.49.0@sha256:bdc7d7e7939911c40d88d6bcd01f9c72c81f7293135916d48bce241569f721bd
        env:
          MEILI_ENV: production
          MEILI_MASTER_KEY:
            valueFrom:
              secretKeyRef:
                name: "bar-assistant-secret"
                key: meili-master-key
          MEILI_NO_ANALYTICS: true
          MEILI_EXPERIMENTAL_DUMPLESS_UPGRADE: true
  frontend:
    containers:
      salt-rim:
        image:
          repository: ghcr.io/karlomikus/salt-rim
          tag: 4.15.0@sha256:2a764abf8bd1717257ec65db9cb4034406fc77968d46570a776004ca5ae2d192
        env:
          API_URL: *api-url
          MEILISEARCH_URL: "https://bar.darkflame.dev/search"
service:
  backend:
    controller: bar-assistant
    ports:
      api:
        port: &port 8080
      search:
        port: &search-port 7700
  frontend:
    controller: frontend
    ports:
      http:
        port: *port
route:
  internal:
    enabled: true
    kind: HTTPRoute
    parentRefs:
      - name: envoy-internal
        namespace: network
        sectionName: https
    hostnames:
      - "bar.darkflame.dev"
    rules:
      - matches:
        - path:
            type: PathPrefix
            value: "/bar"
        filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"
        backendRefs:
        - name: bar-assistant-backend
          port: *port
      - matches:
        - path:
            type: PathPrefix
            value: "/search"
        filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: "/"
        backendRefs:
        - name: bar-assistant-backend
          port: *search-port
      - matches:
        - path:
            type: PathPrefix
            value: /
        backendRefs:
        - name: bar-assistant-frontend
          port: *port
persistence:
  data:
    existingClaim: "bar"
    advancedMounts:
      bar-assistant:
        api:
          - path: /var/www/cocktails/storage/bar-assistant
  search:
    suffix: search
    enabled: true
    retain: true
    storageClass: openebs-hostpath
    accessMode: ReadWriteOnce
    size: 1Gi
    advancedMounts:
      bar-assistant:
        search:
          - path: /meili_data
defaultPodOptions:
  securityContext:
    fsGroup: 33
