---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volsync.io/backup: "true"
  name: vaultwarden
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
