apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:MQFI3nucd8WejdD2qA==,iv:6uPzy2gzZL+szVsqQ3MwbrPf4SKjq92wXA5Qt0jSZ10=,tag:PqzQoJP9MTy3wPWjnwhdrg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:p4lA0Q7I22FxRp2EHScsUULD,iv:1+KKQvFuR1IDQZ2jdDY4FCn0hjO9BCqpyBoNlpjV0CQ=,tag:eVf8gmF1aCMPSi889WQgyA==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:8NujrrbkNGJhsn4/4O1WaX/XY2Th9f80XR68EYrQJIOo9ZyW,iv:jDkdSNt/jTYAFWugAfX5+caryEDAWzvdGRauw+uc2Ak=,tag:bTC2xm8oms3bFtarTklhEw==,type:str]
    NOREPLY_EMAIL: ENC[AES256_GCM,data:JnufJTUyFwCACtDpQlx/1BQm6Owt,iv:H8//v6YFEdBP70IN1GFkKWNbOeGJEOaLqRscO2pxqiw=,tag:g4n17FGol3YGcWNyKSLafw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHVzNRVzBBU1o2d1cwaFoz
            eDg3akN1bUNmdTBJVWgxaklVRjdKK2w1WDFVCmsvNGlOUHpPVVhRWXJDUjVOa1dC
            ajE1UEd6dDN1cWVXNHJzdUlEelNvSlkKLS0tIDJLTi9iZmMxek9OZEw0TlI4Y2g4
            MVphcThIVExPaDU2bW41RWk4K280MWsK6RD+nuvEv3ftHStGE8QqFgvlQ4hmI+0Q
            f7ua/pXnmSUgSIBgyVW1ds+iN2SOEFg9oCEKnizVp/FsBL0wWwFJrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:10:44Z"
    mac: ENC[AES256_GCM,data:lGvXqSyvnldrsg7GwsTPAZikE0HTYRCqAYtCBTdQ1zUg5MthKLNxY63XJp61RJ2dCx3K9VCyVJI1hQbExTLfyGtOAEENTVOyV40LYER1l7fQ+rEnH9ctHRNk5j3m1mD0Rj00kxfTkhm0xgCZrLHz4Qq464W+1Lv3jUVXkU2piwQ=,iv:wIk1yNVO/K+DwZTAcNSxO4q4aEoUm/J/McOEBzvZZPI=,tag:awWHlmC6FLsxKEwycSKAGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
