apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:Psf3Wxb+E7I62doM8g==,iv:BxGI5o+BHtWajnSIxDSL58jd7uRpuTEeDxs5RgD+NhE=,tag:CVcN3ORbOJLaBnZwd/1Q9A==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:NDdbGt5uVRg6Y6YaXdmPjWuD,iv:X9jBBlruIT3lXGlioREKQSRU+CGvbOUzUqq1gTCNl3w=,tag:t38QPl+FWem2OtiSOGDLIg==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Ka0vbG2aujVz9dC0YBHlp81pdawh1gtouz7SwvwUTtgrs+d0,iv:7WreGin8zJTmFp+CL8AvbUsArwP5YNOrZB8+N7N2cJc=,tag:4jO8T4IJv0NOUp+FSl2ImA==,type:str]
    NOREPLY_EMAIL: ENC[AES256_GCM,data:830ktZhQYeTzCggTd43NhXNVwBGS,iv:/tg9dRlWWCgdgcrG4U33qQPB04J0jbgpGmHHFLb5swQ=,tag:h00pO9mPYSQQFwD6+qpgNg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvdDdlMjVnaEp4YXpvOEJS
            QlVzQnhVK2E1Q1c3My9ReHVIWExQSVZIbng0CnRwSCtsNTFnZXUzNk16c2RjVE1G
            Z1ZxYm1Ra2MyOVNUeE9oL0xrU2J4eU0KLS0tIFczbDlzS3VNRS9PUHZKSUZWS2d6
            bFpJeHRnS2lSSmtoby9hOEw4T0NXMmcKWkqtMOYS2T7WuEr/PY26Uy4Ue4UwYMRc
            nArC5MwpjSA13V/KkKzw7C2A5B97TtT2uPxhcTyw5Izt5pmsCoNcLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T13:05:31Z"
    mac: ENC[AES256_GCM,data:AUxydzVgi8OybQ+bHu/3PT2ci3GiWgY7oUdK1aeOh+WwzdB6urWkntQcy43mxYglEodThLqtmcVP8c64cJ+gol0WQSSjKRqyus40mKRsHJsWJu3ViNDLDwlAxhYEtt7tGNHQCNZGg8fJjLmZnqHsad7D+Gbelu0rE2UMbYzDznk=,iv:EVScrzw9Tx/Z5iuhSRxCPGpWw01Q606aGjg7LmsL1ew=,tag:Q9h5KawZgZUcz9bcGKJmKA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
