apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:aqxtnQZTsL43+ZAkDA==,iv:Scbw+dHkVu7l8HErYtaTzL4q8EhFB8F2qIPZy7DMtd4=,tag:h73bb+rmaDSMvezI9V3Qzg==,type:str]
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:E/LSVpmNU6rWtpxRsM6uqDDK,iv:iEiIA8zReO0O33FtP7IZtsg7UmxDZH/L58DDrrDb+ds=,tag:AVq44DmZFEKCEOOzMcoqFQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:Bzm+4ddYV85F9gBALZHfUDK5PVQtx+NzXoig1/XcX44GlYUB,iv:Gkeh4uXi/sZ6vF0gVPj4JOFt20jzR3BD0OPOrncrUIs=,tag:SsJCMQwSUzKEzKgs17s+gw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWUFQdVF3bXgvd0JtRkVh
            aTRRd2J3VmNjQmRYZkZRRlA1Y0RpV1c2SUZzCjFsVnhFc0ZPVUh5clVEeDViTTVS
            dVdlUThLRDJ1TTErNTBEWm9yS2VrOXMKLS0tIHpDcG13ZjZxeURTRVlrdXJ6YVox
            QXREdk1mTkV5b3VQOFFZd3BuOEE4SEUKy/8Af6nFGriTb0WJIKIyLtAAw3gCKbrv
            gv9Ib48QC2Rfbi4r01xRpiuPrCtItATJkoKhJH0cX68XiSFSOCQ/zw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T12:36:18Z"
    mac: ENC[AES256_GCM,data:FG1sxZ+nX0BYc/ygm97S0KPay2l5XJj5PdxTRjdH4j8QRbgya4rtAdG9ZkLb1YUdyC7kJWSwz2ZWmroIBxloGU47lokDLvb45NKFd+4J/AwfHN4iz4JoGP8mp4Eg6RFTPmwhOzC6CJVVzXLsNsXQ70akdXL8oOGYcL3ea9On7c4=,iv:5jisw9tU3zJqXbj0OPpvahzCzhFSny29IrWhZ10QEKU=,tag:I8G8G8ezJsFs6a09l22PMA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
