---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crosscut-runners
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '5'
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Darkflame72/home-ops.git"
      path: apps/arc/crosscut-runners
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/actions/actions-runner-controller-charts
      chart: gha-runner-scale-set
      targetRevision: 0.15.0
      helm:
        releaseName: crosscut-runners
        valueFiles:
          - $repo/apps/arc/crosscut-runners/values.yaml
  destination:
    name: in-cluster
    namespace: arc-runners
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
