---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Darkflame72/home-ops.git"
      path: apps/external-secrets/external-secrets
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/external-secrets/charts
      chart: external-secrets
      targetRevision: 1.3.2
      helm:
        releaseName: external-secrets
        valueFiles:
          - $repo/apps/external-secrets/external-secrets/values.yaml
  destination:
    name: in-cluster
    namespace: external-secrets
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
