# yaml-language-server: $schema=https://raw.githubusercontent.com/cloudnative-pg/charts/main/charts/cloudnative-pg/values.schema.json
crds:
  create: true
resources:
  requests:
    cpu: 10m
    memory: 128Mi
  limits:
    memory: 512Mi
monitoring:
  podMonitorEnabled: true
