apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:BqZ5ICqblgA=,iv:mRIsEx7VW/tGKBXufK++wAXX7pe/ODuFfAciHFbzY0I=,tag:6QQa5TJJ7uRQCNS9TuMPeA==,type:str]
    password: ENC[AES256_GCM,data:xv0I/L7LmOjCROUWX/6DK+Cx9LFd5V75DOMeRzZBND1oR05DPQqLjqPN3BIa9uZgiJIums+GNTBPbVve1GCxTSe/8GQXHM2ckLMkp1MfUwEK679/A138+lHeDdfQjAAe6uUEzMXYBVeI+B30+otcDW5ghke7c6FPn7NP2xHd938=,iv:+f9RTXbOhLO6QNZBcpjLdLNHlrlvMDMvEacTUf4Szkc=,tag:x6RAVQfm2Q+vne1ZGV5mKQ==,type:str]
    aws-access-key-id: ENC[AES256_GCM,data:RvSp+1OSN92g,iv:VqSbBQJtg+3DuHujPMMJnyDyZ8KkW/8ydN+2uWtHblw=,tag:emak/obJXQoMVFi9GuM5Zw==,type:str]
    aws-secret-access-key: ENC[AES256_GCM,data:1fqSS8ymJTW6tKpMvwuJpPtWOUoEKsCyH1lYILCRazE=,iv:4naLhrgHeiAKDNNw2bAuGkkutlGTHeDlvApNEK6zfvo=,tag:9dhNcxqZ9KZu0TYr+cB50Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVkF1T1lMbU1FOUpYTTNn
            QUVPZmdsM0V4K1UrdEsxTDh1L0FVZ1RrSWxrCnlXWTBXaW9pbDdiSmttcS9raThW
            TVVsS1JRRE0rdVpBd3Vxa2s5cDJGa2MKLS0tIGt4bGxrTjlXVndkck9TNW1nQVhu
            RTZvQnZEcTZmUDVQVlcwM2VoS2FPcWMKh84gmFPN8FJR7VxlXECiGIaV2lgGptHR
            wrF909EqizbhCdXq1imhcb84cH029NNaW3Kk0DlUCgn586ZWiccQ8Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T06:00:27Z"
    mac: ENC[AES256_GCM,data:zB1L0gY6gCQMLOvCwl7PCQ386ImV/ugkltQ6lBIxq95y94gniaLJTGpKvvwHHuMNHntMdWGp17a/leG2aeIbJGE6FvlXGurvpYTincnyJjPY9EBYlkFtLb/Evx4lst+qRPIZ37QLBgTayCpJUsaZZaKCqtGZ41xY8s+wfR2M9Ts=,iv:DVeWD4DDMvzTZ6YQN/O1qFen2FGEyHGghnuWidf2uLg=,tag:+uYxb27lWOvfHVjMTgdmEQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
