apiVersion: v1
kind: Secret
metadata:
    name: cloudnative-pg-secret
stringData:
    username: ENC[AES256_GCM,data:BZlzNL57Y5c=,iv:p2g4FjgYr0uj7C/kuuq4awKtoZQdWYTHjCCOYzZoHCg=,tag:QqETZ7Lx7yHeDi9bi0FbWw==,type:str]
    password: ENC[AES256_GCM,data:e4AIGdvDwYI3QiR34sBUVS82KZBCyRDFSlVEAPSCkJkoUEW1xtSZKNGdCVAexGQZYfC01MPkqHyNXURH3rq5dTEjaqp6O5LjMxADcejsMgjhDq5HA+TIVKDBZ8hJdDZQo6OWIersmWE19Dl0WtUUqqKEX4BRTs5alFrYOC3RvC0=,iv:nbvKNxNkY6bK2KEx/6kJ/6+9Oqpcgw8LaQfeRrYUmlI=,tag:VzchIErTG+I79AKtUF7h7A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0azZPakV4bk1lNUNrRjk0
            bEZtMmhTdjcrMkVkemxTZ1I3NDA1WE5vYldVClovR0VyUzNFeis4VG5IMC9YMzh0
            UEprOXI1T2o0anY5R2RGdEJMZ2p3R0EKLS0tIGFGY1l6MHdzQTNSYm45SnRGMzBs
            SFpKM2NVbVUwRGlscndja0d1SGpTYU0KBxRDB+wYAyUL5aYsSecaFMcv4pM6FhMF
            5v5OPsESdFKkMVQb4ZwJe3U+jFtJjOrT1aVoVaD1jDDA3g8eEwyFsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T13:13:22Z"
    mac: ENC[AES256_GCM,data:s/PhDq/xnNYeZ+OqEN1khkyIjAIfsnz7WuVM6k7MCNTqZiijHpsrOSAUtfvfMUTOw3tbKalQJXFNjjX1bmEYJuR2UjbEOIaIocVCKq94rSKI2ntS/a0M1qUfsk8RbvKf9N/nvEHASUEwVV7NpR8OqnNcT64KrqOBTGl4DPQd0D4=,iv:BOKf9Bnbn5e3Af6/8J3aJGYdvE46z+mR5PRgr4TLsLc=,tag:WLcrVZcq9A2dktXPuy822Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
