---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    volsync.io/backup: "true"
  name: redbot
spec:
  accessModes:
    - ReadWriteOnce
  dataSourceRef:
    kind: ReplicationDestination
    apiGroup: volsync.backube
    name: redbot-dst
  resources:
    requests:
      storage: 5Gi
  storageClassName: ceph-block
