---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  - ./element/ks.yaml
  - ./synapse-admin/ks.yaml
  - ./thelounge/ks.yaml
  - ./ghost/ks.yaml
  - ./redbot/ks.yaml
  - ./gotosocial/ks.yaml
