---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-discordsrv-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: minecraft-discordsrv-config
    template:
      data:
        config.yml: |
          BotToken: "{{ .BOT_TOKEN }}"
          Channels: {"global": "1538487608395698216"}
  data:
    - secretKey: BOT_TOKEN
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: /minecraft/discordsrv-bot-token
