---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otlp-ingest-tokens
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: otlp-ingest-tokens
  data:
  - secretKey: token
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /otel/ingest-token
