apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:U6kgAcDmHN3gQIn9gtfDiieCc+9CR1HKDwUCIin0edg=,iv:h0dK9PIuRE5C9PnTHGjtWr07nxEHLrR8Clo59+UmWJg=,tag:mPRh7quLePCKFhJaYZ/chQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjM3dMajdwaTZHR2ZCc0M2
            Zy96UGxrdUtEQWJqV2RhZkUwZU16WXQybnlrClBzWEsxMXpIVHBEU1VDN0xMV24z
            dXhqMnhmK1NDY1R2SkhBRzMrQXB6YWsKLS0tIHQ4dXZ3UGRkUTNKaDVYOVhmWk53
            UnY1NmRmT3FUNlpkSTlDMFpBdUtDSFEKfCEPXKzgsFBjW1iqe+VC28LhEiCcmpSG
            pg4brUL7hawRUrS89elK+vE7WYca3UiSyhyZjQpRC69ifoZ3aqKgQA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T12:36:18Z"
    mac: ENC[AES256_GCM,data:fel1cxVjQbtRIt5dMZsjWXW1ihMVqK/U7ogISfqYmtFUosGlFhnD2q7u4JhQeTinr+1B8n4D2uTdfMHyAUEdvn9wKRiJ+CpIITwOuGnpZ5XAgz/KMsl2uXINkpd6PR7N4NnQUaACLSezLP0SNBDk/6hBFwlgDFP94VHbSqqN1T0=,iv:Oup2BRGkhz7yITUpeB5umoiRJflnPSIE9ZIr6hxEFg8=,tag:t7L/cz+G5BuFWb8d6XtL2A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
