apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
stringData:
    token: ENC[AES256_GCM,data:wQB4vWTq9fascQU1Ef9AXh8ihyVGnf2ecl+4/5lZyhw=,iv:/VirZykDGpoKyto0GuASovROQMu9v8fYuS+oBtA4TlE=,tag:RC5bBaZZgO/InVuRe49ecA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLakJrRGJOM1plRXRHM0d4
            QUZuTzNtcDExbkhpMkNSWFFjWS8yR3A0U2hVCktXRFN5dU1LUTlPSitaK3lHYURP
            aGMrVDZLcCtjOHhva3VIL1lFTlBOb1UKLS0tIEFpUXI5MXg0RTZkN2RnV0hOSFJo
            Qm5mTWlDSU9ZR3Q5a0xCckhab0hmakUKm/t7h8JmxZJzKDhsdjh07F1ErzsZDWqM
            R2XlSfD5803lbRN0+f8DJQ1UyZuwCsj4eYwmhqNQYsTQtP/1BBtHiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T05:17:42Z"
    mac: ENC[AES256_GCM,data:qShYRBQwOvSyA3Ss/EfRVf2dWUjbEZMtdt00MjTTPbPBvwvAJAG6ZHCb2AO+kQOD7JErBAlrGM9tyZhdQdq2cYi6fjqQ7m+SPqZB5Ba9IvPxUh12F8CSvKuHvkB7nyiNooCJrjqwcpmyQdzY8FeDjRRgOILj7gYDoiEt3HsYg3c=,iv:JHbdigKNCRvMO+11KsoHrWA+j1FGslmqftiIPS2eRxA=,tag:nSqkTWPlj3bT4u3rUQNnfg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
