apiVersion: v1
kind: Secret
metadata:
    name: atuin-secret
stringData:
    ATUIN_DB_URI: ENC[AES256_GCM,data:pPVJ6pie6kp8vx/yxkfFSOaM2pnK+3HGOETOU3FenFTRh54Qlt1Lyot3/kYey99y3n7b6R8ZVD7iyjzMK8QIpI/k/dZbLr4JSgSQWlz1LPtWB6YTXos8mNzg4xtuCAcKuNUEB2nx2nlH2LDItGtiD+pJon4QQo3AMKTILwHNIxOl2zUfs8Xa2YSu8nQhqkPi+jIPCf0LeUNc4kay0eYYokVo+V91W9oLnUQYO9YXR253BlOnc7D0ZOf+GgZ3/x3AqPPqet5Iyak=,iv:GClOZEVZwBiOL5xBwSrYeKJtlzqSnkp6k3lBTZZkNG4=,tag:4xpQSQ4mgMGdfU4sQeVVgg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:ugMjvf8=,iv:dpbujd9tjzjZNLPmxIubn6obbu4i3JgQJwgrJ0OoD98=,tag:34VkzpMffsCKYw2DLPpwTw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:La7VTh5+XSwWa4Nx94Vc/a0+0YvLAdidpXa1W+W1BwutnCRTBQImyw==,iv:TI3YMjmN4JS5+a6Qz8rzJ0m2XuuzbX67orp3aP+FkRg=,tag:t9/DfAwPL09EuQSPTErrsg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:aZUUVQl3YrK9fVg16Q==,iv:DoTxCMQUGXmfFZOoq+VcfglgNcyvDv8Cn/Q0WCNObes=,tag:xHYhcQO+8moNFBQa+zzTmQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:s5VKZPjl5vnUwIdRme1H5xZnxcvh9aHnDq8W7EMS22ftHMm0Cik9dBU95N7ON28vxrBx0gw3lCBGqEGyc6czVtYeYeQ8LHOOiBdKtPnyciUMcb0tiOEiq5UcOULxo+ObBFl6Iygq7GBbK5NvQNhPmbwwRkzwNgAV5EvkarFAQ2k=,iv:gnwGBFxa3rXsJcQjED2fiJpQgImfP6/dbhNw4ZRexqE=,tag:7TBb+7RwMKIb7CqT9XReMQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:RxmsuTI8/VOxYT3bDCKuQD7tgPVgT7Jv2HHs4GotHS7ekZ6kF+R9LPczt+/whVxXSTVuYCuP4VcqoD0ov5+Ssdxf8BtEzeKWOzO44uNs1pdnIpvAvV88vVtR2/N/qIrgsqD1nONOHTUvblawkbP0bZTfN0eXMoPSh0DGWd6BFIY=,iv:gnzrkxgP8db9IVumBJwaJTYKusepqEzH0bF1fsRgnsM=,tag:hc4l75lvaoW22Nn99sYV2w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpKzFKTVptZnJDeTVrbHJV
            NDNrODdCZldMa0lYL3kvSTZrOEJqeTJBVVdJCkFEUW9oTEFkcUVhTjV2QjNGN3Qz
            ZHNXMEFBV1Nuam5KZStTa2NkQ05XOU0KLS0tIDFMc0wrVmt3cmdNbWZLa3Arcm9H
            TnhFeXpDc05OeEMzL0paZUN5NEpvd1UK4e4NrEIM8cAWSQVkyQkV/aILdEVwzOK0
            CR92l5mhPo/Z0Er00cQt1sjBonexk+qGSXwKdgQ4MFGs8xAd5Z+7Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-18T13:21:54Z"
    mac: ENC[AES256_GCM,data:nrLDPOhNwcbSFxefIezeKTk7uHzqwVMlWRDqte7w/EXv2oGHIHuyLqHfP72LHxQetMcx8NCVbvQ5Y72z+UtKsvgtbgjv990BqHjXvO5C5pLK0UaFayuhZ3m8XwWuWxIoLJROUQtn+IkNzGpZLJSZqD6B85+rTBtFCQvDbPadFP0=,iv:CzvlFlCpPh97g040tEC7B59xzdZpLKJABcQAQyqPFpU=,tag:4VZ8hC4owAifM93dkneaWw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
