apiVersion: v1
kind: Secret
metadata:
    name: atuin-secret
stringData:
    ATUIN_DB_URI: ENC[AES256_GCM,data:li7DDH/QZx3KZgGZmX5vMkMI/VNZMcOLKPtpakwTYq/x7bRKZTBGM+3UTCOUdQFn/PggZjDyBLWi1B3tdePiUlXA5NKAMiBzwi0Wmn5FVGjqhZk7PGkHzf61VvQ3qiBDjqj10ezqXxH2X/t2RzhTQk5uiS5OeoWF2E+A3NbBqfZYwKE508GIztWGWbNNWTOWYEqh12MBXQo7DD23h60oSJ/kCS5xX2iemxo/U4sJ2o7WIgHNDE72vpmd+zxBuk6Gub9RCvrIc7s=,iv:1vvwRW7+a8RT8wIwvzsmUzWhl2W2OFiPXOPNQEdTkws=,tag:t3uS/DPCops9ThrTfwBfIg==,type:str]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:dx9EaNQ=,iv:smtBgOBBMVeh5NkB5ecUeouq1o8yyWWrsuvRVw9Vc70=,tag:FWse6D1gz6anqbWG9KuaPw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:3+FdhauIl3e8SurXP3TPWWO71fm/qegbNLL25t5T85RZmfYcDBtUDA==,iv:iMfmtkM7YezAkTmQv5HSRxCwz37fRCo1g6QDz4Je0fc=,tag:U/ho46EtDCEEoZKU1fsmXg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:uZqeALIk1TJ25oHD6A==,iv:EiecErl62vDCFMxHkGSvXh0Yd1n198cdV32JA16kez8=,tag:WF1L9MmWZU7wSNPz7DdvFg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:6pNOlfWW72TRNG8hTTm4LJ/RwiljkeeFcJGjmkmkSIDayYFDXkcGXqW780UAqXxyFEHnrEPcXyrRpCV/tbHBxJzs/nXv7AqxpEHTIyt//udDgBdqFldkep4uN/DQr76/BJl+8hQrap6aeXAbakrSDyDFvvgmLi1SW067wv2feIE=,iv:r96S3BIwNg8L9S94SQU1iUJbMDIj1xYIeMjDyBer3Ls=,tag:AUnI0R+B6KqdVL0bkyU19Q==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:sieYHSS0g4E7RyowA6V9K11sBBJJtzDrsDlS4rL/Sd4QtveVtdVF+eQ2kLz60+PpiLQNqWMUP/cFJHuwQx+qnouCpo9ZINeDH97N2qDn7BSvHUNl/EoysnQH9J2ARUJJMrJnXCarU3LunQTVKEfaNtRhUGDqbgxuwXi4OqdWVUs=,iv:BuSzSvMwoCbOLE5cCX78LaC+rUyZqCxMosATSYFcrlA=,tag:xVgiNhugNFcdI3LYcDES8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwcXJBU082ajNkRmVoRXhj
            SENuVlNTcUlmKzJMaXRyTS9xSmE3T29QS21vCmo0OGFvUnlsQ0hQMWZTTDVqVEY2
            L2Q3Y08yL3RTVFBSN3QzdWNxWHZ2WHMKLS0tIGVQUTNPS05zR0VTNTVJSjZMbGtm
            U2VCVmZlR1hEQVlEUGdlQll4K05CcnMKRWKUUEPvKfKXTVJkobxFGfB9uv5ERkMn
            2Kgb3+W7EZnq/C/c7hhZJokclF8/5zlZvd04tzbQ/5q1qbXJMKfqGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T06:17:56Z"
    mac: ENC[AES256_GCM,data:zzo2IjSle2fjvfQsWE5wMKcrHfbBo4vpDT71CbKqwSX2Ip5zCt4JD2cVjrFy9iYldmsPxMYoqA9/0WqpVVIINJrltZ5F5VYlrjWZ7/xp9XZSAqis8JDNHLnklyvy3XupvPWxM+NoR/B++AhbosoIwOnoSMgN2AdYgIrPHW5oc68=,iv:INC1LRtO5NyHEBKgn6VrPHxmjiOTHvSnBLG3Rcl7YSU=,tag:nEg/PaEzsNyNXGnoqSqjbg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
