---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: infisical
  target:
    name: nextcloud-secret
  data:
  - secretKey: nextcloud-username
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /nextcloud/admin-username
  - secretKey: nextcloud-password
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /nextcloud/admin-password
  - secretKey: OIDC_CLIENT_ID
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /nextcloud/oauth2-client-id
  - secretKey: OIDC_CLIENT_SECRET
    remoteRef:
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      key: /nextcloud/oauth2-client-secret
