---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Darkflame72/home-ops.git"
      path: apps/volsync-system/volsync
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/home-operations/charts-mirror
      chart: volsync-perfectra1n
      targetRevision: 0.18.2
      helm:
        releaseName: volsync
        valueFiles:
          - $repo/apps/volsync-system/volsync/values.yaml
  destination:
    name: in-cluster
    namespace: volsync-system
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
