---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./grafana-dashboard-generate.yaml
  - ./istio-ambient-namespace-labels.yaml
  - ./istio-default-authz.yaml
  - ./volsync-generate.yaml
  - ./volsync-label-pvcs.yaml
  - ./disallow-latest-tag.yaml
  - ./disallow-privileged-containers.yaml
  - ./require-requests-limits.yaml
  - ./require-run-as-nonroot.yaml
