---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cnpg-scheduled-backup.yaml
  - ./grafana-dashboard-generate.yaml
  - ./volsync-generate.yaml
  - ./volsync-label-pvcs.yaml
