apiVersion: v1
kind: Secret
metadata:
    name: sliding-sync-secret
stringData:
    #ENC[AES256_GCM,data:4GRA2d84LA4oQThCCY0=,iv:FKV417fTlFKxMdc4JCBIKujKbe7a3Z0JylhrLyfk8oI=,tag:/yPBjPxQ6cWGhXHB+EDdRw==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:haZicfyDl55TngZB,iv:uoLBmV5reDaV2qqYpa31hJFgwnaOJrEtJUf45bumO3c=,tag:5wWbVLZ87REE3LxL80+7vg==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:2g19GzbXAI+FnUnXjAz/nIfs3bX+ZCtbcuNaUieJV5pzj2hr/W9ldA==,iv:rXUb1PneRaspROXB/oMimJsoTtmddMSf7q721OoOoV8=,tag:ldznPnxOcYP9Ny0CNryVGw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:SMvgWl7KAmSgmebb7ed8wYHJvPc=,iv:h2yyjzoTZOOmrq/fDTXyLd2Q/tIhau9hKExmSYpll14=,tag:4i+eSmJO253qpmsMmKRI/w==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:5Gu36LytUNmA/iTG7qqMC5Vu/5LBq3hGKFH3mx0+NoETk+AD8yH/oKiGdaH/QLJHrg2tDHN0xbdT9f49T7x89n6yUSch/Mf/aO+lWJ5bU429T4z/+hyn5TC00wPCCtrr/JAlUx8gB2L2GyNJslHSlppGjB+yMABYjyO+rp63I3s=,iv:/oGjKwhG4O7fHv3F3pwlV3H/IaSeM6kySpamYyr7kWU=,tag:3sNDSjsqj4QbFqEOiwTtdQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:+WVJ8vhLgO36q55PeOGNXtsltD1QKJvaueEJJQj6gRbHpnAWvA31vPTY5IbqEsZQ0QB90oqtYdDcF2skogLfKmHASGLwQBU1h6OmP4AU3k6+YAdgne9v65kh4WgBwFbLHZaaBm5iMD/2f0NDqOIFDtiFEBbUlt1M3r8wf690npg=,iv:87IJqXO2IjHAFbQypHyuEh8f38aXohS4X/WhhYsaWHQ=,tag:9PqdaNICq+Imr0ss7FBwmA==,type:str]
    SIGNING_KEY: ENC[AES256_GCM,data:wDkRjxRBMdpywHUANeRkOoTxTeiJ8VtRpj+tWGDO4x2SuU1gQdbgdBLvAuSRyc0FypSTrmE0S3sHkg==,iv:6mS1NRaeoWLYgKym37xMzi4nmodQCBhm/99QK99iU+0=,tag:4VRxVwlEpKA0pKDLqKL5aQ==,type:str]
    SYNCV3_SECRET: ENC[AES256_GCM,data:Wvayk1qw9tjBuU6qxOcntUT/YxsOUq7hoC58k9WDkGOB9EWCWxFbPHNOzHXjsON7SujdYXBjLsQUWdSH4fgkTP2SocAqiWQaJKQjsZntSmYk6BGtYsYBwYpPkUNGqkX3Hy0BN872q36Wmmaii6f2X0rEjVrgnvlt/ixJPHaW12E=,iv:QgYjUyljjNKauAcvzW4gzIwopitdYw63CzfQapUv7wE=,tag:amc3PddDsWnbxeVfFb+8Tg==,type:str]
    SYNCV3_DB: ENC[AES256_GCM,data:Befths+6OOYPXbRiXUqxksVagNf2GLvLwzsLKCgzYmuQCQMIA34/9UcID0rWo5Ub+rNYwb+oR+kjDmR/JbdkUUmpb+hAN68UI9EouEbF0DJBET8LzGpj6msASx4iED+80wh7TaFI/H1nGgxsgpNJOikW9aERn82gXC7dGMxOCYg0D0W6LbB8HdshFv9Ox2Q6S7DevvCgqPh/6W8613/y7vbt0p2JRO5uXNFhDoq+HtMPtsEzmBezunJGioLJXF9GQyC2fFCVHzbl1ilOInDjZqAWRgfheo4fzqrtiQ0X,iv:o25Ts0uz/XXh7BMs0p+qARHEELaHq/1puYo+tXETxJI=,tag:Pe0MSOoOfPXJgW00blLRsQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhRVJxamtXZzlnOXFRNTJC
            UEhuZ1FBZllvUFVoTFBnVUpqeTNRTURXaVhZCmxLZjMvdW8zMGRpbzJjZlduSXlP
            RE5FQTd1elF4NXhRUHFCVldLVlRYeHMKLS0tIEpjb0EwT1BGM2hSdTlxMERURzN3
            Y0Z3OFk1NjF3L2x3UW5qVGgvdnVPUXcKr2SmF5Ut9RaPVOFGDzs+4axpMANZmu7y
            uFD0OLn+ckYRL9CL8nyHaAAbqvaIPHL6t7QwMNsy8NpzQCAuzi2wAg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T01:23:54Z"
    mac: ENC[AES256_GCM,data:af9/6Nfq0dKEpAdaIU+V8w4X2fn7eCz4ewI2ZUwotOQIy8j3zDhvJXJWlwmdcjdxSCQ4x53r26cXLbBvx9EaCdurjklLNuZRlOwK9mR7AUe0EYBOEQJbORZykSW5goGjsdoeL0aeUFnQ+U84GB7GvVm45QOcCn6ZPULADGwxuUE=,iv:2el1MjBd7T1CjAOeOQKv7e13Szawlah0RzowoKem6uI=,tag:K1VBT/pJEKwdcuTiFvnAZQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
