apiVersion: v1
kind: Secret
metadata:
    name: sliding-sync-secret
stringData:
    #ENC[AES256_GCM,data:6wN8i2UICsckGPUYgcY=,iv:EwOA4oSOvsKqr1+91xDPeWY3vW0LfkpC405pRFCIiZE=,tag:Tz6LzfOPtElsp74TsmDPtg==,type:comment]
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:78GjWKvlNaJiL4zd,iv:IGbyob7Kehvmr3lzNXS1JEzdpYV8H6zBlS36In4DgOs=,tag:HYSm2jrXmqqADYuhJhlnbA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:Il5NTLtW88WSnpO/qhhK40Ode5VNZKdWAU/6aU++aRdr1vlz1xk7nQ==,iv:zX2/mVE1cIZBRC5ylLHog69jmFMIecyOTTS2bp08I2g=,tag:dtzC+eHqGkY/DmjFJj29Yw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:o0gYn4pf535yMYPW2PU6CrNqBN4=,iv:SK8KnLiQna5NdQIn9kE0gC4l5HRMVrStFEOn8rXzlLI=,tag:jedYKw20QPTGTsuPdhJwyg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:Th1dTv/w+H/iQi1ujGXL10DRO+vUYc1fAQJEaulz8NAlKDOVTzyckVtFUEhU653tdGHpR5NaEy18IQJx50OnJrm96MnxaCaGcD5HmdciIWdCiDtXbysK6SAi0E/TsyKgA3iDVcpDTuO/y083PhHDtHSulV7ZhNFaAyrMbz1TMqY=,iv:ShizElT8HGqPiPNVLJj7gtvJGBPiPXM4BbIeOv1oOYo=,tag:S0gHQAy4SloYwMmZuZ1EjQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:NRq36CSVx9n7vPVRm720SNX2RnUnw303o12N6IvwsnAt7KeZtRZRh3mQcPGdnMQbit/u5k+Op5VbcPhnS/nEmCyV7DSZniG+Kb5HX04PbV2oFPXBI+W3fbEdyos7gMGMMI+yVo+nW+Pz2NChzmx72iTQoF145LNg3IwPkWTWGwA=,iv:a87aawD/VzKMLRUIa1bIjEY/72wKrdi6ntlsMTOmbkI=,tag:jiCdZ/P+f1vVcRJhDEYuCw==,type:str]
    SIGNING_KEY: ENC[AES256_GCM,data:PQJE4FMXXZYB1OUR13OrjEzT/u1smZu41aBA9ArOca4bLxGy7i2rUcgsrP3u/02RIbZ2Zc6bivDJJw==,iv:mHYSC1gpe6gejU1J5p/Yj64sbiv9xoZe1qO+1ak7tjM=,tag:u3U4PHKkYFi8XI/exk6XZw==,type:str]
    SYNCV3_SECRET: ENC[AES256_GCM,data:VVWUEKC0clmCxhUeQwEERt9LQlX0SQ/xvuBNbQoAOJqjZo4OtDl1iip4+H/uehBzOO9IgWLJg2DRWo5W1S/1o2FPOlOpszzYIQLWrJoGcRX0A0JLmot6ytWxmgMCDE2ALt1yBZ3bTPWSzVL8bO5RNNqQ1vAnnogU/++PhkbprQc=,iv:tao6G86J0Fl2z8CVh9YIEVRf+aY+qx1xDD1cPbcdvuE=,tag:14XGhFxMUoz9hVmQOmdwxw==,type:str]
    DATABASE_URL: ENC[AES256_GCM,data:r29bwLyF31W15Z1Jqy60JFtnXttKoLdk9bh/NXjxk3xotF6jwBFHGoKUpC7plnIe6dh0VElKp1pKHN+P7+oVa74ct4yfw3lHqLAi4fPZyuk4NS+Qvg3nljWQRTZKXdUynBQKilytyYTepvuU6WcdHf4ncddkhYlh+2Zrr9OBMD04s86/vt2e5O+RB0aFJWKFKKgdCaiK+hiwaq2yewF3NBYgdP+15IbuqGGfOjxTNOaLjnYHe1wWdyW2Y3Xmpi/XPiOIQknNPZmSHPhIIbMmCXQ+CfVs1wzV3inT5yvb,iv:TAZ7+tWXetD3FW0SxklqEerj/0sQlS0vAp7vRKV+oko=,tag:pVEYMu7MxYaquorut17NkA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCSTQxSXJGRG8xSXNCNDlU
            bzJTZUhZbDRDR1llOVM1ZFA1NllkN0RkbVZNCmZ5RWlRMERhZjNRRDFpZGVjdUVE
            eXEvbTdGVkQxNXpqUjBNek5NaGw0UVEKLS0tIHVIU2dKcWtHdFIyTVhlM1AyZjhM
            dWJRN0VLdFRzN2JmS3JlTEQwdEdMNFkKfmMZ1lwdQoexpYeNM7G2DeR+pVzLiAMz
            I6bR2p63cfF2bqunz3aTlN4ekP8JlZ5u0ZVQc/IfrWAcT/C0nied6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-22T01:14:42Z"
    mac: ENC[AES256_GCM,data:kSufNMg6kQJ8v8jBFmR3eND9AmVMPbfHU0vbTEcr0GFsLhMwImqeTm+Iikrp6P53Pfv1Xo1vmqTxrPS8RWEiPIwkNlz46mPbQfRwgOuHQB694qILCns0g4vZW7DwLbpgQuNJPBDqBBdJkMz0+Wth1EaMrRVEfDSSLjntDYSKwR4=,iv:HyAf0oKpQ8o1g7wmQXiviZh3E8+nmM1+0yz+RwqQDJE=,tag:Qf9JM9ku85RYuhXia1hvbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
