---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich
  namespace: media
spec:
  instances: 3
  primaryUpdateStrategy: unsupervised

  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:16-0.3.0

  storage:
    size: 25Gi
    storageClass: openebs-hostpath

  managed:
    roles:
    - name: immich
      superuser: true
      login: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-db-url
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS cube CASCADE;
        - CREATE EXTENSION IF NOT EXISTS earthdistance CASCADE;

  postgresql:
    shared_preload_libraries:
    - vchord.so
