---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./pvc.yaml
  - ./cluster-v2.yaml
  - ./scheduled-backup.yaml
  - ./scaledobject.yaml
  - ./podmonitor.yaml
  - ./kopiur.yaml
