---
# yaml-language-server: $schema=https://schemas.zinn.ca/v1/persistentvolume.json
apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-nfs
spec:
  storageClassName: immich-nfs
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.0.60.15
    path: /mnt/Main/Immich
  # Note: The first two options are strictly for NFSv4.2
  mountOptions:
    - nfsvers=4.2
    - nconnect=8
    - hard
    - noatime
    - nodiratime
    - nolock
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-nfs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: immich-nfs
  resources:
    requests:
      storage: 1Mi
