# No yaml-language-server schema available: immich-app/immich-charts (no values.schema.json)
immich:
  metrics:
    enabled: true
  persistence:
    library:
      existingClaim: immich
  configuration:
    backup:
      database:
        enabled: false
controllers:
  main:
    containers:
      main:
        image:
          # renovate: datasource=github-releases depName=immich-app/immich
          tag: v3.0.3
        env:
          REDIS_HOSTNAME: immich-redis.media.svc.cluster.local
          REDIS_PORT: "6379"
          TZ: "Pacific/Auckland"
          DB_URL:
            valueFrom:
              secretKeyRef:
                name: immich-v2-app
                key: uri
machine-learning:
  controllers:
    main:
      strategy: Recreate
      containers:
        main:
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              memory: 4Gi
  persistence:
    cache:
      type: persistentVolumeClaim
      accessMode: ReadWriteOnce
      storageClass: "ceph-block"
      size: 10Gi
    data:
      enabled: true
      existingClaim: immich-nfs
      globalMounts:
        - readOnly: true
server:
  controllers:
    main:
      strategy: Recreate
      containers:
        main:
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              memory: 4Gi
  probes:
    liveness:
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /ping
          port: http
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3
    readiness:
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /ping
          port: http
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 3000
    startup:
      enabled: true
      custom: true
      spec:
        httpGet:
          path: /ping
          port: http
        initialDelaySeconds: 0
        periodSeconds: 10
        timeoutSeconds: 1
        failureThreshold: 60
  persistence:
    data:
      enabled: true
      existingClaim: immich-nfs
  route:
    main:
      enabled: true
      hostnames: ["photos.darkflame.dev"]
      rules:
        - matches:
            - path:
                type: PathPrefix
                value: /
          backendRefs:
            - name: immich-server
              port: 2283
      parentRefs:
        - name: envoy-external
          namespace: network
          sectionName: https
valkey:
  enabled: false
