---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app asciinema
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    controllers:
      asciinema:
        annotations:
          reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 16
            envFrom:
              - secretRef:
                  name: asciinema-init-secret
        containers:
          app:
            image:
              repository: ghcr.io/asciinema/asciinema-server
              tag: 20250509@sha256:97c14960ce380b99bb8c1ae8861f53a81866cbea40517fde8c46a1fea721aacd
            env:
              HOME: /data/config
              SIGN_UP_DISABLED: true
              URL_HOST: asciinema.${SECRET_DOMAIN}
              URL_SCHEME: https
              SMTP_HOST: smtp-relay.default.svc.cluster.local
              MAIL_FROM_ADDRESS: ${NOREPLY_EMAIL}
              SMTP_PORT: 25
            envFrom:
              - secretRef:
                  name: asciinema-secret
    service:
      app:
        controller: asciinema
        ports:
          http:
            port: 4000
    ingress:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        className: external
        hosts:
          - host: asciinema.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      config:
        existingClaim: *app
        globalMounts:
          - path: /var/opt/asciinema
