apiVersion: v1
kind: Secret
metadata:
    name: asciinema-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:OcabWU4s0arKIfU06LH4r3aY5G8+2/16OqproWZAnnl9e4fGHnxJiG72fl/WE5X4vbH5pOxOytZgOR6d9V9/5iIidhu/HKzxzfHHa+pXP5JhYRO9rcX5Lk5fEQ3lLAyywsUrDLwGBnmyagRTeY1a7cyBC2FzKoHf8GLRKLqi1u0sPkCRVB8NSlSVe+sbqmxNOZ4CKDvindeOMiPZkNv9vchbOGgRtKX0xLnJNdUTBnHG+4jo4u8pJkeji4vpT5z3mAkEovHvm33y5cizcRyWkpGYKTNF,iv:/jTQml7hI7O4vOragrSBEW1BWeMPloaRXkp8GZa+zQk=,tag:DmJRElOYRnMpha+TPtnOMQ==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:IG0+OnAXFq6eBwQeXjfkOchft0dD02CnlvCOnzlYqPdE2BLh0uDW5j7E/o7DHsGOhU6zixnYLf+Hu+LJhbA65w==,iv:d7CEqQTmaRxyzumcmnazYrZ9JnpmLaSodu2PjDFxug0=,tag:K5i/+s9C5CEJnUXEGe7C1w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS1VHNit3dWUvWms4UEZv
            MFFQd2RDOTVmYzZPNmtkRFdSSU5DYmQzeldVCnV2T2o0ZjF1d0FpZDE1U1VMbEhX
            a2xTa0ordUcxcVY1NGJwRjh1QXhBTXMKLS0tIDFFbjh3NlVIRy9Hb0tQL2NqbHdy
            VjZXdU10dW95b3FKNUR4OUhLM0JoY1UKjkpiqwawAhdMa85kWCRfjr8cTtWwOQ7i
            cFG3hTNS1GZj3Ycsaa0+DZTtqCSScrmS920xnXp/llcEu/SVIrhDKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T02:56:37Z"
    mac: ENC[AES256_GCM,data:UioVBeTPXLFZXt1lhRCjJy3cMz2tBLJPVx2/0DPyLNlXukv2IyZb6IdBauvOfhhDf3tL0WL/cYrLRGiQcnoq5L8dsVRdBep8/lbRVzMfJtgFmCvdmiBz/gbgvdTe1C6hJSRLYiMxVksS6Ngm+ijlGkI/Ui7dWGTKsbpU3N6wfNs=,iv:CEFWMp5vQRrhMn8XCZAw9Mh0rcKdFS+fufMwhNSj+Gc=,tag:vhR7IeIpseukZiIqsbrwAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: asciinema-init-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:vBvkcoKHfWPF,iv:Y7hrqAjlFLNImJQQwYXvRzJFFAC+SpZvFe9/qnfFjE8=,tag:TkZQSgeOS5GmPuD7aITQ6w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:L3mwNKT1SoEXO/I3ZgWNao0wbsGVDhv61ceDE0auqNHUFnmTEbu1Dg==,iv:DGmTBR42ohLWnYJIacLylHtga7swcP0G28ZiiKYrnCc=,tag:bXviWhAd0099oLGtqc/LZA==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:jIc3IMiHqsQ6cK288ELFzUI=,iv:eKusYON325yWtts6T7keNz5fZiwd+qkSwsQ5lSCqYcI=,tag:vdG/jwcdvS4C4EfO7fwVtg==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:ljIp2tOYtVLZRdcShIoYiY2klZM6BueoZm6rExYw0Jptq0AD4MSuO94Jj8brdeSDwyhoceXCrWO0nzsCQF204Ni8kSsWCYpmCHZgY+IVN3eh9OovMqStQRJZt5pWv/bM/BU8bRZU9G2wl//cDPxM6lJG6Cr8biiRhG4I/2847SU=,iv:pbmyCaofRPW7qbsWikDhMZiIEQMY/2KQLtvIOZXjUQ4=,tag:6ZXEojB/ArcTq6LBokJlDA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:9I60VXtzOmLKJtsxHInoo0PRjtsGqQEMxPCS7DIWHDa1rEIP9YCERWqhYwF4ciQSv1AZmOW5A73TwmXvKLv2aLHPEXTRkARd39YM4XXTTGPdLZeY74byWjuos8UkEPAVICzpjMfdigWOXaHyCB7UpiYfA6vfjPEPBiDq1XG7bPA=,iv:vJMNMl2ks1OkjgpFJE8pIQh8UCjO8mYw865G2Jq4adk=,tag:zwpy2dajW8sQss5oEsdEqQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzS1VHNit3dWUvWms4UEZv
            MFFQd2RDOTVmYzZPNmtkRFdSSU5DYmQzeldVCnV2T2o0ZjF1d0FpZDE1U1VMbEhX
            a2xTa0ordUcxcVY1NGJwRjh1QXhBTXMKLS0tIDFFbjh3NlVIRy9Hb0tQL2NqbHdy
            VjZXdU10dW95b3FKNUR4OUhLM0JoY1UKjkpiqwawAhdMa85kWCRfjr8cTtWwOQ7i
            cFG3hTNS1GZj3Ycsaa0+DZTtqCSScrmS920xnXp/llcEu/SVIrhDKw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T02:56:37Z"
    mac: ENC[AES256_GCM,data:UioVBeTPXLFZXt1lhRCjJy3cMz2tBLJPVx2/0DPyLNlXukv2IyZb6IdBauvOfhhDf3tL0WL/cYrLRGiQcnoq5L8dsVRdBep8/lbRVzMfJtgFmCvdmiBz/gbgvdTe1C6hJSRLYiMxVksS6Ngm+ijlGkI/Ui7dWGTKsbpU3N6wfNs=,iv:CEFWMp5vQRrhMn8XCZAw9Mh0rcKdFS+fufMwhNSj+Gc=,tag:vhR7IeIpseukZiIqsbrwAw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
