apiVersion: v1
kind: Secret
metadata:
    name: asciinema-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:SB0YWlMYckqnR11BYNrupjhm2u6ru936qfFkjmyYRe/cKe5cDnSXh/gHQ0FfGMejJxB0DCqr18QSrJ5V9YRm9ePiMZRQwnn4ekLMQVcmI5wkAeOsGlVrPS5qNdOFhwBTt8nyMqD4Ehnx50KM3WMAdDAsOr/m06+RhyXKRh/eZIpjxGZuyHho4NcOZajb5EI+ECfnB+YIEY3PqKTAKcl+ULJzwpJgxU/kriCDQUIZhdSZ8ejkfeI2a8pF0dUW42G9zF180mRQFRhu2taiK6VXvzbBREqB,iv:Am7IhED4c4X/zmQByHxANmG8ZAk7k7qjlPXS2aHRYc0=,tag:HHFMLqPMsHevzb6jIDmPwA==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:R0tGWoVU3s4k9dbTJAv029h6BbOBNonadwt+hIshnznPXJuWvw1I9lXg1w+EGldtgK/pvc54eNMBzUrho0cpLw==,iv:CE31/vYIfMgU+wUd9vJueJbqzKWZGkC5HagmIfn83f8=,tag:9Z6dgGSfRH8qecSRpZoS6g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQmZGSEF6amhwSnAwNzEy
            b0E1NHFETE1ybGJtLzBYcHhJeExlUVFYYlgwCmR3YW5wUk5tekY0dnlidFBXMkdU
            UDl3dENBdFBWb004RlA5WERPdkQrcVEKLS0tIE1WNFduT3FQaFljZDNOVXJoUDFO
            aFFLNHV0KzU4UnAzRFUyMmdSZmFVYjQKDiuZqulvmTg0bRHlakXxgdUjA0yOQT9V
            gj9gmVzThgrXbNbhGcUKPr7ZDpL+Nbit6npOmfRbSuzKlhNKU7NvdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:03:49Z"
    mac: ENC[AES256_GCM,data:YCrD0U3lpmK2wK3eUqiEJLQAUPW5iWnWvBjW65+ojKirFEr5gQcn7B0Bu4kGsFFi2Jo7KBRJWirB8K2Pw2OcJE/jUjeXHjfpNubtqQ/LcKnkn0jkYxJt1I4NwrTMATD+u+6NfMD2qGQZ3vJbKUQmMC8vKw833nqCx9/qtn4IIlI=,iv:JpfxnifCHmkAHzHIYwhCVjXaXNodygeCk98f7BdyPFA=,tag:EVfJmwoE2PQdAXjBcdk5rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: asciinema-init-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:3gTsk7tWQdzv,iv:daa7wdAvqdVuY+mdQAqBGMP8xH94w18A50N30qlmdQ0=,tag:JQeSO8ZE/5Q2riVC1aTvhQ==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:a+Y6RKm543MwLIIU+WOu8BnGAnLROqp8M6Lg2oLN8HQn7nmsyz8PZg==,iv:BCOYvgb2Yp9oTjZf3+oTFEPJkUBeg4KwWQZ4W/YSqoo=,tag:8l7M3wpj2f1YyDes3ldE2w==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:cp6X9lIYZXc09dUkpUtrLmI=,iv:NpPtWjseHoWP+MGdyzRBF5HUMUx9Atb2Pe64Yq0Yg7o=,tag:zn70W8ouiXaq0AXqLaRyrw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:OXd2hBSsxoJTv4AKY78ApO2V9isw0Z+YoX2DBG7Aem/30XRQ+Cogytnaz91HppaD8p6TQRH9sm37e+cn50fY/L709giF7owH2w4wQBZX2nKExchJBwQ70NlePrUvbruz1K9X9w/FGWxIqUR7wsqnA0uLUnvIOIG3Aeoy7CI42zc=,iv:qvkRuQZBAo3hXJpFsTeMbnkWIwSbYofOYpMR1wzus/8=,tag:3/cvqyesLoB2qVcoWd66bQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:hAcH7miKd3bi+2S/kRB5RPH7uKMRkuPRwt5cht1qvZURXfsbGUQdEfGYNbUijQAnOT5gLDIlXzcWEb1wKdf1TWV0oJ7dLSMK2T4EytDsVqXsF+8oL7X/hiYNw/pMQIyD2BdvgI5VYAyGmUDMnhfjkunCsSyPBGzWyGA+vP6DvzE=,iv:3fhmxq1XwRD5vkJQzQpfJV0ICGYZ44pnFvOBcZF6l4Y=,tag:3CymFIJE1oAkMILKojQGAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQmZGSEF6amhwSnAwNzEy
            b0E1NHFETE1ybGJtLzBYcHhJeExlUVFYYlgwCmR3YW5wUk5tekY0dnlidFBXMkdU
            UDl3dENBdFBWb004RlA5WERPdkQrcVEKLS0tIE1WNFduT3FQaFljZDNOVXJoUDFO
            aFFLNHV0KzU4UnAzRFUyMmdSZmFVYjQKDiuZqulvmTg0bRHlakXxgdUjA0yOQT9V
            gj9gmVzThgrXbNbhGcUKPr7ZDpL+Nbit6npOmfRbSuzKlhNKU7NvdQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:03:49Z"
    mac: ENC[AES256_GCM,data:YCrD0U3lpmK2wK3eUqiEJLQAUPW5iWnWvBjW65+ojKirFEr5gQcn7B0Bu4kGsFFi2Jo7KBRJWirB8K2Pw2OcJE/jUjeXHjfpNubtqQ/LcKnkn0jkYxJt1I4NwrTMATD+u+6NfMD2qGQZ3vJbKUQmMC8vKw833nqCx9/qtn4IIlI=,iv:JpfxnifCHmkAHzHIYwhCVjXaXNodygeCk98f7BdyPFA=,tag:EVfJmwoE2PQdAXjBcdk5rw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
