apiVersion: v1
kind: Secret
metadata:
    name: asciinema-secret
stringData:
    admin-user: ENC[AES256_GCM,data:MMQducA=,iv:I7Dqr6JdkYKWzyVomS6P9yBGjPD4I0zQlfwz5HZo8Ig=,tag:OAvrqJdVsUQ2flWE8U1gQQ==,type:str]
    admin-password: ENC[AES256_GCM,data:qavW3b6pgIvNhVgj1XQ=,iv:CWnA7kga2shzqITJYH7OuhXU68/8H9kZJB83jkZBiQk=,tag:DlMqlQXofMaWvgKzEm7sRw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeE1EY1NHQmM4Z0I2NEVa
            MWh0bmtwblVjTEMySVZWTlpXZFZzQURMWW1BClBaMUgrVkZ1aHBFY2p4T3QrOW5W
            d09qbVVMY21JQXh6NXphdXpUT0xLZ1EKLS0tIGR5NU1LdW10REZmaktIcndUWVFp
            RGQyellOdlZmNWNHYjhIdzFqMURscDAKHzqX5xpwtd6GuAOdKQSa/S/MLrFtLMOj
            mNoSMk1SzAqav01I9NA8EURL8uaq5SzBPt64JrYRRt9p1yMQ7qEHHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T02:07:23Z"
    mac: ENC[AES256_GCM,data:Gpcu2/JzooJynULVk8zNOVJkdlqw6wfZZ0YDPMxFW3KRK+UZ60kEElU0m6KbJePliYvUCr+3+9KzrTpuNfu0Nnmsck/ky3aLlX8oAaimwozEP29G6ddmaGaFcwROJcupaSH5xJWokH/D21gGzNjvHrTGS+cLvL6FubTgQgiBR8w=,iv:+mmVoaitP7jconwTOqvZZ2Qh15ZOS/jPg1BAaMOsA0Q=,tag:dx64p3IPVtZFtS+8JtysSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: grafana-authentik-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:XtO84KIwEi0pvX32cnkRrGsyATRURATZMQb0mKVHC44DHv3mzYvqGK8/OKSAT0uv0kiXYxitSxFOUS3hiSXPzucJU4hTAli46tjzjG/a/MkU8A3zY/dYFqB48uo2N2o1UNh35Yy5StoC8w/YCDDXc6UX53+15FJ9LtKnEWZ9eNB3ej5CdgNM57wpbwq+wOBy27dW+4VVlzuaVTUWkcLwJfza4Yr7ckTKBY+q+dZM3qcyI1Dpvmo4MV7Qtfrith2MLFYyDGULYrcfgud35iI0hBAJbZ+/,iv:B3vwaYxqhIB4Ib3Z+rI/UeVKxOpe9rxbuzAFocOBHfg=,tag:ufuIqDSkhrr8XTp/o11D6g==,type:str]
    SECRET_KEY_BASE: ENC[AES256_GCM,data:EdRT/ING3Ed5m+n386jQftftnQogVwxjcK3r0Q88yFHkTkZ16aU66XfGZLvdGHW8FEufUbRy6nUe57H2TA1PPw==,iv:++YqUA2eRxb3ZbwBgnfWIFjey78ezLo9981kB+Pl+FY=,tag:Oi1z9FaAIMn8ucq/D0XIaA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeE1EY1NHQmM4Z0I2NEVa
            MWh0bmtwblVjTEMySVZWTlpXZFZzQURMWW1BClBaMUgrVkZ1aHBFY2p4T3QrOW5W
            d09qbVVMY21JQXh6NXphdXpUT0xLZ1EKLS0tIGR5NU1LdW10REZmaktIcndUWVFp
            RGQyellOdlZmNWNHYjhIdzFqMURscDAKHzqX5xpwtd6GuAOdKQSa/S/MLrFtLMOj
            mNoSMk1SzAqav01I9NA8EURL8uaq5SzBPt64JrYRRt9p1yMQ7qEHHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T02:07:23Z"
    mac: ENC[AES256_GCM,data:Gpcu2/JzooJynULVk8zNOVJkdlqw6wfZZ0YDPMxFW3KRK+UZ60kEElU0m6KbJePliYvUCr+3+9KzrTpuNfu0Nnmsck/ky3aLlX8oAaimwozEP29G6ddmaGaFcwROJcupaSH5xJWokH/D21gGzNjvHrTGS+cLvL6FubTgQgiBR8w=,iv:+mmVoaitP7jconwTOqvZZ2Qh15ZOS/jPg1BAaMOsA0Q=,tag:dx64p3IPVtZFtS+8JtysSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: asciinema-init
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:tOOItf5zj43T,iv:hW0F8+zJymTK6BnOqPCSYNQHsB2Et0mmR/Axjjjs6J4=,tag:NpU0V+60Qc3FE3Tx9bh64w==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:S2oAEuI5HUiGfrtg3DSsfhJG3a0Qp05y/YmRmX3b8bDsrrsqb63dIg==,iv:Xoh1xbC4wMmipcLlyjg+zzx/B2uxIBEbJF6ea/UYHTg=,tag:iPYJEbNyfYLKTW11DV0cfw==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:QNaX3yOSh9lSy5nSz6x1lbo=,iv:IiSNy0+4F4LmCr8Y+J5blmXpgLSX6aeiIiLI5hC6dRI=,tag:53Lg8v9Bg7rOClXRbG9NiA==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:oNZ7xXcnlxzZh7rdFhwE/yG6SNkUTNzUqB9ljHzKebuhyIfRhOZTCkobJ7ZfbVGyS2UHXfODcq0RjpmRPM7qZjuUZxXr2Fhpwur4C4JiQXVNk57R9gxIt875m1spu0AntuaCsTs13jLnUrcIEKd6ChxLq2fvHT1uX8FLnZrWwHI=,iv:Ka4DkdZpIQ3FB2OBowomF+Yzb3Yfq2UuH5xJbBydExQ=,tag:EnWS3elwoNndfTsrklEuqA==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:D7oX1d6t2Sq4ItBUJMuERwlqRCbvqRb8xxHzommJiqQ5r+SSDfPGnmp5X4JEAByCvXMyBkTsQPEXoSVQ+ncUTvXSJaGThoj8Wgyq6T7OVDib9GDcYZdb0WzzGVv302GQz77eA673ahK4hSqDk8Mr1NGZoe1s3uJfhgxhaCA1Hns=,iv:odqo1E+mDB2bYDSpLggs5PKPb83D93+Yn8r9igAJNzc=,tag:U6mEXKgF3LjypjK8bhjsFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWeE1EY1NHQmM4Z0I2NEVa
            MWh0bmtwblVjTEMySVZWTlpXZFZzQURMWW1BClBaMUgrVkZ1aHBFY2p4T3QrOW5W
            d09qbVVMY21JQXh6NXphdXpUT0xLZ1EKLS0tIGR5NU1LdW10REZmaktIcndUWVFp
            RGQyellOdlZmNWNHYjhIdzFqMURscDAKHzqX5xpwtd6GuAOdKQSa/S/MLrFtLMOj
            mNoSMk1SzAqav01I9NA8EURL8uaq5SzBPt64JrYRRt9p1yMQ7qEHHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-14T02:07:23Z"
    mac: ENC[AES256_GCM,data:Gpcu2/JzooJynULVk8zNOVJkdlqw6wfZZ0YDPMxFW3KRK+UZ60kEElU0m6KbJePliYvUCr+3+9KzrTpuNfu0Nnmsck/ky3aLlX8oAaimwozEP29G6ddmaGaFcwROJcupaSH5xJWokH/D21gGzNjvHrTGS+cLvL6FubTgQgiBR8w=,iv:+mmVoaitP7jconwTOqvZZ2Qh15ZOS/jPg1BAaMOsA0Q=,tag:dx64p3IPVtZFtS+8JtysSA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
