apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-password
stringData:
    password: ENC[AES256_GCM,data:/fGBTHjz1DLSp4JDZhIqMBlu6TQnxvIwHGQ7/bWUOAg=,iv:vBuQ48KfZ+pHNpmhj6nMrytL8mBLiFM7QYeqnn/+iSg=,tag:n1R9ODZNUsD7r/yvAegrWw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaLzdIY0VFUHVIdTZObUpp
            akJZaGRBQy9GWitqU2ozeFNDRDUyVFVUK25RCjd4L0JKZ093V2RkTnpwUytLT0d1
            SVhQNkVhMkZmUU4yTm8rLzRhOTRpY0kKLS0tIEdXdVJ4Ynh4UVZrQzJvRXhiVXd0
            L1dqR0htYnVFZ0JNQXpKZTJ4UmUrb00K7065mC04syn9VRQ6c1Kve/7SBTkW36MS
            FQXkHEAr8KzVY4Mbm1vM442kGhIREiZ05GUZOh2pyJG7yaQQTtUWWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-08T13:47:54Z"
    mac: ENC[AES256_GCM,data:+tRQ2EWS4DVo+OCnOck6oOyklkJeWE3MaO9XxzTi0XP8GiBvG09kNNNfypDPWOiIp/jaGxoqT49u4RWtRyiRk65nA0k2GjvZkgkBlvvDRx+G0C5P28P2NBSr4I8K//jR26wPnOnYq/0rBDbasnRkAaiaUGq1RnLOR/X8PdKlats=,iv:IIWKeL/DummyiwlZ4l5lRXNRPZmjQBmnW+zakWytIJI=,tag:TheHD+1HUWkBnuECRnx2sQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
