apiVersion: v1
kind: Secret
metadata:
    name: rook-ceph-dashboard-password
stringData:
    password: ENC[AES256_GCM,data:EtiA57+hTxrehAr2OvN9Wc+dB6wSrCu6o7kHvMoX2iU=,iv:R5vDdEwA0Lm3kTZcgx35qrSdZ7YPqxHY1hphXwgX6Ys=,tag:sr6AbjcOBOqVwKflfoKVEQ==,type:str]
sops:
    age:
        - recipient: age1pk4hw4gdplvq3tz6ma96hx3ja4w303ld5n5x82yqzyhj4g45qadqq9nf4n
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcjVMS0dqTjA0bDMvVFlr
            TW1xeW96Q1ptY3J0UmhzeDI3cnZ0WmIvYkJRCmJ2dXArZzM0NXlGTHRPZzYyNGo3
            VDVEVDRURm44V0p4YmRnekZzUUxtMjQKLS0tIFJPUDFZVDloazVrL2ZyUkdmVVk2
            eW12dmpIN3hMSkcwNWEvRVFtUCtVZEkKrfAZ3OSyvgOPZzt/1iP9IkavnW2OnkqL
            pXwGUsJT+nI629Cqk1KD2G3BfmfCqtVeNCrbhmfstn5zc5Pk7jegww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-27T12:53:42Z"
    mac: ENC[AES256_GCM,data:qn+N1ykWVlOav/RhPhSu8o3yBVsHv4IYuL1rlX8FrMXE5KAt5u1BIfsD+0fEL+5UniU8VeIWFPme13Aj/gV3O7aevljhFCOluZzpsrQus57966v+e3VJDi/eePRg7HrIdyjlz7dskIau9fpOH35/+t/gHjdUYLFmL8gG9R6qdJI=,iv:jGjLFzCvbfwMVhKJEWJ1tN7iQMGVWdSRi/8S9rvQn6g=,tag:hrdGr9RZvEkT+ReiBIdpHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.10.2
