---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubescape
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: default
  sources:
    - repoURL: "https://github.com/Darkflame72/home-ops.git"
      path: apps/policy/kubescape
      targetRevision: main
      ref: repo
    - repoURL: https://kubescape.github.io/helm-charts
      chart: kubescape-operator
      targetRevision: 1.30.3
      helm:
        releaseName: kubescape
        valueFiles:
          - $repo/apps/policy/kubescape/values.yaml
  destination:
    name: in-cluster
    namespace: policy
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
