# renovate: datasource=github-releases depName=external-secrets/external-secrets
# yaml-language-server: $schema=https://raw.githubusercontent.com/external-secrets/external-secrets/v2.7.0/deploy/charts/external-secrets/values.schema.json
leaderElect: true
resources:
  requests:
    cpu: 10m
    memory: 80Mi
  limits:
    memory: 320Mi
serviceMonitor:
  enabled: true
webhook:
  replicaCount: 2
  resources:
    requests:
      cpu: 10m
      memory: 192Mi
    limits:
      memory: 768Mi
certController:
  resources:
    requests:
      cpu: 10m
      memory: 80Mi
    limits:
      memory: 320Mi
grafanaDashboard:
  enabled: true
