apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:DF9nVp5SJR3BUDQSJEQY/5HWr9kKfWE20JHdOrx9c+Y3EKEvGPFWyA==,iv:zODkB0PceCcsVle1Be9KpuBJ+H2kNxQp27So0ZWs2sU=,tag:sOIOuCEAVWpBW2tSaVMpTg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxQ2xRbHllcDJxbW9ENE1n
            R29ZTy80SEptRzFJRUE3SWhGajBaNHNzZERRCnZEOHVrN3VIWHZUbTFuUk9iUk4v
            aWx1eXFFSVRkWmR3TTVLaWZJWGhGRlUKLS0tIFR1Q2duYWgrV3lvNGgvamRxc0ZS
            Q0dYUTZ4RCtsSnp3T1JRUGRmdlA4QncKaqLNZsZLiw6cdTz9M2b7wcpyxIcZGeTG
            L5G7rweXJYo5tgd6NtWMiUwIMfwziw0ZvrhzJVesiS8DVwRygicP6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-12T12:36:18Z"
    mac: ENC[AES256_GCM,data:g/pRDCA4AdSMmvCE0RMJpF7AHD5Cj6OMwfIM1BfWGZHslqKaIi7qkjO1qmj6n6NYGN7J5D0oRq8l9soTTukuII4LbZw2L0HhB8n1isQkjm7z3V+VwYaVcC74kZGwQWEqamIV8ayKC8pLoX6y+MJy4wgHgTlupjyEI08W19ozcyM=,iv:c5zBd50B8Xs2DZWT8cSIzlyfVG/uw0oM9vMERd3mez0=,tag:uHKNdGdnO0Pj1niYgPtHLA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
