apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:3vYw6IpBcSg2bDqSJoRD3KL1MIL7fOXs21+cGgXud4P4OdHW3h2BMA==,iv:A2QMP9+rhvnThyn6eoTvxChhGy3HcaClkQfRF26wcN4=,tag:YU5JqxwhKB6O+RwIN6mdiA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3clV5ZWNRdGtHbFhhOE1L
            cWZ3UFFkem56eCtwc21GWE45dy9XT0dQcUc4CnV0cDRUbGZBeVhhL3BFWTBKcmdX
            SnNBenBHVjV1OWxBOStyQk5RcGZ2dTQKLS0tIG0xb0lsenBSK0tMMHdoYmszYXJK
            aWRWNUpvTTRDWUZNY3BlZ0VXWlBrNDgKiN08Dm/rj23S5Qv5fDmEnUIKAEQOxc/N
            lRGPn8U4EzJWgtBaqoYbEjB4QK43N0btbBREBUi+RgajB4JMUQ2zOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T22:22:52Z"
    mac: ENC[AES256_GCM,data:3GOMLohI3MuJJp5N2HHaM2GLEeKZFe9FZWUQiTeEmhTFQMCOLnxy30CfOsTAdOqmTOml6kAjZ8gQ2BbfrXyXWHZYhsstez3N2op7QyM1ktRRYAGmTbAoXCgR1u6LRZQ+oRoO+fnnYsB+gMHqheZU5AcLGz/pSREiobbaEg547gg=,iv:5VgLPR3gvdeVADIg1l2Oaxp0iK7KpHeoklD+fzoVmsc=,tag:fkGb/0dtbKh84RjILbGN1Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
