apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:q3j9dYr0iX3HL/9bTjzINGY9lVFJaVlFFyGYEdCwgR0htxPA1mwsp7qhfQ9xjBInX8ARFMuzcj1ss+rB9HrMaVnFStMpfexlLbZUEzCDXnJDFrGF+cCZ2VdLKqYv/yKaFdsTshYLHsaVwlia1GX4IVA6rxq12hTyoG0TsWqDolhb6k26XZRdcVHSvmit8PnCx82/pW7wl+gvPWw/MoI3Tmxiby85emUGYjo2UVIvpxJCbc4YYGY/xgwAsL7c5RiXK14KhKF5SGP0NefJKS7jxknrVHmuQjU=,iv:1yQW6R6WpaaBU4rx91Qw/tIAWjriwFgPh6tLBzblcuQ=,tag:MvfNQLGcLheBXYqgCY9Zdw==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:3VrB7aWViqiZFm4CuRlRHyCwoY0i5NAFABsYdx4tWb3wIxv4PakoXLWJJySMIbnNpkB2SoTZRQTin//VFlcyhg==,iv:cmmkDcsNEccD3JIeGs00KAsbUlmeMm3Y9yVyKXNtgwc=,tag:z6myDPZwE/XytxHoQVKE5g==,type:str]
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:EqjfdacTlZDwPwr8njWPUVYWfLEQp86tZAyzOTEldGYYohHDJiq2Hw==,iv:C/CbxSjtqrKCr7UTwzHHarM9jsaQouPi7HAUESrf0Kk=,tag:/DnRyOKI+dm38/P/0C77wQ==,type:str]
    AUTHENTIK_ISSUER: ENC[AES256_GCM,data:l/Z92jCSM/HVqgeZ6L7KrMiSAED15A1Gesgs5Yp5oxpnWY9crVziCtGaxWSJxPO7p4+/,iv:qNQkCEZ+hdn0utNuGpDJmIr456M7hl9qcOFJFqGF55M=,tag:OxKsdKT3Ycdjlh7JT/jnyA==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:Y9yporMEFTc+NiZaXOdRPj6vYzxr/60gHvfZbJ3J1bpq7Ez6Irtmcz8KNxdojF5Ea/M9a0BDULj+xQVbkRYfxB+/QASbjvlppKA4Xm+szO83NP0eLdHLHk2me4auqbsGbskcG01NhP3mXDV34bcV/NyOUX0iaJmQ93Nh7z4Q9Cc=,iv:hQMnMBmgn07v6Oh6Tjui01T+KWwOPO1HZYXoXOh7wsk=,tag:L6ylYMIZyb4qwVti5ZBzpw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSFpJTHJNSFI1Rm9paUtz
            eU85VmZnMFU3MHdpTGgzeGh6dkJtNnNtSEEwCjJtMStkbG13ZWFUVnRObUxQY1ZQ
            Ky9ZeFpHSWVxa3Z5ZE91a2d1MFI5WDAKLS0tIEpPNkhqZlo2Y3lVRlptZmFGQitv
            TDBBRUhQY1JTWFFkNk5UVXhlRm1DeGMKU31f0RnLiKVVX8p/GLDaGxmZn/r9c1uG
            vk8qyOMYWVd4lvSihCdUdtj9lMPZhEp1NSGzsLiqCTrRnOIt7t5DyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:04:38Z"
    mac: ENC[AES256_GCM,data:KqO0+8oz0G0TFUINcSd64PyDzh8cJIQwzDf8U5cKiaesV6vEyeCn7e1EdsOu2gHhpseYGabNwMVY9oL6ui8ef3rJvrw7Z6rngMZMFaHIQJqKvtO4muECP68v6kCsjmLcxys1soiOfhtkwhUE1okby6aH9Pi7V3230GaF6n/OnwA=,iv:Ux0eA1YqTndQoCkHhBgP1OKFBZlwCT/MneOSLIL84NQ=,tag:RK+LIOG0dbVyo3VwO+oj9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-init-secret
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:zGP8a0iR+XxGvg==,iv:8EWxwYFLv3X1OvA2umk1AVKpmrBDjazo45WCHytFanE=,tag:Whti38HErY81sNIxToZ4Vw==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:2ME8fCHGgZ3qsOmmUoinOvFBLHAaGBlpcOTxtmoNOI3/+sOVZnyFKg==,iv:qOc6buWxEhGGIz0WuNXdIWhsRdrjjsG4dYGBqtUeLxE=,tag:SgsXx4u1Rv88Ncd0NHCEFg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:emxVvnuahyXwo8PFWLXR543T,iv:muRvmFT5UytnviAOdMzqjCLoebXSeL0272FfoRtT19A=,tag:R7SfuEXVSNEGR2FLp9MMhw==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:40oMMKDDCnObJcooykBhaxhlee+mQtcltDs6iR7JcqJrcyJ8OA7U+viLac2VUuLUCvmlV5uUGNFeYPD8Db3LDjAJW8sqYkOXwrHmMV0ZYxH3iklA/pZIbtYqBISJPdptGipHGE0/C2zxUnAfRDTwE3orvaD9MX4sMh5J1XyYoZo=,iv:lhvbYdNAzmyJZpQJ0cvLaGFRtSfnHj2tbmIZ0mjLE+Q=,tag:w/laR1+q7Jwg3uDOQUIZJg==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:74zP/PQHZOUTR+MqYYKVIYIv11DeqA6uzOHSA3DapDDME6jFaIZd2db4wAs7vwrcCouwkgQPym7SWjW2s9JSPRw7m9NH9a5mJ4B1hgfX/Hu/8H7/vmQAsfe2fGpURQ6UsA4UZoF4oKJOoWs/LWHLgG5rWQ7BQ8/wG4kuxCVZiik=,iv:DEW/aPRyZ4ZlJIUwPLM7+hK5Rc2DoqRDhkvXz1a6MHs=,tag:vT7dHLtODDFPu6/rlVuyWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1klg8akm9jh2u26y2yrgzvlutyapz033f9lkdzsd93zz3y8as9p7sn22gkt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVSFpJTHJNSFI1Rm9paUtz
            eU85VmZnMFU3MHdpTGgzeGh6dkJtNnNtSEEwCjJtMStkbG13ZWFUVnRObUxQY1ZQ
            Ky9ZeFpHSWVxa3Z5ZE91a2d1MFI5WDAKLS0tIEpPNkhqZlo2Y3lVRlptZmFGQitv
            TDBBRUhQY1JTWFFkNk5UVXhlRm1DeGMKU31f0RnLiKVVX8p/GLDaGxmZn/r9c1uG
            vk8qyOMYWVd4lvSihCdUdtj9lMPZhEp1NSGzsLiqCTrRnOIt7t5DyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-24T07:04:38Z"
    mac: ENC[AES256_GCM,data:KqO0+8oz0G0TFUINcSd64PyDzh8cJIQwzDf8U5cKiaesV6vEyeCn7e1EdsOu2gHhpseYGabNwMVY9oL6ui8ef3rJvrw7Z6rngMZMFaHIQJqKvtO4muECP68v6kCsjmLcxys1soiOfhtkwhUE1okby6aH9Pi7V3230GaF6n/OnwA=,iv:Ux0eA1YqTndQoCkHhBgP1OKFBZlwCT/MneOSLIL84NQ=,tag:RK+LIOG0dbVyo3VwO+oj9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
