apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secret
stringData:
    DATABASE_URL: ENC[AES256_GCM,data:8vvNQ6LLC503Dps2bYdlNUID6kc485SHl589P136Vdg3QY3+I6FUz3Vmn6ZzhkozT3a6NCqQ4FS2k4QB7Y4j78LWLbX6KBp92IPO1B0AUhlxHxvj4CZR5N2W82gkQBN8dQTKGaCu5JOSTpcitMwHZessAflw38XGrBPqgXSxCIn4N79rgE2RaVbEdIun3dtUov4Ir/vBn1tTIyseaMJ1NfHNh8fF4Q7w1aSJ1+wPZWQTwHgDVe0pUshHDrDfgue15hrTOUGM5pZ4Cf2Zv7+MSAQIMnxOksI=,iv:O7LXmVu5j58CDocGbRKAKSdGujcUWG/K/yNVAotfwSI=,tag:mRCkzCvjZeOkXyxbmCtJPg==,type:str]
    NEXTAUTH_SECRET: ENC[AES256_GCM,data:PeRNkz3laQZvh9LCnTaZRN1yU21MTQfFUzT4Wu2iuhYjfaZRTFspyjysS2aTa75kHvSuSA2ZEqRzDShq1nzR4w==,iv:AotFjJjcap4cDPGS0tItmbbBRAGySdvrJN622HfPRjE=,tag:drdYEayh4+lWk2N1/ILPbQ==,type:str]
    AUTHENTIK_CLIENT_ID: ENC[AES256_GCM,data:2aJ/VbOjZAQHdqkQ2XKXy1/1v2ZDZAkyHRbc/rMySVCjinuH8aNB8A==,iv:WxdJhWXlun4qBoQ/mAaMlDq3PgQxGZhltHMnp9/ijC0=,tag:OvZaLt/cHIL23stYTlgDjg==,type:str]
    AUTHENTIK_ISSUER: ENC[AES256_GCM,data:7Jr3sxU0258zmy2yhBK1UMZrfUazuVi/SXmG9IKvfklV2Mp98F36V8tLVsDw5qYYNnIH,iv:Voh5hhoma9vPs76k06eey3qOuzAAcJ7HRjWRaHVM0B0=,tag:1CIhWAikk8UVGbxXAYAyZg==,type:str]
    AUTHENTIK_CLIENT_SECRET: ENC[AES256_GCM,data:CL5UCYQ+vezPdfLyG2d3zetSbYW2lOylxtJ5FZHC722yttrC52LhNHdv8K2u4uTOuisKfoCBMxp7GMXA6IiyALFSHwtyaOMvsdLvsn8XB0N2YvJXQgwmu4En/DJ+cLsTBgpFGZmWHtBXviMv/A3koR/fM/26NswI5bgMwFgpPjo=,iv:2rkEVcSI7Im6Fb/SvDhAsCgCSGIAvJo0O+RAwkLRSlA=,tag:6dLsCYh3In6lvM1LNcU73Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeU5pQ2FOT21iSEdIb2pu
            NHhLR0FpMkFjL0FpOHVMUmdacysxMUxPSlNjClQ3YTFJemMzRE1aWmhYaXlBOE41
            ZkhrTFRDYW9CTytueStncE9uNjJLL0EKLS0tIDZuSnBsWDN2WDVkdnNZUC9DZ0JQ
            S2F4b0RKYXduWVExeUJKMUl0L2loV1UKaaoksyqsBCDdEIDXTz+QPTxvuSteM23w
            LqxhXuQl9fVP5RTJzPJAHwjIJ3R8bp8437qOhpaOJIbEtiGueSWMjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T23:53:25Z"
    mac: ENC[AES256_GCM,data:S4l8558Wxwzrw+xI8tcYMb0AbZVk4jeui+WAV7LxqCNP0HVffUIfF8yrbk9KeUM0qzrOfQt8j+KEngUULFCRa4uGm8+3E4cblWLaSlvhio74Lao4/+9zwKwpVK1bzbzu3ndC9G8D8cw0TbUMGgXBNl61VNJVHm4/GFpdS+ZePE8=,iv:VjWrgZyby4+BnV9Zwi/vglQkd9IXwXubbq3AQY8XluE=,tag:ZR1gf009eTTgoghrvi9etA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
---
apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-init
stringData:
    INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:V/byn/sKDUhZGw==,iv:u6BNuJuwCDF8GAF+2XMtyBuOzTXI+uKeQAs9Ftx86VM=,tag:Paln5SufKUy7RXVi6KRzJA==,type:str]
    INIT_POSTGRES_HOST: ENC[AES256_GCM,data:pJUzeSwpFDwFkg8YQdEe8qlvrvIBQIDLhaM89Y1grelltiFEEMqnHg==,iv:IUQP/uWUDBf+5ETgSaNw5BRcHESnHkXRbCWYixqBPG8=,tag:u70SrNLvdSt8530JIjFkOg==,type:str]
    INIT_POSTGRES_USER: ENC[AES256_GCM,data:DQ184TcN3HTuGVKbVbZQqzWv,iv:akRDX0mbTl4Hsy3FzHeWQZaDUsjNr4VOrHDPhfdYRCg=,tag:ZMumT/ynpaBmIuUGwt7urQ==,type:str]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:haPPkwPZeaLzJMF2+NCjwRlwP0arochmKYpNfwd7CzMsugZsQcI2qsr5UwsXFFdiLj22W9yNDNmLvYf81tdLZM4i1l0gt9E7+5Rhhs+1Y9zwFprehShtL9n9o7cE9R+VYasjemYobAJlQDLR2c9YljwI5BoQe2R5zyk6tC7yR6Y=,iv:0G3AvRXmWEI0WiVC7muTiU9TFj39uIn1cC4L1Jvi8ck=,tag:tHkPdeCc0yK/mw+RzyC6hQ==,type:str]
    INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:y9S2MimGeYRjJTbdNadP8MwKFhnAECIJjgjIcnUfFWqjgOS3I+QAWjNHrmqCFP5eyK68Umv4Psl4dfCZC7h2ENcilTVwkOA0SdlFfAyyo47VZdUN2fnikf5DseaMm5xmH4hVKU/AIWLQYmx/wZC4jHCEdSvaoLmg/znU8Prd2dA=,iv:6ZvCp8/PVUwfcocOTl40m2ZLtfMb0o2NF9yMCrsI9LM=,tag:XcVzd4C6mOSLrhQcs6rksw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZeU5pQ2FOT21iSEdIb2pu
            NHhLR0FpMkFjL0FpOHVMUmdacysxMUxPSlNjClQ3YTFJemMzRE1aWmhYaXlBOE41
            ZkhrTFRDYW9CTytueStncE9uNjJLL0EKLS0tIDZuSnBsWDN2WDVkdnNZUC9DZ0JQ
            S2F4b0RKYXduWVExeUJKMUl0L2loV1UKaaoksyqsBCDdEIDXTz+QPTxvuSteM23w
            LqxhXuQl9fVP5RTJzPJAHwjIJ3R8bp8437qOhpaOJIbEtiGueSWMjg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-13T23:53:25Z"
    mac: ENC[AES256_GCM,data:S4l8558Wxwzrw+xI8tcYMb0AbZVk4jeui+WAV7LxqCNP0HVffUIfF8yrbk9KeUM0qzrOfQt8j+KEngUULFCRa4uGm8+3E4cblWLaSlvhio74Lao4/+9zwKwpVK1bzbzu3ndC9G8D8cw0TbUMGgXBNl61VNJVHm4/GFpdS+ZePE8=,iv:VjWrgZyby4+BnV9Zwi/vglQkd9IXwXubbq3AQY8XluE=,tag:ZR1gf009eTTgoghrvi9etA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.2
