apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-secret
stringData:
    DATABASE_URL: postgres://linkwarden_db_user:8d0088f73c1174d299dc465fa6f8afc3b8563e4f507cd05d78946060d100cd493ce0fa7c00a91ca266aa1ce36ec8ba1d6345ee014427ba2bfaa8f7d1742dc0de@postgres16-rw.database.svc.cluster.local:5432/linkwarden
    NEXTAUTH_SECRET: 881aefadb8546006cdb60aac00c345cebcf05e94c505177663cd83519044bc04
    AUTHENTIK_CLIENT_ID: mIa5J710SYWMuobumGQ4HqpgbMiMfAnvgdXjjIrq
    AUTHENTIK_ISSUER: https://auth.darkflame.dev/application/o/linkwarden
    AUTHENTIK_CLIENT_SECRET: kdQhnmyNuMFGqYic58dm7R8pBL3wbEdzbywyR57iPdK7PhTvzFvuJGKD1zpWsZEJvvM8nNxxWmTMUUK95Fcqpt5S6wH2oObsBSIvWxzjuvSxXxSvTbLUcCDMeCB99K2p
---
apiVersion: v1
kind: Secret
metadata:
    name: linkwarden-init-secret
stringData:
    INIT_POSTGRES_DBNAME: linkwarden
    INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local
    INIT_POSTGRES_USER: linkwarden_db_user
    INIT_POSTGRES_PASS: 8d0088f73c1174d299dc465fa6f8afc3b8563e4f507cd05d78946060d100cd493ce0fa7c00a91ca266aa1ce36ec8ba1d6345ee014427ba2bfaa8f7d1742dc0de
    INIT_POSTGRES_SUPER_PASS: 8d0088f73c1174d299dc465fa6f8afc3b8563e4f507cd05d78946060d100cd493ce0fa7c00a91ca266aa1ce36ec8ba1d6345ee014427ba2bfaa8f7d1742dc0de
