---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/monitoring.coreos.com/podmonitor_v1.json
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: gotosocial-postgres
  namespace: comms
spec:
  namespaceSelector:
    matchNames:
      - comms
  selector:
    matchLabels:
      cnpg.io/cluster: gotosocial-postgres
      cnpg.io/podRole: instance
  podMetricsEndpoints:
    - port: metrics
      relabelings:
        - action: replace
          sourceLabels: [__meta_kubernetes_pod_label_cnpg_io_cluster]
          targetLabel: cluster
