apiVersion: v1
kind: Secret
metadata:
    name: ocis-secret
stringData:
    OCIS_JWT_SECRET: ENC[AES256_GCM,data:egxw0pR94OfnJD3c/dN6OP1mMtSVr3idsz2whX609u4uBawkBAi61UP0MojCWFVOcu/znA2Y7c+SiW8UT1UWpa5vNIeeUkPsChG9AL9pQP+RzRTWabWOLMXA4/iHLvvIl1kH0jdIAyhFILG37hCB6G5KbbX7UxtZmcIa8hp7Yic=,iv:SNkv787j8hGNtQj7GGwVpTC/wkIb7GC7LIBQ8+sBJTc=,tag:X2U+yMtLlZwQWGfdOZR/1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16eahsyapth9w8w5h6qmpetqayp57qlntvlzecd06lda33ce62sqqxjmawf
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUU03bTlXQTZlYVNOWVZq
            UFY4akJuME1Uc3AwVzZHenRWaVpnaHFmNG1RCmwvSE1neHJtQmErczk4RXlMRk1R
            TXJiYkJ4RmVQMG1jWURzRHlpdlBHN0kKLS0tIFJJdFgwOEFheWw0bElaRWt2Q200
            dnRFaG1LS3g1akVKZXFhUFZaVnczWUUKOPR1Xj8jzE+EzdNa4n8KGluQAtMUseKh
            aF6TTY61r8Z8HZi9aN75eWE8e7k6iBczZxY24+EmPU4Ar0mXApypjw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-11T13:41:50Z"
    mac: ENC[AES256_GCM,data:CL7x+Xi9HQ0AB7jc22a7BSf4YnEHGojolJTmhTAy9G8OtrkymSTNEbqB+gdiu5t9TVbScBPPHkMIoNbEzqR+60m4NhoedL/82KKxdJGgT5/m8pURGNCaC97jr7izt2qLehWc3WdQPI30CcqPNiNS1lU68DhkpHLMUJKLPWk7FFI=,iv:g0IicdO4wEr/b1BEtIkIN4BzIshau14RfviIZE3LggY=,tag:GEWdAn8CSWbYYh0QIg/lqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
