name: drydock

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: drydock-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  drydock:
    name: Diff
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Run drydock
        uses: sholdee/drydock/pr-action@a3f5c18c71c7866e3f88b692469854c70208057c # v0.3.0
        with:
          # renovate: datasource=github-releases depName=sholdee/drydock
          version: v0.3.0
