name: drydock

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: drydock-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  drydock:
    name: Diff
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Run drydock
        uses: sholdee/drydock/pr-action@4275b182fafed3e0cb185ba467c3e2c6c02b86e8 # v0.2.8
        with:
          # renovate: datasource=github-releases depName=sholdee/drydock
          version: v0.2.8
