name: drydock

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

concurrency:
  group: drydock-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  drydock:
    name: Diff
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Run drydock
        uses: sholdee/drydock/pr-action@46be45ba2e5e29ea40dce6047217b33861471e8e # v0.2.10
        with:
          # renovate: datasource=github-releases depName=sholdee/drydock
          version: v0.2.10
